ice-blockchain/ion-framework

- ios/Podfile.lock
- lib/app/services/media_service/media_service.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This PR integrates image compression and resizing functionalities across all platforms and addresses enhancements for image processing.
Image Compression & Resizing:
Integrated compress and resize functions for image optimization.
Added `cross_file` package to handle files across all supported platforms (mobile, web, and desktop).
Used the `image` package to resize images effectively.
Implemented `image_compression_flutter` to handle image compression efficiently, improving overall performance and file size management.
Tested on iOS, Android, Web, MacOS and Windows
> feat: add image compress and resize functionality

- packages/ion_identity_client/example/lib/pages/user_wallets/user_wallets_page.dart
- packages/ion_identity_client/example/lib/pages/wallet_transfer_requests/providers/wallet_transfer_requests_provider.dart
- packages/ion_identity_client/example/lib/pages/wallet_transfer_requests/wallet_transfer_requests_page.dart
- packages/ion_identity_client/lib/ion_client.dart
- packages/ion_identity_client/lib/src/core/service_locator/clients_service_locator.dart
- packages/ion_identity_client/lib/src/wallets/ion_wallets.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/data_sources/get_wallet_transfer_requests_data_source.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/get_wallet_transfer_requests_service.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/transfer_request_body.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/transfer_request_body.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/transfer_request_body.g.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/transfer_requester.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/transfer_requester.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/transfer_requester.g.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/wallet_transfer_request.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/wallet_transfer_request.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/wallet_transfer_request.g.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/wallet_transfer_requests.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/wallet_transfer_requests.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/wallet_transfer_requests.g.dart
Adds `GetWalletTransferRequestsService` with examples
- `GetWalletTransferRequestsService` with dependencies
- Added example
> feat(ion-identity-client): Add GetWalletTransferRequestsService

- .github/PULL_REQUEST_TEMPLATE.md
This PR adds pull request template to streamline our reviews. It highlights the purpose, type of change, and any visuals if needed.
> docs: add pull request template for consistent PR submissions

- lib/app/features/wallet/views/pages/coins_flow/network_list/network_item.dart
- lib/app/features/wallet/views/pages/coins_flow/network_list/network_list_view.dart
Update UI for the "Choose network" page.
[Design](https://www.figma.com/design/3TnZngoFeklOVC8TexlR1D/%F0%9F%A7%8A-ICE-Cloud?node-id=43380-111245&m=dev)
> chore: update Choose network page

- packages/ion_identity_client/lib/src/signer/dtos/user_action_signing_init_request.dart
- packages/ion_identity_client/lib/src/signer/dtos/user_action_signing_init_request.freezed.dart
- packages/ion_identity_client/lib/src/signer/dtos/user_action_signing_init_request.g.dart
Fix for a UserActionSinger init request
Previously optional field is now required
> fix(ion identity client): add `userActionServerKind` to UserActionSigningInitRequest

- lib/app/features/chat/messages/views/components/message_types/photo_message/photo_message.dart
- lib/app/features/chat/messages/views/components/message_types/video_message/components/message_with_timestamp.dart
- lib/app/features/chat/messages/views/components/message_types/video_message/video_message.dart
- lib/app/features/chat/messages/views/pages/messages_page.dart
- lib/app/features/core/providers/video_player_provider.dart
This PR improves the photo and video message components by:
- Adding dynamic width calculations for media content
- Implementing proper constraints for photo/video dimensions
- Fixing layout issues with message content alignment
- Video player controller factory has been refactored to be more efficient
https://www.figma.com/design/3TnZngoFeklOVC8TexlR1D/%F0%9F%A7%8A-ICE-Cloud?node-id=46807-138942&m=dev
> refactor: Enhance Photo & Video Message Components with Dynamic Sizing

- lib/app/features/feed/stories/views/components/story_viewer/components/core/stories_swiper.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/core/user_story_page_view.dart
> fix: 3d-transition in the end of progress

- lib/app/extensions/asset_gen_image.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/core/story_content.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/header/header.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/header/header_actions.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/header/story_header_gradient.dart
- pubspec.lock
- pubspec.yaml
> fix: [ION-363] add a shadow of the icons in the header

- packages/ion_identity_client/example/lib/pages/wallet_generate_signature/providers/generate_signature_notifier.dart
Fixes compilation error because previously I forgot to update code for example. Example is excluded from analyzer, so I didn't notice it.
> fix(ion identity client): compilation error

- lib/app/features/wallet/views/pages/wallet_page/components/tabs/tabs_header.dart
> fix: remove hide option from wallet menu

- lib/app/features/feed/create_article/views/pages/create_article_preview_modal/components/create_article_topics.dart
- lib/app/features/feed/create_article/views/pages/create_article_preview_modal/components/select_arcticle_visibility_item.dart
- lib/l10n/app_en.arb
> fix: wrong localization for article preview

- lib/app/features/protect_account/backup/views/pages/backup_recovery_keys_modal.dart
> fix: add next arrow to lets start button on secure your recovery keys info modal

- lib/app/features/protect_account/components/delete_twofa_select_options_step.dart
- lib/app/features/protect_account/components/delete_twofa_step_scaffold.dart
Redesign screens with delete 2fa options
> feat: redesign twofa delete options

- lib/app/features/video/views/hooks/use_status_bar_color.dart
- lib/app/features/video/views/pages/videos_page.dart
Fix status bar color after pop from video
> fix: status bar color after pop

- lib/app/exceptions/exceptions.dart
- lib/app/features/feed/create_post/providers/create_post_notifier.c.dart
- lib/app/features/feed/create_post/views/pages/compress_test_page.dart
- lib/app/features/user/providers/avatar_processor_notifier.c.dart
- lib/app/features/user/providers/banner_processor_notifier.c.dart
- lib/app/services/audio_wave_playback_service/audio_wave_playback_service.c.dart
- lib/app/services/compressor/compress_service.c.dart
- pubspec.lock
- pubspec.yaml
Add Brotli compressor/decompressor to the project.
> feat: add Brotli compressor

- lib/app/features/protect_account/backup/data/models/recovery_key_property.dart
- lib/app/features/protect_account/backup/views/pages/validate_recovery_key_page.dart
> fix: revert recovery keys order

- lib/app/features/feed/stories/providers/stories_provider.c.dart
- lib/app/features/protect_account/authenticator/views/pages/delete_authenticator/authenticator_delete_page.dart
- lib/app/features/protect_account/components/delete_twofa_input_step.dart
Add missing 2fa warning
Fix override exception
> fix: add missing 2fa warning

- lib/app/features/protect_account/authenticator/views/pages/delete_authenticator/components/delete_authenticator_initial_step.dart
- lib/app/features/protect_account/authenticator/views/pages/delete_authenticator/components/delete_authenticator_input_step.dart
- lib/app/features/protect_account/authenticator/views/pages/delete_authenticator/components/delete_authenticator_select_options_step.dart
> fix: use correct icons for delete authenticator pages

- lib/app/features/auth/views/components/auth_scrolled_body/auth_header.dart
> fix: set static width for auth header to match design text wraps

- lib/app/features/protect_account/phone/provider/country_provider.c.dart
> feat: set default phone country based on device locale

- lib/app/features/protect_account/backup/views/pages/recovery_keys_success_page.dart
Redesign backup keys success page
> feat: redesign backup keys success page

- lib/app/features/feed/create_post/views/components/post_submit_button/post_submit_button.dart
Small fix to allow making post only with media.
https://github.com/user-attachments/assets/844c8599-b926-45c0-a444-4d00df85b944
> fix: allow making post only with attached media

- lib/app/features/auth/views/pages/fill_profile/fill_profile.dart
- lib/app/features/user/pages/profile_edit_page/profile_edit_page.dart
Name and nickname was messed, so switch them back
> fix: switch name and nickname

- lib/app/features/feed/stories/views/components/story_capture/controls/story_gallery_button.dart
- lib/app/features/feed/stories/views/pages/story_record_page.dart
- lib/app/services/media_service/banuba_service.c.dart
- enable the banuba editor
- handling of the possible exceptions
> feat: enable banuba editor

- lib/app/features/video/views/hooks/use_video_ended.dart
- lib/app/features/video/views/pages/video_page.dart
- lib/app/router/feed_routes.dart
- Change navigation to `VideosPage` similar as for `Stories` with `fullstack` pattern
- Add play/pause by app state and page visibility
> feat: video improvements

- lib/app/features/protect_account/phone/views/pages/setup_phone/phone_setup_input_page.dart
> fix: add clear button to phone number setup text field

- lib/app/utils/retry.dart
> fix: convert future to stream in withRetry function

- lib/app/features/nostr/providers/nostr_notifier.c.dart
- lib/app/utils/retry.dart
> fix: retry only on RelayRequestFailedException for relay requests and events

- .tool-versions
- lib/app/features/auth/views/components/identity_key_name_input/identity_key_name_input.dart
- lib/app/features/auth/views/components/user_data_inputs/name_input.dart
- lib/app/features/auth/views/components/user_data_inputs/nickname_input.dart
- lib/app/utils/validators.dart
- lib/l10n/app_en.arb
Add validator for Identity name.
Remove validator for Name field, only nickname validate.
> feat: remove validator for name field

- .tool-versions
- lib/app/exceptions/exceptions.dart
- lib/app/features/nostr/model/auth_event.c.dart
- lib/app/features/nostr/providers/auth_challenge_provider.c.dart
- lib/app/features/nostr/providers/mixins/relay_auth_mixin.dart
- lib/app/features/nostr/providers/mixins/relay_timer_mixin.dart
- lib/app/features/nostr/providers/nostr_notifier.c.dart
- lib/app/features/nostr/providers/relays_provider.c.dart
- lib/app/utils/retry.dart
- melos.yaml
- pubspec.lock
- pubspec.yaml
Add Auth flow for required resources
- Add mixins for close relay on timer, for listen `AuthMessage`
- Add `error` to retry task for manipulate with it in task
> feat: add auth event

- lib/app/features/protect_account/authenticator/views/pages/setup_authenticator/authenticator_setup_instructions_page.dart
- lib/app/features/protect_account/authenticator/views/pages/setup_authenticator/components/authenticator_setup_instructions_error_state.dart
- lib/app/features/protect_account/authenticator/views/pages/setup_authenticator/components/authenticator_setup_instructions_success_state.dart
- lib/app/features/protect_account/secure_account/providers/request_twofa_code_notifier.c.dart
https://github.com/user-attachments/assets/905670ef-901c-43a6-8bb2-ea0651fe405c
> fix: add error handling to authenticator setup page

- lib/app/features/protect_account/authenticator/views/pages/setup_authenticator/authenticator_setup_code_confirm_page.dart
- lib/app/features/protect_account/common/two_fa_utils.dart
- lib/app/features/protect_account/email/views/pages/setup_email/email_setup_confirm_page.dart
- lib/app/features/protect_account/phone/views/pages/setup_phone/phone_setup_confirm_page.dart
- lib/app/features/protect_account/secure_account/providers/validate_twofa_code_notifier.c.dart
> fix: add eror handling for code confirmation on auth, phone and email setups

- analysis_options.yaml
- lib/app/exceptions/exceptions.dart
- lib/app/features/chat/providers/fetch_conversation_provider.c.dart
- lib/app/features/chat/views/pages/chat_main_page/chat_main_page.dart
- lib/app/features/nostr/providers/nostr_notifier.c.dart
- lib/app/services/database/ion_database.c.dart
- lib/app/services/nostr/ion_connect_gift_wrap_service.c.dart
- lib/app/services/nostr/ion_connect_seal_service.c.dart
- pubspec.lock
- pubspec.yaml
- test/app/services/nostr/ion_connect_gift_wrap_service_test.dart
- test/app/services/nostr/ion_connect_seal_service_test.dart
- New `fetchAndSyncConversations` provider for e2ee chat syncing
- Added persistent subscriptions support in NostrNotifier
- Refactored gift wrap and seal services with proper annotations
N/A
> feature: fetch e2ee chats and sync to local database

- lib/app/features/feed/stories/views/pages/story_preview_page.dart
> fix: show a dialog with the visibility options

- lib/app/exceptions/exceptions.dart
- lib/app/features/chat/providers/conversation_management_provider.c.dart
- lib/app/features/chat/providers/conversation_message_management_provider.c.dart
- scripts/generate_code.sh
- `PrivateDirectChatService` renamed to `ConversationMessageManagementService`
- `ConversationManagementService` added: add participant, remove participant, change subject
> feat: Change conversation participants and subject

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- pubspec.lock
- pubspec.yaml
On Android 15 device, action bar override the crop image container. This package has a newer version for android 15.
https://github.com/hnvn/flutter_image_cropper/commit/ae59e78faf0b13c699d71c194d0452e74003ff9d#diff-6560afb2187da7ae5b88875a99eb907b6e2b3160465a92e588dd431bfe5fbe70R4
> fix: upgrade crop image package for android 15

- lib/app/features/feed/views/pages/feed_page/feed_page.dart
The small change which will be reverted soon.
> chore: hide trending videos in feed

- lib/app/features/components/entities_list/components/article_list_item.dart
- lib/app/features/components/entities_list/components/generic_repost_list_item.dart
- lib/app/features/components/entities_list/components/post_list_item.dart
- lib/app/features/components/entities_list/components/repost_list_item.dart
> fix: improve tap gesture detection on post/article cells

- lib/app/features/chat/messages/views/components/message_types/money_message/components/amount_display.dart
- lib/app/features/chat/messages/views/components/message_types/money_message/money_message.dart
- lib/app/features/wallet/components/arrival_time/arrival_time_indicator.dart
- lib/app/features/wallet/components/coin_icon_with_network/coin_icon_with_network.dart
- lib/app/features/wallet/components/send_to_recipient/send_to_recipient.dart
- lib/app/features/wallet/model/coin_data.c.dart
- lib/app/features/wallet/model/crypto_asset_data.c.dart
- lib/app/features/wallet/views/pages/coins_flow/network_list/network_item.dart
- lib/app/features/wallet/views/pages/coins_flow/providers/send_asset_form_provider.c.dart
- lib/app/features/wallet/views/pages/coins_flow/receive_coins/components/info_card.dart
- lib/app/features/wallet/views/pages/coins_flow/receive_coins/components/receive_info_card.dart
- lib/app/features/wallet/views/pages/coins_flow/send_coins/components/buttons/coin_amount_input.dart
- lib/app/features/wallet/views/pages/coins_flow/send_coins/components/confirmation/confirmation_sheet.dart
- lib/app/features/wallet/views/pages/coins_flow/send_coins/components/confirmation/transaction_amount_summary.dart
- lib/app/features/wallet/views/pages/coins_flow/send_coins/components/confirmation/transaction_result_sheet.dart
- lib/app/features/wallet/views/pages/coins_flow/send_coins/components/contact_input_switcher.dart
- lib/app/features/wallet/views/pages/coins_flow/send_coins/components/send_coins_form.dart
- lib/app/features/wallet/views/pages/transaction_details/transaction_details.dart
- lib/app/router/wallet_routes.dart
- lib/app/utils/num.dart
- lib/l10n/app_en.arb
Updated UI for the Send coins pages. Fixed small bugs there too.
> fix: update UI for the Send Coins pages

- lib/app/features/feed/create_post/views/components/reply_input_field/reply_input_field.dart
> fix: replace unique key with global key to avoid losing focus on post details reply bottom textfield

- lib/app/router/main_tabs/main_tab_navigation.dart
> fix: add safe area to main bottom navigation bar

- lib/app/features/feed/providers/replies_provider.c.dart
- lib/app/features/feed/views/pages/post_details_page/components/reply_list/reply_list.dart
https://github.com/user-attachments/assets/65f8099e-6fd9-4fa3-8e31-a07d31cc4810
> fix: add live refresh to reply list so that fresh created replies are visible

- lib/app/exceptions/exceptions.dart
- lib/app/features/core/model/feature_flags.dart
- lib/app/features/core/providers/feature_flags_provider.c.dart
- lib/app/features/feed/views/pages/feed_page/feed_page.dart
- lib/app/features/wallet/views/pages/wallet_page/components/loaders/grid_loader.dart
- lib/app/features/wallet/views/pages/wallet_page/components/nfts/nfts_tab_footer.dart
1. Hide "Buy nft" button for 1.0 app version.
2. Add feature flags provider.
> chore: hide buy nft button

- lib/app/router/components/sheet_content/sheet_content.dart
> fix: bring back bottom bar inside sheet content

- lib/app/features/chat/views/components/type_selection_list_item.dart
- lib/app/features/chat/views/pages/new_group_modal/pages/add_group_participants_modal.dart
- lib/app/features/chat/views/pages/new_group_modal/pages/create_group_modal.dart
- lib/app/features/gallery/views/components/gallery_grid_cell.dart
- lib/app/features/gallery/views/components/gallery_grid_view.dart
- lib/app/features/gallery/views/pages/media_picker_page.dart
- pubspec.lock
Create group flow fixes:
- Edit button to lower case
- Arrow for "Next" button
- Group picture picker without selector
> fix: create group UI bugs

- lib/app/features/wallet/views/pages/coins_flow/coin_details/components/balance/balance.dart
- lib/app/features/wallet/views/pages/coins_flow/coin_receive_modal/coin_receive_modal.dart
- lib/app/features/wallet/views/pages/coins_flow/coin_receive_modal/components/coin_address_tile/coin_address_tile.dart
- lib/app/features/wallet/views/pages/coins_flow/network_list/network_list_view.dart
- lib/app/features/wallet/views/pages/coins_flow/receive_coins/components/share_address_view.dart
- lib/app/features/wallet/views/pages/coins_flow/receive_coins/providers/receive_coins_form_provider.c.dart
- lib/app/router/app_routes.c.dart
- lib/app/router/wallet_routes.dart
Fixed receive coins modal issues. Added `onTap` listeners for the most buttons.
https://github.com/user-attachments/assets/acf55e72-1ac1-4d99-8854-08deb94689b8
> fix: receive coins modal issues

- lib/app/components/inputs/text_input/components/text_input_decoration.dart
- lib/l10n/app_en.arb
Adjust input field error message
- Change error text
- Change error text style
> feat: change error text, floatingLabelStyle

- lib/app/features/feed/create_post/views/components/reply_input_field/reply_input_field.dart
This PR introduces the author avatar displaying a near reply field for an unfocused state
> feat: add avatar displaying for unfocused state

- lib/app/features/feed/data/models/bookmarks/bookmarks_set.c.dart
- lib/app/features/feed/data/models/entities/post_data.c.dart
- lib/app/features/feed/providers/bookmarks_notifier.c.dart
Removes stories type bookmark set, as there are going to be no bookmarking feature for stories
> chore: remove stories type bookmarks

- ios/Podfile.lock
- lib/app/features/protect_account/backup/views/pages/create_recover_key_page/create_recovery_key_page.dart
> fix: add scroll for recovery page

- lib/app/features/debug/views/debug_shake_gesture.dart
- lib/app/services/logger/logger.dart
Resolve the pop issue caused by the top-level `Navigator`.
Fix the pop issue by utilizing the `rootNavigatorKey`.
> fix: pop bottom sheet

- lib/app/features/feed/providers/feed_filter_relays_provider.c.dart
- lib/app/features/feed/providers/feed_stories_data_source_provider.c.dart
> fix: show own story

- lib/app/features/ion_connect/model/ion_connect_auth.c.dart
This PR update the token prefix
N/A
> fix: update auth token prefix to bearer

- ios/Podfile.lock
- lib/app/components/scroll_view/load_more_builder.dart
- lib/app/features/feed/providers/feed_posts_data_source_provider.c.dart
> feat: improve pagination experience on feed

- lib/app/features/ion_connect/providers/ion_connect_event_signer_provider.c.dart
> chore: add storage key migration todo

- lib/app/features/wallet/data/coins/database/coins_dao.c.dart
- lib/app/features/wallet/data/coins/repository/coins_repository.c.dart
- packages/ion_identity_client/lib/src/coins/ion_identity_coins.dart
- packages/ion_identity_client/lib/src/coins/services/data_sources/get_coins_data_source.dart
- packages/ion_identity_client/lib/src/coins/services/get_coins_service.dart
- packages/ion_identity_client/lib/src/core/network/network_client.dart
1. Added methods to get coins from DB by id. Also, fixed other HTTP client methods to handle list responses. 
2. HTTP request to get all the user coins with symbol and wallet info (balances, etc).
> feat: methods to provide coins data from the DB

- .github/workflows/CICD.yaml
- .gitignore
- ios/Podfile.lock
- lib/app/features/core/providers/init_provider.c.dart
- lib/app/features/wallet/data/coins/domain/coin_initializer.c.dart
- lib/app/features/wallet/data/coins/domain/coin_sync_service.c.dart
- lib/app/features/wallet/data/coins/repository/coins_repository.c.dart
- packages/ion_identity_client/lib/src/coins/services/data_sources/get_coins_data_source.dart
- packages/ion_identity_client/lib/src/core/network/utils.dart
- pubspec.yaml
Add `assets/ion_identity/coins_version.txt` during build time and use it in run time to set the coins version.
- Update `CoinsRepository` to use `localStorage` to keep `last sync time` and `coins version`
- Update `parseJsonObject` to handle `null` value
> feat(wallets): get Coins version during build and using at runtime

- packages/ion_identity_client/lib/src/coins/models/coin.c.dart
Fix a strange Freezed issue with our Coin class
> fix: convert block to expression in Coin

- ios/Podfile.lock
- lib/app/components/video_preview/video_preview.dart
- lib/app/features/components/entities_list/components/post_list_item.dart
- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_item.dart
Fix for dispose video player controller in feed.
- Add blur with thumb while video is loading.
> fix: feed video player

- lib/app/features/auth/views/pages/recover_user_page/components/twofa_input_step.dart
- lib/app/features/auth/views/pages/recover_user_page/components/twofa_options_step.dart
- lib/app/features/auth/views/pages/recover_user_page/recover_user_page.dart
- lib/app/features/auth/views/pages/recover_user_twofa_page/components/twofa_code_input.dart
- lib/app/features/auth/views/pages/recover_user_twofa_page/components/twofa_option_selector.dart
- lib/app/features/protect_account/backup/views/pages/create_recover_key_page/components/create_recovery_key_success_state.dart
- lib/app/features/protect_account/backup/views/pages/create_recover_key_page/create_recovery_key_page.dart
- lib/l10n/app_en.arb
- packages/ion_identity_client/lib/src/auth/services/twofa/data_sources/twofa_data_source.dart
- packages/ion_identity_client/lib/src/core/types/ion_exception.dart
> fix: account recovery error handling 2fa

- lib/app/features/auth/views/components/user_data_inputs/name_input.dart
- lib/app/utils/validators.dart
- lib/l10n/app_en.arb
Disallowed fancy fonts for profile name
> fix: profile custom font name

- lib/app/features/feed/providers/article/mention_suggestions_provider.c.dart
- lib/app/features/ion_connect/model/search_extension.dart
- lib/app/features/user/providers/search_users_data_source_provider.c.dart
- test/app/services/ion_connect/model/search_extension_test.dart
Add `SearchQueryExtension` to wrap query with quotes.
- Cover `search_extension.dart` with tests.
> feat: add search query extention

- lib/app/features/chat/providers/fetch_conversation_provider.c.dart
- lib/app/features/feed/data/models/entities/event_count_result_data.c.dart
- lib/app/features/feed/providers/bookmarks_notifier.c.dart
- lib/app/features/feed/providers/feed_posts_data_source_provider.c.dart
- lib/app/features/feed/providers/replies_data_source_provider.c.dart
- lib/app/features/user/providers/followers_data_source_provider.c.dart
- lib/app/features/user/providers/followers_you_know_data_source_provider.c.dart
- lib/app/features/user/providers/user_articles_data_source_provider.c.dart
- pubspec.lock
- pubspec.yaml
Integrate generic tags to `RequestFilter`.
> refactor: generic tags for request filter

- lib/app/components/counter_items_footer/replies_counter_button.dart
- lib/app/features/feed/providers/can_reply_notifier.c.dart
> fix: prevent multiple modals present when reply button is quickly tapped a few times

- lib/app/features/feed/stories/views/components/story_viewer/components/header/story_viewer_header.dart
> fix: swap display name and nickname in story viewer header

- lib/app/components/counter_items_footer/replies_counter_button.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/core/story_content.dart
> fix: hide reply textfield on story when cant reply

- lib/app/features/feed/stories/views/components/story_capture/controls/story_gallery_button.dart
- lib/app/features/feed/stories/views/pages/story_record_page.dart
- lib/app/services/media_service/image_proccessing_config.dart
- add crop functionality for stories
- add media picker reopening on the banuba editor cancel
https://github.com/user-attachments/assets/92b7ae5d-8ca0-43e1-8ff5-34f4070e07fa
> feat: add crop functionality for stories

- lib/app/features/auth/views/components/recovery_keys_input_container/recovery_keys_input_container.dart
- lib/app/features/auth/views/pages/recover_user_page/components/recovery_creds_step.dart
> fix: incorrect text on restore identity key input page

- lib/app/features/wallets/views/pages/contact_modal_page/contact_modal_page.dart
- lib/app/features/wallets/views/pages/wallet_page.dart
- lib/app/features/wallets/views/pages/wallet_page/components/contacts/contacts_list.dart
- lib/app/features/wallets/views/pages/wallet_page/components/contacts/contacts_list_header.dart
> fix: wallet UI issues

- lib/app/features/feed/stories/views/pages/story_viewer_page.dart
> fix: restore status bar color after closing stories

- lib/app/features/user/pages/profile_page/components/header/user_list_item.dart
- lib/app/features/user/pages/profile_page/pages/follow_list_modal/components/follow_list_item.dart
Swap name and nickname
- Swapped for Follow/Following modal page
- Profile tab
> fix: swap names

- lib/app/features/user/providers/followers_count_provider.c.dart
Fix `RequestFilter` for `EventCountResultEntity`
> fix: RequestFilter for EventCountResultEntity

- lib/app/features/wallets/model/coin_in_wallet_data.c.dart
- lib/app/features/wallets/providers/current_user_wallet_views_provider.c.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_assets/models/wallet_asset.c.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_assets/models/wallet_asset.c.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_assets/models/wallet_asset.c.g.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/coin_in_wallet.c.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/coin_in_wallet.c.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/coin_in_wallet.c.g.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view.c.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view_aggregation_item.c.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view_aggregation_item.c.g.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view_coin_data.c.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view_coin_data.c.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view_coin_data.c.g.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view_item.c.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view_item.c.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view_item.c.g.dart
Made a few fields nullable, so they can be parsed properly.
> fix: wallets parsing

- lib/app/features/gallery/views/components/albums/album_item.dart
> fix: improve tap area of album selection page item to work on a whole cell

- lib/app/features/auth/views/pages/recover_user_page/recover_user_page.dart
- lib/app/features/auth/views/pages/two_fa/twofa_input_step.dart
- lib/app/features/protect_account/authenticator/views/pages/setup_authenticator/authenticator_setup_code_confirm_page.dart
- packages/ion_identity_client/lib/src/auth/services/recover_user/data_sources/recover_user_data_source.dart
- packages/ion_identity_client/lib/src/auth/services/twofa/data_sources/twofa_data_source.dart
- packages/ion_identity_client/lib/src/auth/services/twofa/twofa_service.dart
- packages/ion_identity_client/lib/src/core/types/ion_exception.dart
This PR adds proper error handling to recover identity key page
https://github.com/user-attachments/assets/019942a3-d17f-4c49-894e-f755c028b367
> fix: add error handling to recover user page

- lib/app/features/settings/model/privacy_options.dart
- lib/app/features/settings/views/privacy_settings_modal.dart
- lib/app/features/user/model/user_metadata.c.dart
- lib/app/features/wallets/model/coin_in_wallet_data.c.dart
- lib/app/features/wallets/providers/current_user_wallet_views_provider.c.dart
This PR adds a logic for reading and settings privacy settings inside user settings modal.
> feat: add privacy settings logic

- lib/app/features/feed/stories/views/components/story_preview/media/story_image_preview.dart
- lib/app/services/media_service/image_proccessing_config.dart
> fix: story image preview aspect ratio and image processing quality

- ios/Podfile.lock
- packages/ion_identity_client/example/.gitignore
- packages/ion_identity_client/example/ios/Podfile.lock
- packages/ion_identity_client/example/ios/Runner.xcodeproj/project.pbxproj
- packages/ion_identity_client/example/ios/Runner.xcworkspace/contents.xcworkspacedata
- packages/ion_identity_client/example/lib/pages/user_wallet_views/providers/user_wallet_view_provider.dart
- packages/ion_identity_client/example/lib/pages/user_wallet_views/user_wallet_views_page.dart
- packages/ion_identity_client/example/lib/pages/user_wallets/user_wallets_page.dart
- packages/ion_identity_client/example/lib/providers/ion_identity_provider.c.dart
- packages/ion_identity_client/example/pubspec.lock
- packages/ion_identity_client/example/pubspec.yaml
- packages/ion_identity_client/lib/src/auth/dtos/credential_request_data.c.g.dart
- packages/ion_identity_client/lib/src/auth/services/twofa/models/init_twofa_request.c.g.dart
- packages/ion_identity_client/lib/src/signer/dtos/credential_assertion_data.c.g.dart
- packages/ion_identity_client/lib/src/wallets/services/broadcast_transaction/domain/transaction_creator/btc_transaction_creator.dart
- packages/ion_identity_client/lib/src/wallets/services/broadcast_transaction/domain/transaction_creator/transaction_creator_factory.dart
- packages/ion_identity_client/lib/src/wallets/services/broadcast_transaction/models/secure_payment_confirmation_request.c.g.dart
- packages/ion_identity_client/lib/src/wallets/services/generate_signature/models/generate_signature_request.c.g.dart
- packages/ion_identity_client/pubspec.yaml
- pubspec.lock
This PR adds PSBT transactions support to `ion_identity_client`.
- The main logic is in the `BtcTransactionCreator`
- I had to fork `bdk_flutter` to update `flutter_rust_bridge` to the latest version
> feature: add BTC Psbt

- lib/app/features/feed/create_post/providers/create_post_notifier.c.dart
Fix multiple attachments separator in post
> fix: attachments separator

- ios/Podfile.lock
- lib/app/components/text_span_builder/text_span_builder.dart
- lib/app/features/feed/create_article/providers/create_article_provider.c.dart
- lib/app/features/feed/data/models/entities/article_data.c.dart
- lib/app/features/feed/providers/article/cashtag_suggestions_provider.c.dart
- lib/app/features/feed/providers/article/suggestions_notifier_provider.c.dart
- lib/app/features/feed/views/components/text_editor/components/cashtags_suggestions.dart
- lib/app/features/feed/views/components/text_editor/utils/mentions_hashtags_handler.dart
- lib/app/features/feed/views/components/text_editor/utils/quill.dart
- lib/app/features/ion_connect/model/related_hashtag.c.dart
- lib/app/services/text_parser/model/text_matcher.dart
- lib/app/services/text_parser/text_parser.dart
- add handling of the `$` hashtag in the post entities
> feat: cashtag suggestions for text editor

- lib/app/features/feed/views/components/post/components/post_body/post_body.dart
- lib/app/features/feed/views/components/post/post.dart
- lib/app/features/feed/views/pages/post_details_page/post_details_page.dart
- lib/app/theme/text_selection_theme.dart
- lib/app/theme/theme.dart
> fix: add an option for text selection in the details post page

- ios/Podfile.lock
- lib/app/features/wallets/views/pages/wallet_page/components/coins/coins_tab.dart
- lib/app/features/wallets/views/pages/wallet_page/components/nfts/nfts_tab.dart
- lib/app/features/wallets/views/pages/wallet_page/components/nfts/nfts_tab_footer.dart
This PR fixes a small issue on Wallet page (NFT tab).
The fix is in the [nfts_tab_footer.dart](https://github.com/ice-blockchain/ion-app/pull/631/files#diff-d48e1cfaca0109d7e96f1ae99f1ea937d3921db43de387539899c227e00e73e0). Other changes are simple refactors.
> fix(wallets): add SizedBox as padding for NFTs

- lib/app/components/scroll_view/load_more_builder.dart
- lib/app/features/feed/providers/replies_provider.c.dart
- lib/app/features/feed/views/pages/post_details_page/components/reply_list/reply_list.dart
- lib/app/features/feed/views/pages/post_details_page/post_details_page.dart
> feat: add pagination to post details replies list

- lib/l10n/short_timeago_messages_adapter.dart
- lib/l10n/timeago_locales.dart
> fix: remove the tilde prefix, rename class

- lib/app/features/feed/data/models/bookmarks/bookmarks_set.c.dart
> fix: add distinction between post and article bookmarks inside BookmarksSetData

- lib/app/components/video_preview/video_preview.dart
> fix: display remaining video duration dynamically

- lib/app/components/scroll_view/load_more_builder.dart
- lib/app/features/feed/views/pages/post_details_page/components/reply_list/reply_list.dart
- lib/app/features/feed/views/pages/post_details_page/post_details_page.dart
> fix: replies list loading more

- lib/app/features/feed/views/components/post/post.dart
- lib/app/features/video/views/components/video_post_info.dart
> fix: use publishedAt for post entities timestamps

- lib/app/components/video_preview/video_preview.dart
- lib/app/features/core/providers/video_player_provider.c.dart
- the other videos should be paused when the specific video playback is on
> fix: only one video should play at a time

- lib/app/features/core/permissions/views/components/permission_dialogs/permission_request_sheet.dart
- lib/l10n/app_en.arb
> fix: make don't allow permission button outlined

- lib/app/features/wallets/model/network_type.dart
- lib/app/features/wallets/views/pages/coins_flow/coin_details/components/transaction_list_item/transaction_list_header_item.dart
- lib/l10n/app_en.arb
This PR updates "all chains" button: icon and text are replaced regarding desing
> fix(wallet): replace string and icon for all chains button

- lib/app/features/feed/views/pages/feed_page/components/feed_posts/feed_posts.dart
- lib/l10n/app_en.arb
> fix: add empty state for feed posts list

- lib/app/components/counter_items_footer/counter_items_footer.dart
- lib/app/features/components/entities_list/components/bookmark_button/bookmark_button.dart
> fix: bookmark button size and color on details pages

- ios/Podfile.lock
- lib/app/features/components/entities_list/entities_list.dart
- lib/app/features/feed/views/components/reply_list/reply_list.dart
- lib/app/features/feed/views/pages/articles_from_author_page/articles_from_author_page.dart
- lib/app/features/feed/views/pages/articles_from_topic_page/articles_from_topic_page.dart
> fix: correctly handle blocking hiding case for the same cell living across multiple pages

- lib/app/features/user/providers/followers_you_know_data_source_provider.c.dart
Adjust request to get followers you know
> fix: followers you know adjustment

- lib/app/features/auth/views/pages/recover_user_page/components/recovery_creds_step.dart
> fix: overflow issue from auth footer when keyboard is open on recover user page

- packages/ion_identity_client/lib/src/wallets/services/broadcast_transaction/domain/transaction_creator/transaction_creator_factory.dart
Adds EVM-compatible networks to create transactions
> feat: add EVM support networks for creating transactions

- packages/ion_identity_client/lib/src/core/types/ion_exception.dart
https://github.com/user-attachments/assets/f9693c2f-4d16-48e2-b1e9-30dd7644c9bd
> fix: wrong parsing error when handling invalid two fa exception

- lib/app/components/inputs/text_input/text_input.dart
- lib/app/features/auth/views/components/recovery_keys_input_container/recovery_keys_input_container.dart
- lib/app/features/protect_account/backup/views/components/recovery_key_input.dart
https://github.com/user-attachments/assets/a53dc8af-abbc-4c84-b404-493eb1c88a8f
> fix: form validation on setup recovery keys page

- lib/app/features/auth/views/pages/recover_user_page/components/recovery_creds_step.dart
This PR adds a similar form validation pattern to recovery keys setup page
> fix: recover user form validation

- lib/app/components/copy/copy_builder.dart
- lib/app/features/protect_account/backup/views/components/recovery_key_option.dart
- lib/app/features/protect_account/backup/views/pages/create_recover_key_page/components/create_recovery_key_success_state.dart
https://github.com/user-attachments/assets/fa17c610-1e1b-4b7f-b9e4-a59b377bd012
> feat: disable remaining recovery keys copy feature for 2 seconds after any of them is copied

- .tool-versions
- pubspec.lock
- pubspec.yaml
> chore: upgrade flutter to 3.27.4

- lib/app/features/chat/recent_chats/views/pages/recent_chats_empty_page/recent_chats_empty_page.dart
- lib/app/features/chat/recent_chats/views/pages/recent_chats_timeline_page/recent_chats_timeline_page.dart
- lib/app/features/user/pages/profile_page/components/tabs/tab_entities_list.dart
- lib/app/features/wallets/views/pages/wallet_page.dart
https://github.com/user-attachments/assets/4ab52d00-017c-4dcc-b2e3-fb8859118e90
> feat: add pull to refresh to main pages

- lib/app/features/ion_connect/providers/auth_challenge_provider.c.dart
- lib/app/features/ion_connect/providers/ion_connect_notifier.c.dart
- lib/app/features/ion_connect/providers/mixins/relay_auth_mixin.dart
- lib/app/features/ion_connect/providers/mixins/relay_delegation_mixin.dart
Sending auth challenge instead dummy auth event for reauth
AuthChallengeProvider now works per connection
> feat: change reauth flow

- packages/ion_identity_client/lib/src/core/types/ion_exception.dart
> fix: handle archived recovery keys error on recover user page

- ios/Podfile.lock
- lib/app/features/feed/create_post/providers/create_post_notifier.c.dart
- lib/app/features/feed/stories/views/pages/story_preview_page.dart
- lib/app/features/user/providers/image_proccessor_notifier.c.dart
- remove double compression
- proper image handling in the StoryPreviewPage
- add logs for QA
> fix: remove double compression

- lib/app/features/user/providers/follow_list_provider.c.dart
- lib/app/features/wallets/views/pages/wallet_page/components/balance/balance.dart
- lib/app/features/wallets/views/pages/wallet_page/components/coins/coins_tab.dart
- lib/app/features/wallets/views/pages/wallet_page/components/contacts/contacts_list.dart
https://github.com/user-attachments/assets/fd71df4a-5cb1-4e14-9fd9-9be89a7b30df
> fix: improve pull to refresh on wallet page

- lib/app/features/auth/views/pages/recover_user_page/components/recovery_creds_step.dart
- lib/app/features/auth/views/pages/two_fa/twofa_input_step.dart
- lib/app/features/auth/views/pages/two_fa/twofa_options_step.dart
> fix: paddings on recover user flow

- packages/ion_identity_client/lib/ion_identity.dart
- packages/ion_identity_client/lib/src/core/service_locator/ion_identity_clients/wallets_client_service_locator.dart
- packages/ion_identity_client/lib/src/wallets/ion_identity_wallets.dart
- packages/ion_identity_client/lib/src/wallets/models/wallet.c.dart
- packages/ion_identity_client/lib/src/wallets/models/wallet.c.freezed.dart
- packages/ion_identity_client/lib/src/wallets/models/wallet.c.g.dart
- packages/ion_identity_client/lib/src/wallets/services/make_transfer/data_sources/make_transfer_data_source.dart
- packages/ion_identity_client/lib/src/wallets/services/make_transfer/make_transfer_service.dart
- packages/ion_identity_client/lib/src/wallets/services/make_transfer/models/transfer.c.dart
- packages/ion_identity_client/lib/src/wallets/services/make_transfer/models/transfer.c.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/make_transfer/models/transfer.c.g.dart
This PR implements Transfer request to make it possible implement Transfer from wallets
> feat(ion-identity-client): add Transfer request

- lib/app/features/chat/community/channel/views/pages/channel_page/channel_messaging_page.dart
- lib/app/features/chat/e2ee/providers/e2ee_messages_subscriber.c.dart
- lib/app/features/chat/e2ee/providers/send_e2ee_message_provider.c.dart
- lib/app/features/chat/e2ee/views/components/one_to_one_messages_list.dart
- lib/app/features/chat/e2ee/views/pages/group_mesages_page.dart
- lib/app/features/chat/e2ee/views/pages/one_to_one_messages_page.dart
- lib/app/features/chat/model/database/dao/conversation_message_status_dao.c.dart
- lib/app/features/chat/model/message_delivery_status.dart
- lib/app/features/chat/providers/conversation_messages_provider.c.dart
- lib/app/features/chat/views/components/message_items/message_metadata/message_metadata.dart
- pubspec.lock
> feat: read message status

- .github/workflows/CICD.yaml
- lib/app/features/feed/stories/views/pages/story_preview_page.dart
Updates GitHub Actions workflow to use macos-15 runner and updates various pod dependencies. We need to upgrade it because latest banuba sdk use swift 6.
- Share story button should work with video media type too
> fix: macos-15 on CI/CD

- lib/app/features/feed/providers/can_reply_notifier.c.dart
- lib/app/features/ion_connect/providers/ion_connect_entity_provider.c.dart
- lib/app/features/user/providers/follow_list_provider.c.dart
> fix: feed refresh loop

- lib/app/features/feed/create_post/views/pages/create_post_modal/components/create_post_content.dart
- lib/app/features/feed/create_post/views/pages/create_post_modal/hooks/use_url_links.dart
- show a preview on youtube-link for creating post
- add URL link extraction hook
> fix: show a preview on youtube-link for creating post

- lib/app/features/wallets/views/components/coins_list/coins_list_view.dart
Added an EmptyState for coins search in wallet
> fix: add EmptyState for coins search

- lib/app/components/button/button.dart
- lib/app/components/button/variants/button_dropdown.dart
- lib/app/features/auth/views/pages/recover_user_twofa_page/components/twofa_option_selector.dart
- lib/app/features/auth/views/pages/recover_user_twofa_page/components/twofa_options_selector_button.dart
- lib/app/features/auth/views/pages/two_fa/twofa_options_step.dart
- lib/app/features/protect_account/components/twofa_select_options_step.dart
- lib/app/features/protect_account/secure_account/providers/selected_two_fa_types_provider.c.dart
https://github.com/user-attachments/assets/e8ccc9bb-69a8-48a8-87f1-1b437c360f0d
> feat: add clear option to 2fa selectors

- lib/app/features/feed/stories/views/components/story_viewer/components/core/story_content.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/core/story_input_field.dart
> feat: add story reply functionality with E2EE messaging

- lib/app/features/wallets/views/pages/manage_coins/manage_coins_page.dart
Add saving of the state, when the page is disposed.
> fix: issue with unsaved changes

- ios/Podfile.lock
- lib/app/features/chat/e2ee/providers/send_e2ee_message_provider.c.dart
- lib/app/features/core/providers/feature_flags_provider.c.dart
- lib/app/features/ion_connect/providers/ion_connect_notifier.c.dart
- lib/app/features/ion_connect/providers/ion_connect_upload_notifier.c.dart
> fix: upload e2e files in anonymous connection

- lib/app/components/separated/separator.dart
- lib/app/features/chat/views/pages/chat_main_modal/chat_main_modal_page.dart
- lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart
- lib/app/features/wallets/views/pages/wallet_main_modal/wallet_main_modal_page.dart
- lib/app/router/components/sheet_content/main_modal_item.dart
This PR  improves modal layouts for main modal sheet.
N/A
checked with a pixel perfect tool
https://github.com/user-attachments/assets/32887719-1a43-493e-ac0d-76813f8e688e
> fix: sync padding of main modal sheets

- lib/app/features/wallets/hooks/use_load_wallet_to_receive_coins.dart
- lib/app/features/wallets/model/network.dart
- lib/app/features/wallets/views/pages/coins_flow/coin_details/components/balance/balance.dart
- lib/app/features/wallets/views/pages/coins_flow/coin_receive_modal/coin_receive_modal.dart
- lib/app/features/wallets/views/pages/coins_flow/coin_receive_modal/components/coin_address_tile/coin_address_tile.dart
- lib/app/features/wallets/views/pages/coins_flow/receive_coins/components/share_address_view.dart
- lib/app/features/wallets/views/pages/coins_flow/receive_coins/providers/receive_coins_form_provider.c.dart
Fix the send/receive buttons on the Coin Details page.
> fix: send/receive buttons on the coin details page

- lib/app/features/components/entities_list/entities_list.dart
- lib/app/features/feed/views/components/overlay_menu/user_info_menu.dart
- lib/app/features/feed/views/components/post/post.dart
- lib/app/features/feed/views/pages/feed_page/components/stories/components/story_list_item.dart
- lib/app/features/feed/views/pages/feed_page/components/trending_videos/components/trending_video_author.dart
- lib/app/features/feed/views/pages/who_can_reply_info_modal/who_can_reply_info_modal.dart
- lib/app/features/ion_connect/providers/ion_connect_entity_provider.c.dart
- lib/app/features/user/pages/profile_page/components/profile_details/followers_you_know/followed_by_avatars.dart
- lib/app/features/user/pages/profile_page/components/profile_details/followers_you_know/followed_by_text.dart
- lib/app/features/user/providers/user_metadata_provider.c.dart
https://github.com/user-attachments/assets/0c1b4e58-afb7-41ff-944b-cc8293ba1c6b
> feat: add sync entity providers, use sync entity providers for feed cells, fix feed scrolling jumps

- lib/app/features/components/entities_list/entities_list.dart
- lib/app/features/feed/views/components/article/article.dart
- lib/app/features/feed/views/components/overlay_menu/user_info_menu.dart
- lib/app/features/feed/views/components/post/post.dart
- lib/app/features/feed/views/pages/feed_page/components/feed_posts/feed_posts.dart
- lib/app/features/user/pages/profile_page/components/header/context_menu.dart
- lib/app/features/user/pages/profile_page/components/tabs/tab_entities_list.dart
- lib/app/features/user/pages/profile_page/pages/components/block_user_button.dart
- lib/app/features/user/providers/block_list_notifier.c.dart
> refactor: make block list listeners on feed cells sync

- lib/app/features/auth/views/components/user_data_inputs/name_input.dart
- lib/app/features/auth/views/components/user_data_inputs/nickname_input.dart
- lib/app/features/feed/views/components/user_info/user_info.dart
- lib/l10n/app_en.arb
https://github.com/user-attachments/assets/8cf91103-7503-4696-aca1-443f3b2783b9
> feat: add name and nickname max length validation

- lib/app/features/components/entities_list/components/repost_list_item.dart
- lib/app/features/components/entities_list/entities_list.dart
- lib/app/features/feed/create_post/views/pages/create_post_modal/components/quoted_entity.dart
- lib/app/features/feed/views/components/article/article.dart
- lib/app/features/feed/views/components/post/post.dart
- lib/app/features/ion_connect/providers/ion_connect_entity_provider.c.dart
- lib/app/features/user/providers/block_list_notifier.c.dart
- lib/app/features/user/providers/user_metadata_provider.c.dart
> fix: make ion connect providers properly async, fix repost/quote child not loading

- lib/app/features/ion_connect/providers/ion_connect_entity_provider.c.dart
> fix: ion connect entity provider loop

- lib/app/features/chat/model/database/chat_database.c.dart
- lib/app/features/chat/providers/conversation_messages_provider.c.dart
- lib/app/features/chat/providers/user_chat_relays_provider.c.dart
- lib/app/features/ion_connect/providers/ion_connect_notifier.c.dart
- Close DB on logout
- Fix circular dependency issue
> bugfix: close db on logout

- lib/app/components/text_editor/text_editor_preview.dart
> fix: post edit reactivity

- lib/app/features/components/entities_list/components/repost_list_item.dart
https://github.com/user-attachments/assets/9b61da5a-028b-447b-953c-def7a05b5d44
> fix: posts and articles reposts/quotes paddings

- lib/app/features/auth/views/components/user_data_inputs/nickname_input.dart
> feat: change nickname length limit to 20

- lib/app/components/inputs/text_input/text_input.dart
- lib/app/utils/validators.dart
> feat: add new display name validation allowing special characters

- ios/Podfile.lock
- lib/app/features/core/permissions/views/components/permission_aware_widget.dart
- lib/app/features/feed/views/pages/feed_page/components/stories/components/current_user_story_list_item.dart
- lib/app/features/wallets/views/components/qr_scanner_bottom_sheet.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/contact_input_switcher.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart
- lib/app/features/wallets/views/pages/send_nft_form.dart
- lib/l10n/app_en.arb
- pubspec.lock
- pubspec.yaml
- fix subscription memory leak
- add popping scanned result
- fix autoredirect to record story route
> fix(qr scanner)

- lib/app/features/core/model/feature_flags.dart
- lib/app/features/core/providers/feature_flags_provider.c.dart
- lib/app/features/wallets/views/pages/wallet_page/components/header/header.dart
- lib/app/features/wallets/views/pages/wallet_page/components/tabs/tabs_header.dart
Added a new FF for dapps with default false value.
> chore(wallet): add dapps feature flag

- lib/app/features/chat/e2ee/model/entites/private_direct_message_data.c.dart
- lib/app/features/chat/e2ee/providers/send_e2ee_message_provider.c.dart
- lib/app/features/chat/e2ee/views/components/one_to_one_messages_list.dart
- lib/app/features/chat/model/message_type.dart
- lib/app/features/chat/recent_chats/views/components/recent_chat_tile/recent_chat_tile.dart
- lib/app/features/chat/views/components/message_items/message_types/audio_message/audio_message.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/action_button.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/recording_overlay.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar_recording.dart
- lib/app/features/ion_connect/model/entity_data_with_media_content.dart
- lib/app/services/audio_wave_playback_service/audio_wave_playback_service.c.dart
- lib/app/services/compressor/compress_service.c.dart
Adds voice message support in chat.
N/A
https://github.com/user-attachments/assets/513694dd-6411-44b3-8953-fff70e54e39b
> feat: chat voice message integration

- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_item.dart
- lib/app/features/feed/views/pages/fullscreen_media/fullscreen_media_page.dart
- lib/app/router/feed_routes.dart
Fix Hero animation between routes
> fix: hero animation between routes

- ios/Podfile.lock
- lib/app/components/sensors/device_rotation_detector.dart
- lib/app/features/debug/views/debug_page.dart
- lib/app/features/debug/views/debug_rotate_gesture.dart
- lib/app/router/components/app_router_builder.dart
- lib/app/router/main_tabs/main_tab_navigation.dart
- pubspec.lock
- pubspec.yaml
Show debug menu when device is up side down and holds 1 second
> feat: show debug menu when device is up side down

- lib/app/features/feed/stories/views/components/story_viewer/components/core/story_content.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/header/header_actions.dart
- hide a context menu for own stories
- prevent story input for own stories
> fix: own stories issues

- lib/app/features/feed/stories/views/components/story_viewer/components/core/story_content.dart
> feat: add fade and slide animations to the story viewer header and footer

- lib/app/features/feed/stories/views/components/story_viewer/components/core/story_input_field.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/core/story_viewer_action_buttons.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/header/header_actions.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/header/story_context_menu.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/header/story_viewer_header.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/progress/story_progress_fill.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/reactions/story_reaction_notification.dart
This PR implements additional performance improvements to the Stories feature, focusing on optimizing the progress indicator rendering with CustomPainter and reducing theme context lookups:
- **Replaced AnimatedContainer with CustomPainter** in `StoryProgressFill` to reduce layout calculations and repaints
-  minimize theme lookups in hot paths
Profiling shows dramatic performance improvements:
- **StoryProgressFill CPU consumption**: 45.20% → 22.97% (~50% reduction)
- **ThemeGetter CPU consumption**: 34.46% → 18.73% (~46% reduction)
- **Animation and rendering operations**: More efficient with better layering
- **Overall CPU profile**: More balanced without extreme hotspots
**Before:**
**After:**
> fix: stories viewing performance

- lib/app/features/wallets/data/database/dao/coins_dao.c.dart
- lib/app/features/wallets/domain/coins/search_coins_service.c.dart
Moved sorting to the data layer and changed it a bit.
> chore: improve coins sorting during search

- lib/app/features/chat/e2ee/providers/send_e2ee_message_provider.c.dart
- lib/app/features/chat/e2ee/views/pages/group_mesages_page.dart
- lib/app/features/chat/recent_chats/views/pages/recent_chats_timeline_page/recent_chats_timeline_page.dart
- lib/app/features/chat/views/components/message_items/message_types/audio_message/audio_message.dart
- lib/app/features/chat/views/components/message_items/message_types/profile_share_message/profile_share_message.dart
- lib/app/features/chat/views/components/message_items/message_types/video_message/video_message.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/more_content_view.dart
- lib/app/services/media_service/media_encryption_service.c.dart
- lib/l10n/app_en.arb
- Fix bug for profile message wrapped
- Improve media types upload by adding event with dummy metadata (needed for resend media types)
> refactor:  insert dummy e2e event before media upload

- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar_recording.dart
This PR addresses the poor audio quality issue in voice recordings by setting a specific bitrate.
https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues/287
N/A
> fix: set  audio recording bitrate for improved voice quality

- ios/Runner/Info.plist
- lib/app/components/text_editor/text_editor_preview.dart
- lib/app/features/core/permissions/views/components/permission_dialogs/permission_request_sheet.dart
- lib/app/features/feed/stories/providers/story_pause_provider.c.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/core/story_content.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/header/story_context_menu.dart
- lib/l10n/app_en.arb
- fix: updates `StoryContent` to conditionally show/hide elements based on both pause and menu open states
- fix: update photo library permission request and localization
- fix: the selection toolbar
> fix: ui issues

- ios/Podfile.lock
- lib/app/features/chat/e2ee/providers/send_e2ee_message_provider.c.dart
- lib/app/features/chat/views/components/message_items/message_item_wrapper/message_item_wrapper.dart
- lib/app/features/chat/views/components/message_items/message_reaction_dialog/components/message_reaction_context_menu.dart
- lib/app/features/chat/views/components/message_items/message_types/money_message/money_message.dart
- lib/app/features/chat/views/components/message_items/message_types/photo_message/photo_message.dart
- lib/app/features/chat/views/components/message_items/message_types/poll_message/poll_message.dart
- lib/app/features/chat/views/components/message_items/message_types/poll_message/poll_result_message.dart
- lib/app/features/chat/views/components/message_items/message_types/url_preview_message/url_preview_message.dart
- lib/app/features/chat/views/components/message_items/message_types/video_message/video_message.dart
- Resend failed message with media
- Renew failed media upload
> feat: Resend message with media attachment

- lib/app/features/auth/views/pages/discover_creators/discover_creators.dart
- lib/app/features/chat/community/providers/community_join_requests_provider.c.dart
- lib/app/features/chat/community/providers/community_messages_subscriber_provider.c.dart
- lib/app/features/chat/views/components/message_items/message_reaction_dialog/components/message_reaction_context_menu.dart
- lib/app/features/chat/views/components/message_items/message_reaction_dialog/message_reaction_dialog.dart
- lib/app/features/chat/views/pages/chat_main_modal/chat_main_modal_page.dart
- lib/app/features/chat/views/pages/new_chat_modal/new_chat_modal.dart
- lib/app/features/core/model/feature_flags.dart
- lib/app/features/core/providers/feature_flags_provider.c.dart
- lib/app/features/search/views/pages/chat_advanced_search_page/chat_advanced_search_page.dart
- lib/app/features/search/views/pages/chat_simple_search_page/chat_simple_search_page.dart
This PR adds feature flag to control chat bookmark visibility in message context menu
N/A
> feat: add chat bookmark feature flag

- assets/svg/icon_profile_camera.svg
- lib/app/exceptions/exceptions.dart
- lib/app/features/chat/e2ee/model/entities/private_direct_message_data.c.dart
- lib/app/features/chat/e2ee/providers/send_e2ee_message_provider.c.dart
- lib/app/features/chat/e2ee/views/components/one_to_one_messages_list.dart
- lib/app/features/chat/e2ee/views/pages/group_mesages_page.dart
- lib/app/features/chat/model/message_type.dart
- lib/app/features/chat/recent_chats/views/components/recent_chat_tile/recent_chat_tile.dart
- lib/app/features/chat/recent_chats/views/pages/recent_chats_timeline_page/recent_chats_timeline_page.dart
- lib/app/features/chat/views/components/message_items/message_item_wrapper/message_item_wrapper.dart
- lib/app/features/chat/views/components/message_items/message_types/audio_message/audio_message.dart
- lib/app/features/chat/views/components/message_items/message_types/document_message/document_message.dart
- lib/app/features/chat/views/components/message_items/message_types/photo_message/photo_message.dart
- lib/app/features/chat/views/components/message_items/message_types/text_message/text_message.dart
- lib/app/features/chat/views/components/message_items/message_types/video_message/video_message.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/more_content_view.dart
- lib/app/features/core/views/photo_gallery_page/components/components.dart
- lib/app/features/core/views/photo_gallery_page/components/photo_gallery_carousel.dart
- lib/app/features/ion_connect/model/entity_data_with_media_content.dart
- lib/app/features/ion_connect/model/media_attachment.dart
- lib/app/services/compressor/compress_service.c.dart
- lib/app/services/media_service/media_encryption_service.c.dart
- pubspec.lock
- pubspec.yaml
This PR implements visual media (images and videos) while adding support for video thumbnails.
- Consolidated media types by replacing the separate video type with a unified visualMedia type
- Added automatic thumbnail generation and encryption for video messages
- Enhanced the media encryption pipeline to handle multiple files and thumbnails
- Updated UI components to reflect the new media handling system
- [flutter_staggered_grid_view](https://pub.dev/packages/flutter_staggered_grid_view) package has been added for flexible grid layout.
https://github.com/user-attachments/assets/b3f01525-a354-4020-bfd5-817dadfbafe4
> feat(chat): photo message implementation & generate thumbnail for video message

- lib/app/exceptions/exceptions.dart
- lib/app/features/ion_connect/providers/ion_connect_upload_notifier.c.dart
- lib/app/services/compressor/compress_service.c.dart
- lib/app/services/media_service/aspect_ratio.dart
Fix dimension for upload video
> fix: video dimensions

- lib/app/components/avatar/avatar.dart
- lib/app/components/coins/coin_icon.dart
- lib/app/components/image/app_cached_network_image.dart
- lib/app/components/image/ion_network_image.dart
- lib/app/features/chat/views/components/message_items/message_types/url_preview_message/components/meta_data_preview.dart
- lib/app/features/chat/views/components/message_items/message_types/url_preview_message/url_preview_message.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/viewers/image_story_viewer.dart
- lib/app/features/feed/views/components/article/components/article_image/article_image.dart
- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_item.dart
- lib/app/features/feed/views/components/url_preview_content/components/url_metadata_preview.dart
- lib/app/features/feed/views/components/url_preview_content/url_preview_content.dart
- lib/app/features/feed/views/pages/article_details_page/components/articles_carousel_item.dart
- lib/app/features/feed/views/pages/fullscreen_media/components/fullscreen_image.dart
- lib/app/features/user/pages/components/user_banner/user_banner.dart
- lib/app/features/wallets/views/components/network_icon_widget.dart
- lib/app/features/wallets/views/components/nft_item.dart
- lib/app/features/wallets/views/components/nft_picture.dart
- lib/app/features/wallets/views/pages/wallet_page/components/nfts/nft_grid_item.dart
- pubspec.lock
- pubspec.yaml
- Disable fade in animation for cached network image
- Bump package version
> fix: cached network image 

- lib/app/features/auth/providers/onboarding_complete_notifier.c.dart
> feat: populate wallets inside user metadata during onboarding

- lib/app/features/chat/model/database/dao/conversation_message_dao.c.dart
- lib/app/features/chat/providers/conversation_messages_provider.c.dart
- pubspec.lock
- pubspec.yaml
> fix: dates for deleted message

- lib/app/features/protect_account/phone/views/components/phone/phone_input_step.dart
- lib/app/features/protect_account/phone/views/pages/edit_phone/components/phone_edit_new_phone_input_step.dart
> fix: bottom button padding on phone input step

- lib/app/features/ion_connect/providers/ion_connect_notifier.c.dart
- lib/app/utils/retry.dart
> fix: retry counter reset

- lib/l10n/app_en.arb
> fix: cloud backup warning label text

- ios/Podfile.lock
- lib/app/features/chat/e2ee/providers/send_e2ee_message_provider.c.dart
- lib/app/features/core/views/pages/search_emoji_modal/components/emojis_grid_view.dart
- Resend multiple media
- Emoji search UI fix
> bugfix: Resend multiple attachments

- lib/app/features/feed/create_post/views/pages/create_post_modal/components/parent_entity.dart
- lib/app/features/feed/views/components/article/article.dart
- lib/app/features/feed/views/components/post/post.dart
- lib/app/features/user/pages/profile_page/components/tabs/tab_entities_list.dart
> feat: add new reply cell ui

- lib/app/features/chat/e2ee/views/pages/one_to_one_messages_page.dart
- lib/app/features/chat/model/database/dao/conversation_dao.c.dart
- lib/app/features/chat/recent_chats/providers/toggle_archive_conversation_provider.c.dart
- lib/app/features/chat/recent_chats/views/components/conversation_edit_bottom_bar/components/conversation_archive_button/conversation_archive_button.dart
- lib/app/features/chat/recent_chats/views/components/conversation_edit_bottom_bar/components/conversation_archive_button/conversation_unarchive_button.dart
- lib/app/features/chat/recent_chats/views/pages/recent_chat_overlay/components/recent_chat_overlay_context_menu.dart
- lib/app/features/feed/views/pages/feed_page/components/stories/components/current_user_avatar_with_permission.dart
- lib/app/features/feed/views/pages/feed_page/components/stories/components/plus_button_with_permission.dart
- lib/app/router/chat_routes.dart
- pubspec.lock
- pubspec.yaml
- Refactor toggle archive provider
- Fix archive all conversations
> fix: multiple conversations archiving

- lib/app/components/video_preview/video_preview.dart
> fix: remove local state for mute status

- lib/app/features/feed/create_post/views/pages/create_post_modal/components/parent_entity.dart
- lib/app/features/feed/views/components/post/components/post_body/components/post_media/post_media.dart
- lib/app/features/feed/views/components/post/components/post_body/post_body.dart
> fix: reply modal parent body padding

- lib/app/features/components/entities_list/components/repost_list_item.dart
> fix: reposted article paddings

- build.yaml
- lib/app/features/feed/views/components/article/article.dart
- lib/app/router/base_route_data.dart
- lib/app/router/main_tabs/main_tab_navigation.dart
- Navigation history between tabs;
- Removed extra bookmark button for the article (now there is one from the footer);
https://github.com/user-attachments/assets/23011ea5-574c-4a75-95e5-f01cca30b943
> feat: tabs navigation history

- lib/app/features/feed/stories/views/pages/story_preview_page.dart
- fixed image path from the Banuba in StoryPreviewPage
> fix: image path during upload story image

- lib/app/features/core/providers/video_player_provider.c.dart
- lib/app/features/video/views/pages/video_page.dart
- update video player volume handling based on mute state
- fixed a mute state on trending videos
> fix: mute state in trending videos

- lib/app/features/user/providers/update_user_metadata_notifier.c.dart
- lib/app/features/wallets/domain/coins/coins_service.c.dart
- lib/app/features/wallets/domain/wallet_views/wallet_views_service.c.dart
- lib/app/features/wallets/model/transfer_result.c.dart
- lib/app/features/wallets/model/wallet_view_data.c.dart
- lib/app/features/wallets/providers/mock_data/mock_data.dart
- lib/app/features/wallets/providers/send_coins_notifier_provider.c.dart
- lib/app/features/wallets/providers/transactions_history_notifier_provider.c.dart
- packages/ion_identity_client/lib/src/wallets/ion_identity_wallets.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/data_sources/get_wallet_transfer_requests_data_source.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/get_wallet_transfer_requests_service.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/transfer_request_body.c.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/transfer_request_body.c.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/transfer_request_body.c.g.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/wallet_transfer_request.c.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/wallet_transfer_request.c.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/wallet_transfer_request.c.g.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view.c.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view.c.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view.c.g.dart
1. Update main wallet view determining;
2. Fix authors field in the `RequestFilter` according to [this](https://github.com/ice-blockchain/ion-app/pull/854#discussion_r2004973058) comment;
3. Fix a few parcing issues for `WalletTransferRequest`;
4. Get with retry transfer data if the received after transaction doesn't contain `txHash`.
5. Add get transfer by `id` request.
> fix: wallet errors

- lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart
https://github.com/user-attachments/assets/f8c18b20-5677-4f96-b6be-6bbbb1763530
> fix: scroll to top not working on feed tab tap after opening post create modal

- lib/app/features/ion_connect/providers/ion_connect_notifier.c.dart
Add timeout exception for `IonConnectNotifier`
> feat: IonConnectNotifier timeout

- ios/Podfile.lock
- lib/app/features/feed/stories/views/components/story_viewer/components/core/story_content.dart
- lib/app/features/feed/views/pages/feed_page/components/stories/components/current_user_story_list_item.dart
- lib/app/features/feed/views/pages/feed_page/components/stories/components/plus_button_with_permission.dart
- Removed gradient from current user avatar when no stories exist
- Fixed showing of the story input field with keyboard state
> fix: improve stories UI with gradient and keyboard handling

- lib/app/components/text_editor/hooks/use_text_editor_character_limit_exceed_amount.dart
- lib/app/features/chat/views/pages/chat_add_poll_modal/chat_add_poll_modal.dart
- lib/app/features/feed/create_post/views/components/character_limit_exceed_indicator/character_limit_exceed_indicator.dart
- lib/app/features/feed/create_post/views/components/post_submit_button/post_submit_button.dart
- lib/app/features/feed/create_post/views/components/reply_input_field/reply_input_field.dart
- lib/app/features/feed/create_post/views/pages/create_post_modal/components/create_post_bottom_panel.dart
- lib/app/features/feed/data/models/entities/modifiable_post_data.c.dart
- lib/app/utils/validators.dart
https://github.com/user-attachments/assets/49497400-d8d9-4b94-9a5b-5acffdb7ef9e
> feat: add character limit to post creator and replies

- lib/app/features/user/pages/profile_page/pages/send_coins_form_modal/send_coin_form_modal.dart
- lib/app/features/wallets/domain/nfts/send_nft_use_case.c.dart
- lib/app/features/wallets/model/send_nft_form_data.c.dart
- lib/app/features/wallets/providers/network_fee_provider.c.dart
- lib/app/features/wallets/providers/send_asset_form_provider.c.dart
- lib/app/features/wallets/providers/send_coins_notifier_provider.c.dart
- lib/app/features/wallets/providers/send_nft_form_provider.c.dart
- lib/app/features/wallets/providers/send_nft_notifier_provider.c.dart
- lib/app/features/wallets/views/components/arrival_time/network_fee_selector.dart
- lib/app/features/wallets/views/pages/coins_flow/coin_details/components/balance/balance.dart
- lib/app/features/wallets/views/pages/coins_flow/network_list/network_list_view.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/coins_network_fee_selector.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/confirmation/confirmation_sheet.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/confirmation/transaction_result_sheet.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/send_coin_modal_page.dart
- lib/app/features/wallets/views/pages/contact_modal_page/contact_modal_page.dart
- lib/app/features/wallets/views/pages/nft_details/components/nft_details.dart
- lib/app/features/wallets/views/pages/send_nft/components/nft_network_fee_selector.dart
- lib/app/features/wallets/views/pages/send_nft_confirm.dart
- lib/app/features/wallets/views/pages/send_nft_form.dart
- lib/app/features/wallets/views/pages/transaction_details/transaction_details.dart
- lib/app/features/wallets/views/pages/wallet_main_modal/wallet_main_modal_page.dart
- lib/app/features/wallets/views/pages/wallet_page/components/balance/balance.dart
- lib/app/features/wallets/views/pages/wallet_page/components/header/header.dart
- lib/app/router/app_routes.c.dart
- lib/app/router/wallet_routes.dart
This PR adds Network Fee support for Send NFT form.
> feat(wallet): add NetworkFee support for SendNft

- lib/app/features/chat/views/components/message_items/message_types/text_message/text_message.dart
This PR improves the text message layout by dynamically positioning metadata based on message length.
N/A
> bugfix(chat): dynamic metadata positioning for text messages

- lib/app/components/text_editor/hooks/use_text_editor_character_limit_exceed_amount.dart
> fix: adjust for quills documents initial length for post character limit

- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/more_content_view.dart
- lib/app/features/gallery/providers/media_selection_provider.c.dart
- lib/app/features/gallery/views/components/gallery_grid_cell.dart
- lib/app/router/feed_routes.dart
https://github.com/user-attachments/assets/833c7f71-61aa-49f0-a978-b92933e7f2b3
> feat: increase image limit in post to 10, add opacity to picker images when limit is reached

- lib/app/features/components/entities_list/components/repost_author_header.dart
> fix: increase repost header max lines to 2

- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/more_content_view.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar_initial.dart
Updates camera button interactions to correctly navigate to the media gallery screen, removing direct camera access to align with the intended user flow for media selection.
N/A
N/A
> fix: correct navigation flow from camera buttons to media gallery screen

- lib/app/components/text_editor/components/gallery_permission_button.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/more_content_view.dart
- lib/app/features/feed/create_post/views/components/reply_input_field/reply_input_field.dart
- lib/app/features/feed/create_post/views/pages/create_post_modal/components/create_post_bottom_panel.dart
- lib/app/features/feed/data/models/entities/modifiable_post_data.c.dart
- lib/app/features/feed/views/components/toolbar_buttons/toolbar_image_button.dart
- lib/app/features/gallery/providers/media_selection_provider.c.dart
- lib/app/router/feed_routes.dart
> chore: move post max media limit to const

- lib/app/features/feed/providers/replies_provider.c.dart
- lib/app/features/ion_connect/providers/entities_paged_data_provider.c.dart
> fix: update pagedDataProvider state to avoid new reply disappearing on loadMore in post details page

- android/app/build.gradle
- ios/Podfile.lock
- lib/app/features/chat/views/components/message_items/message_types/audio_message/components/play_pause_button.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/pause_audio_button.dart
- lib/app/features/gallery/providers/camera_provider.c.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
- eliminate double camera initialization on permissions grant
> fix: double camera on first launch

- lib/app/components/overlay_menu/hooks/use_hide_on_scroll.dart
- lib/app/components/overlay_menu/overlay_menu.dart
- lib/app/features/feed/views/pages/feed_page/components/feed_controls/components/feed_filters/feed_filters_menu_button.dart
- lib/app/features/feed/views/pages/feed_page/components/feed_controls/components/feed_filters/feed_filters_menu_overlay.dart
- lib/app/features/feed/views/pages/feed_page/components/feed_controls/components/feed_navigation/feed_navigation.dart
- lib/app/features/feed/views/pages/feed_page/components/feed_controls/feed_controls.dart
- lib/app/features/feed/views/pages/feed_page/feed_page.dart
> fix: feed category select popup not hiding on scroll

- lib/app/features/chat/e2ee/model/entities/private_direct_message_data.c.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/more_content_view.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar_initial.dart
- lib/app/features/chat/views/pages/upload_limit_reached_modal/upload_limit_reached_modal.dart
- lib/app/features/gallery/data/models/media_selection_state.c.dart
- lib/app/features/gallery/providers/media_selection_provider.c.dart
- lib/app/features/gallery/views/components/gallery_grid_cell.dart
- lib/app/features/gallery/views/pages/media_picker_page.dart
- lib/app/router/feed_routes.dart
- lib/l10n/app_en.arb
This PR implements a video duration limit feature for chat messages. 
N/A
https://github.com/user-attachments/assets/ef5ad137-fc55-48d0-8aa9-507ca368eb6a
> feat(chat): add video duration check and warning modal for long videos

- lib/app/features/feed/stories/views/components/story_capture/camera/custom_camera_preview.dart
https://github.com/user-attachments/assets/293a5fde-136a-4ecd-8091-9e2de0535e6e
> feat: add camera focus on tap in camera preview

- lib/app/features/feed/create_post/providers/create_post_notifier.c.dart
- lib/app/features/feed/providers/feed_posts_provider.c.dart
> fix: keep correct image order on post create with multiple media

- lib/app/features/feed/create_article/views/pages/select_artcile_topics_modal/select_artcile_topics_modal.dart
- lib/app/features/user/pages/profile_edit_page/pages/category_select_modal/category_select_modal.dart
- lib/app/features/user/pages/profile_page/pages/account_notifications_modal/account_notifications_modal.dart
Replace [MenuItemButton](https://api.flutter.dev/flutter/material/MenuItemButton-class.html) with ListItem in non-menu contexts for better UI consistency.
> bugfix: topics/category/notification selection modals ui consistency

- lib/app/exceptions/exceptions.dart
- lib/app/features/feed/create_post/providers/create_post_notifier.c.dart
- lib/app/features/feed/data/models/entities/article_data.c.dart
- lib/app/features/feed/providers/delete_entity_provider.c.dart
- lib/app/features/ion_connect/providers/ion_connect_delete_file_notifier.c.dart
- lib/app/features/ion_connect/providers/ion_connect_upload_notifier.c.dart
- lib/app/features/ion_connect/utils/file_storage_utils.dart
> feat: add logic for media files delete on entity delete

- ios/Podfile.lock
- lib/app/components/text_editor/components/gallery_permission_button.dart
- lib/app/features/feed/create_post/views/pages/post_form_modal/components/create_post_bottom_panel.dart
- lib/app/features/feed/views/components/toolbar_buttons/toolbar_image_button.dart
- lib/app/features/feed/views/components/toolbar_buttons/toolbar_poll_button.dart
- lib/app/features/feed/views/pages/fullscreen_media/components/fullscreen_image.dart
- lib/app/features/feed/views/pages/fullscreen_media/components/image_carousel.dart
- lib/app/features/feed/views/pages/fullscreen_media/components/single_media_view.dart
- lib/app/features/feed/views/pages/fullscreen_media/providers/image_zoom_state.c.dart
- lib/app/router/components/modal_wrapper/dismissible_content.dart
- pubspec.lock
- pubspec.yaml
- Image addition and poll buttons are disabled when creating a video post
- Added extended image scaling capabilities by replacing `InteractiveViewer` with `PhotoView` component
> fix: feed media

- lib/app/features/feed/create_article/views/pages/create_article_modal/components/article_main_toolbar.dart
- lib/app/features/feed/create_post/views/components/reply_input_field/reply_input_field.dart
- lib/app/features/feed/create_post/views/pages/post_form_modal/components/create_post_bottom_panel.dart
- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_carousel_horizontal.dart
- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_carousel_vertical.dart
- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_item.dart
- lib/app/features/feed/views/components/toolbar_buttons/toolbar_image_button.dart
Add video to regular post creation flow 
Align videoIndex for swiping videos
> feat: add video to post create

- lib/app/features/gallery/providers/gallery_provider.c.dart
- lib/app/features/gallery/views/components/manage_access_banner.dart
- lib/app/features/gallery/views/components/media/add_media_cell.dart
- lib/app/features/gallery/views/pages/media_picker_page.dart
- lib/app/services/media_service/media_service.c.dart
https://github.com/user-attachments/assets/ca774ca4-3b10-457a-83ac-b91055ed57fc
> fix: add watch for gallery media to handle limited gallery permission

- lib/app/features/feed/views/pages/fullscreen_media/fullscreen_media_page.dart
> fix: remove post media options for post author

- ios/Podfile.lock
- lib/app/features/chat/views/components/message_items/messages_context_menu/messages_context_menu.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/action_button.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar_recording.dart
Fix voice recording delay where recording wouldn't start right after user grants microphone permission.
- remove unused share button functionality
https://github.com/user-attachments/assets/c568633e-b69d-4a09-8c95-f34c0560d77e
> bugfix: start voice record immediately if user gave a permission

- ios/Podfile.lock
- lib/app/features/feed/create_post/views/components/post_submit_button/post_submit_button.dart
- lib/app/features/feed/create_post/views/pages/post_form_modal/components/video_preview_cover.dart
- lib/app/features/feed/create_post/views/pages/post_form_modal/post_form_modal.dart
- lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart
- lib/app/router/feed_routes.dart
- lib/app/services/logger/logger.dart
- lib/app/services/logger/logger_initializer.dart
> feat: add a banuba editor to the create video flow

- lib/app/features/gallery/providers/albums_provider.c.dart
Fix pagination by set provider as keepAlive
> fix: media picker albums pagination

- lib/app/features/feed/create_article/providers/create_article_provider.c.dart
- lib/app/features/feed/providers/feed_posts_provider.c.dart
- lib/app/features/feed/providers/repost_notifier.c.dart
> fix: add correct new entities listen on feed depending on the category

- lib/app/features/chat/e2ee/views/pages/one_to_one_messages_page.dart
- lib/app/features/chat/views/components/message_items/message_types/visual_media_message/visual_media_message.dart
- lib/app/features/chat/views/components/message_items/message_types/visual_media_message/visual_media_metadata.dart
Update visual media message component layout for preventing layout errors while rendering
Error log
`RenderFlex#304ee relayoutBoundary=up19 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE(creator: Row ← VisualMediaMetadata ← Row ← Column ← IntrinsicWidth ← SizedBox ← Listener ← _GestureSemantics ← RawGestureDetector ← GestureDetector ← Padding ← DecoratedBox ← ⋯, parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size), constraints: BoxConstraints(unconstrained), size: MISSING, direction: horizontal, mainAxisAlignment: space-between, mainAxisSize: min, crossAxisAlignment: end, textDirection: ltr, verticalDirection: down, spacing: 0.0)`
> fix: resolve visual media message flex layout issue

- lib/app/features/feed/views/components/overlay_menu/own_entity_menu.dart
> fix: enable post options menu for regular, non modifiable posts

- lib/app/features/feed/views/pages/fullscreen_media/components/video_carousel.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
> feat: add wakelock to video carousel

- ios/Podfile.lock
- lib/app/services/compressor/compress_service.c.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
> fix: use ffmpeg fork

- lib/app/features/feed/views/pages/fullscreen_media/fullscreen_media_page.dart
> fix: add edit and delete menu from post to full media page

- pubspec.lock
- pubspec.yaml
Just point to ffmpeg fork branch with local ffmpeg binaries for ios and android
> feat: use local ffmpeg binaries for ios and android

- lib/app/components/text_editor/attributes.dart
- lib/app/components/text_editor/components/suggestions_container.dart
- lib/app/components/text_editor/text_editor.dart
- lib/app/components/text_editor/utils/mentions_hashtags_handler.dart
- lib/app/features/core/model/feature_flags.dart
- lib/app/features/core/providers/feature_flags_provider.c.dart
- lib/app/features/feed/create_post/views/pages/post_form_modal/components/create_post_bottom_panel.dart
- lib/app/features/feed/create_post/views/pages/post_form_modal/components/create_post_content.dart
- lib/app/features/feed/create_post/views/pages/post_form_modal/post_form_modal.dart
- lib/app/features/feed/providers/article/cashtag_suggestions_provider.c.dart
- lib/app/features/feed/providers/article/hashtag_suggestions_provider.c.dart
- lib/app/features/feed/providers/article/mention_suggestions_provider.c.dart
- lib/app/features/feed/providers/article/suggestions_notifier_provider.c.dart
- lib/app/features/feed/views/components/toolbar_buttons/toolbar_hashtag_button.dart
- lib/app/features/feed/views/components/toolbar_buttons/toolbar_mention_button.dart
https://github.com/user-attachments/assets/3bbd04c6-973c-4a8a-806e-af3d2c57401d
> fix: rework on how text formatting is done for casthags, hashtags and mentions

- lib/app/features/chat/model/message_list_item.c.dart
- lib/app/features/chat/views/components/message_items/message_item_wrapper/message_item_wrapper.dart
- lib/app/features/chat/views/components/message_items/message_types/text_message/text_message.dart
- Fixes alignment issues in replies
> fix:  text alignment in replies

- .github/workflows/CICD.yaml
- lib/app/features/core/providers/env_provider.c.dart
- lib/main.dart
- packages/ion_identity_client/example/lib/providers/ion_identity_provider.c.dart
- packages/ion_identity_client/example/pubspec.lock
- packages/ion_identity_client/example/pubspec.yaml
- pubspec.lock
- pubspec.yaml
> chore: migrate to compile time constants from dotenv

- lib/app/components/inputs/text_input/components/text_input_icons.dart
> fix: general text input prefix icon paddings

- android/app/src/main/kotlin/io/ion/app/VideoEditorModule.kt
- ios/Podfile.lock
- ios/Runner/VideoEditorModule.swift
> feat: update video editor configuration to disable drafts

- lib/app/features/feed/stories/views/components/story_capture/camera/camera_idle_preview.dart
> fix: swap icons and actions for story control buttons in camera idle preview

- lib/app/components/text_editor/hooks/use_text_editor_has_content.dart
- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_carousel_horizontal.dart
- check if the text editor has content
- change padding
> fix: feed issues

- ios/Podfile.lock
- lib/app/features/feed/create_post/views/components/post_submit_button/post_submit_button.dart
- lib/app/features/feed/create_post/views/hooks/use_can_submit_post.dart
- lib/app/features/feed/create_post/views/hooks/use_changed_media_attachments.dart
> fix: allow post submit after removing media during post edit

- lib/app/features/chat/views/components/message_items/message_types/visual_media_message/visual_media_custom_grid.dart
Reorganize the media items in the grid to match the Figma design.
N/A
> fix(chat): Adjust visual media grid layout

- lib/app/features/video/views/pages/videos_vertical_scroll_page.dart
- pubspec.lock
> fix: update user info menu on video scroll in trending videos

- lib/app/router/base_route_data.dart
> fix: ios backswipe pop navigation

- ios/Podfile.lock
- lib/app/features/components/entities_list/entities_list.dart
- lib/app/features/feed/views/components/overlay_menu/user_info_menu.dart
- lib/app/features/feed/views/pages/feed_page/components/feed_posts_list/feed_posts_list.dart
- lib/app/features/ion_connect/model/mute_set.c.dart
- lib/app/features/user/pages/profile_page/components/tabs/tab_entities_list.dart
- lib/app/features/user/providers/block_list_notifier.c.dart
- lib/app/features/user/providers/muted_users_notifier.c.dart
> feat: add logic for not interested post option

- lib/app/features/video/views/pages/video_page.dart
> fix: make video cover full screen

- lib/app/features/gallery/data/models/gallery_state.c.dart
- lib/app/features/gallery/providers/gallery_provider.c.dart
- lib/app/features/gallery/views/pages/media_picker_page.dart
- lib/app/services/media_service/media_service.c.dart
Fix gallery media slow loading
> fix: high memory consumption

- pubspec.lock
- pubspec.yaml
> chore: update markdown_quill dependency to master branch

- lib/app/services/media_service/aspect_ratio.dart
Just increase maximum landscape aspect ratio to 2
> feat: increase maximum landscape aspect ratio to 2.0

- ios/Podfile.lock
- lib/app/components/image/ion_network_image.dart
- lib/app/components/placeholder/ion_placeholder.dart
- lib/app/components/video_preview/video_preview.dart
- lib/app/features/chat/views/components/message_items/message_types/url_preview_message/components/meta_data_preview.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/viewers/image_story_viewer.dart
- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_item.dart
- lib/app/features/feed/views/components/url_preview_content/components/url_metadata_preview.dart
- lib/app/features/feed/views/pages/feed_page/components/trending_videos/components/trending_videos_list_item.dart
- lib/app/features/user/pages/components/user_banner/user_banner.dart
Add thumbnail for unavailable content (images, gifs, videos)
> feat: add placeholder image on image load error

- lib/app/features/feed/create_article/providers/create_article_provider.c.dart
> feat: compress all uploaded images to webp

- lib/app/features/user/pages/profile_page/components/profile_details/follow_counters/follow_counters.dart
- lib/app/features/user/pages/profile_page/components/profile_details/follow_counters/follow_counters_cell.dart
Show following and followers counter at the same time.
> fix: sync display follow

- ios/Podfile.lock
- lib/app/features/chat/community/providers/community_messages_subscriber_provider.c.dart
- lib/app/features/chat/e2ee/providers/e2ee_messages_subscriber.c.dart
- lib/app/features/chat/model/database/dao/conversation_event_message_dao.c.dart
- lib/app/features/feed/notifications/data/database/dao/comments_dao.c.dart
- lib/app/features/feed/notifications/data/database/dao/followers_dao.c.dart
- lib/app/features/feed/notifications/data/database/dao/likes_dao.c.dart
- lib/app/features/feed/notifications/data/repository/comments_repository.c.dart
- lib/app/features/feed/notifications/data/repository/followers_repository.c.dart
- lib/app/features/feed/notifications/data/repository/ion_notification_repository.dart
- lib/app/features/feed/notifications/data/repository/likes_repository.c.dart
- lib/app/features/feed/notifications/providers/notification_followers_subscription_provider.c.dart
- lib/app/features/feed/notifications/providers/notification_likes_subscription_provider.c.dart
- lib/app/features/feed/notifications/providers/notification_quotes_subscription_provider.c.dart
- lib/app/features/feed/notifications/providers/notification_replies_subscription_provider.c.dart
- lib/app/features/feed/notifications/providers/notification_reposts_subscription_provider.c.dart
- lib/app/features/ion_connect/providers/entities_syncer_notifier.c.dart
- lib/app/features/wallets/data/database/dao/funds_requests_dao.c.dart
- lib/app/features/wallets/data/database/dao/transactions_dao.c.dart
- lib/app/features/wallets/data/repository/request_assets_repository.c.dart
- lib/app/features/wallets/data/repository/transactions_repository.c.dart
- lib/app/features/wallets/providers/transactions_subscription_provider.c.dart
> fest: add entities syncer and integrate it into notifications providers

- lib/app/exceptions/exceptions.dart
- lib/app/features/auth/providers/onboarding_complete_provider.c.dart
- lib/app/features/core/providers/main_wallet_provider.c.dart
- lib/app/features/core/providers/wallets_provider.c.dart
- lib/app/features/core/views/pages/error_page.dart
- lib/app/router/app_routes.c.dart
- lib/app/router/providers/go_router_provider.c.dart
- packages/ion_identity_client/lib/ion_identity.dart
- packages/ion_identity_client/lib/src/auth/services/login/login_service.dart
- packages/ion_identity_client/lib/src/auth/services/recover_user/data_sources/recover_user_data_source.dart
- packages/ion_identity_client/lib/src/auth/services/twofa/data_sources/twofa_data_source.dart
- packages/ion_identity_client/lib/src/core/network/network_client.dart
- packages/ion_identity_client/lib/src/networks/services/get_estimate_fees/data_sources/get_estimate_fees_data_source.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_assets/data_sources/get_wallet_assets_data_source.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_history/data_sources/get_wallet_history_data_source.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_nfts/data_sources/get_wallet_nfts_data_source.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/data_sources/get_wallet_transfer_requests_data_source.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallets/data_sources/get_wallets_data_source.dart
Redirect to Error page if Onboarding meets an error from ION Identity Client.
> fix(init): if an error happens in the Wallets request, redirect to ErrorPage

- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_carousel_horizontal.dart
- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_carousel_vertical.dart
- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_index_indicator.dart
This PR adds a media index indicator to media carousel with horizontal AR media
> feat: add index indicator to horizontal carousel post media

- lib/app/router/main_tabs/main_tab_navigation.dart
> fix: allow for application exit on android system back button tap when there are no more pages to pop

- lib/app/router/profile_routes.dart
Fix follow list flicker on pop by set it as `bottomSheet`
> fix: follow list flicker on pop

- lib/app/features/feed/create_post/views/pages/post_form_modal/post_form_modal.dart
Add bottom padding for post modal
> fix: create post modal bottom padding

- lib/app/features/user/pages/profile_page/pages/follow_list_modal/relevant_followers_list.dart
- lib/app/features/video/views/components/video_post_info.dart
> chore: remove solved todos

- lib/app/features/protect_account/authenticator/views/pages/setup_authenticator/authenticator_setup_options_page.dart
- pubspec.yaml
> fix: update external app launcher lib to latest version to cover ios bug

- lib/app/features/chat/e2ee/providers/e2ee_delete_event_provider.c.dart
- lib/app/features/chat/views/components/message_items/message_types/money_message/components/money_message_button.dart
- lib/app/features/chat/views/components/message_items/message_types/money_message/money_message.dart
This PR adds ability to cancel (delete) a funds request message you sent.
https://github.com/user-attachments/assets/52e00741-857a-4b4e-80e8-9ffe9b81b22c
> feat: cancel funds request message

- lib/app/features/user/providers/user_delegation_provider.c.dart
This PR fixes a bug when a user cannot log in after a logout. Read a comment in the code for details.
> fix(auth): add isAuthenticated to userDelegationProvider

- lib/app/components/progress_bar/ion_loading_indicator.dart
> fix: ion loader not animating

- lib/app/features/feed/views/pages/add_bookmark_modal/add_bookmark_modal.dart
> fix: add shrinkwrap to add bookmark model

- lib/app/features/feed/providers/feed_bookmarks_notifier.c.dart
> fix: add user relays availability await inside feed bookmarks notifier to avoid exceptions during register

- lib/app/features/ion_connect/database/dao/event_messages_dao.c.dart
- lib/app/features/ion_connect/database/tables/event_messages_table.c.dart
- lib/app/features/ion_connect/model/event_serializable.dart
- lib/app/features/ion_connect/providers/ion_connect_db_cache_notifier.c.dart
- lib/app/features/ion_connect/repository/event_messages_repository.c.dart
- lib/app/features/user/model/user_relays.c.dart
> feat: add db cache provider

- lib/app/features/components/user/follow_user_button/follow_user_button.dart
- lib/app/features/user/pages/profile_page/components/profile_details/profile_actions/profile_actions.dart
- lib/app/features/user/pages/profile_page/pages/follow_list_modal/components/follow_list_item.dart
Add follow back button to followers list
> feat: add follow back button to followers list

- lib/app/features/user/providers/followers_data_source_provider.c.dart
Set entity filter to kind 3 to get right until param
> fix: followers pagination

- lib/app/features/user/pages/profile_page/components/profile_details/follow_counters/follow_counters_cell.dart
- lib/app/features/user/pages/profile_page/components/profile_details/relevant_followers/followed_by_text.dart
- lib/app/features/user/pages/profile_page/pages/follow_list_modal/components/follow_list_item.dart
- lib/app/router/profile_routes.dart
Fix navigation issue to user profile from following/followers lists
> fix: following/followers route

- lib/app/features/ion_connect/providers/entities_paged_data_provider.c.dart
- lib/app/features/user/pages/profile_page/pages/follow_list_modal/followers_list.dart
- lib/app/features/user/providers/followers_data_source_provider.c.dart
Add search for followers list
- Add `pagedFilter` to handle edge case with pagination
> feat: add followers search

- ios/Podfile.lock
- lib/app/features/feed/data/models/bookmarks/bookmarks_collection.c.dart
- lib/app/features/feed/providers/feed_bookmarks_notifier.c.dart
> feat: add support for immutable events bookmarking

- lib/app/features/user/pages/profile_page/components/tabs/tab_entities_list.dart
- lib/app/features/user/pages/profile_page/profile_page.dart
> feat: invalidate user metadata on profile pull to refresh

- lib/app/features/core/providers/video_player_provider.c.dart
- lib/app/features/video/views/pages/video_page.dart
> fix: video continues playing after leaving trending video full screen page

- android/app/src/main/res/values/styles.xml
- lib/app/features/auth/views/pages/fill_profile/fill_profile.dart
- lib/app/features/chat/views/pages/chat_add_poll_modal/chat_add_poll_modal.dart
- lib/app/features/chat/views/pages/chat_learn_more_modal/chat_learn_more_modal.dart
- lib/app/features/chat/views/pages/chat_main_modal/chat_main_modal_page.dart
- lib/app/features/feed/create_article/views/pages/article_form_modal/article_form_modal.dart
- lib/app/features/feed/create_article/views/pages/article_preview_modal/article_preview_modal.dart
- lib/app/features/feed/create_post/views/pages/post_form_modal/post_form_modal.dart
- lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart
- lib/app/features/settings/views/settings_modal.dart
- lib/app/features/wallets/views/pages/coins_flow/coin_receive_modal/coin_receive_modal.dart
- lib/app/features/wallets/views/pages/coins_flow/network_list/network_list_view.dart
- lib/app/features/wallets/views/pages/wallet_main_modal/wallet_main_modal_page.dart
- lib/app/features/wallets/views/pages/wallet_scan_modal_page.dart
- lib/app/features/wallets/views/pages/wallets_modal.dart
- lib/app/router/components/sheet_content/sheet_content.dart
- Add default safe area for sheet content
- Fix paddings for some screens
| Before | After |
|--------|-------|
| ![before](https://github.com/user-attachments/assets/60de5aa4-162a-459d-94dd-eec25bbc19d0) ![before](https://github.com/user-attachments/assets/a58dc97d-8b9b-411a-9a04-d1a918d30fe1)| ![after](https://github.com/user-attachments/assets/7ddbc5bc-6fa8-4dc1-bcf8-539d3b5b46c1) ![after](https://github.com/user-attachments/assets/58f188c7-70a2-4c40-abdf-bee588b362f8)|
> fix: safe area

- lib/app/extensions/iterable.dart
- lib/app/features/video/views/pages/videos_vertical_scroll_page.dart
> fix: avoid duplicated videos from reposts displayed in videos vertical scroll page

- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart
> fix: make app bar in send coin modal pinned to avoid hiding on scroll

- lib/app/features/wallets/views/pages/coins_flow/receive_coins/providers/wallet_address_notifier_provider.c.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/widgets/not_enough_coins_for_network_fee_message.dart
Changes:
1. Fixed issue, when after tap on deposit app asked to deposit transferred token, not the native to pay fee.
2. Fixed wrong source of the crypto wallets.
3. Improved search of the wallet.
https://github.com/user-attachments/assets/a44d9952-05d3-4ff5-954f-4f86679702d4
> fix: issues with native token deposit during transfer

- lib/app/features/wallets/views/components/arrival_time/network_fee_selector.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/coins_network_fee_selector.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart
- lib/app/features/wallets/views/pages/transaction_details/transaction_details.dart
> fix: make app bar in transaction details and send coins pinned to avoid hiding on scroll

- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/confirmation/confirmation_sheet.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/confirmation/transaction_amount_summary.dart
- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/confirmation/transaction_result_sheet.dart
- lib/app/features/wallets/views/pages/transaction_details/transaction_details.dart
> fix: add proper plus or minus sign to coin transaction amount, depending on the receiver

- lib/app/features/wallets/model/balance_display_order.dart
- lib/app/features/wallets/model/user_preferences.c.dart
- lib/app/features/wallets/providers/wallet_user_preferences/user_preferences_selectors.c.dart
- lib/app/features/wallets/providers/wallet_user_preferences/wallet_user_preferences_provider.c.dart
- lib/app/features/wallets/views/pages/coins_flow/coin_details/components/balance/balance.dart
- lib/app/features/wallets/views/pages/coins_flow/coin_details/components/balance/coin_usd_amount.dart
https://github.com/user-attachments/assets/24345517-9854-4751-9cf7-8e87335f2380
> feat: add balance display order switch on top balance amount tap

- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/buttons/coin_amount_input.dart
- lib/app/utils/text_input_formatters.dart
> feat: add 18 decimals characters limit to coin amount input

- .gitignore
- ios/Podfile.lock
- lib/app/features/core/providers/env_provider.c.dart
- lib/app/services/sentry/sentry_service.dart
- lib/main.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
> feat: setup sentry

- lib/app/features/wallets/views/pages/send_nft_form.dart
This PR fixes an issue when the Send NFT flow can be finished with an empty destination address.
> fix: Send NFT add address validation

- ios/Podfile.lock
- lib/app/features/chat/e2ee/views/components/one_to_one_messages_list.dart
- lib/app/features/chat/views/components/message_items/message_types/visual_media_message/visual_media_message.dart
- lib/app/utils/string.dart
> bugfix: scrolling fixes

- lib/app/features/feed/stories/views/components/story_viewer/components/header/story_context_menu.dart
> fix: update story report to use content reference instead of user pubkey

- lib/app/features/components/entities_list/entities_list.dart
- lib/app/features/components/entities_list/entities_list_skeleton.dart
- lib/app/features/feed/create_post/views/components/reply_input_field/reply_input_field.dart
- lib/app/features/feed/views/pages/feed_page/components/stories/stories.dart
- lib/app/features/feed/views/pages/feed_page/components/trending_videos/trending_videos.dart
- lib/app/features/feed/views/pages/post_details_page/post_details_page.dart
> feat: decrease entities list padding between items, fix left padding in quick reply bar

- lib/app/features/user/pages/profile_page/components/tabs/tab_entities_list.dart
- lib/app/features/user/pages/profile_page/profile_page.dart
- lib/app/features/wallets/views/pages/wallet_page.dart
This PR adds a missing pull to refresh to wallet and profile tabs for android.
> fix: add missing pull to refresh to wallet and profile on android

- lib/app/exceptions/exceptions.dart
- lib/app/features/chat/e2ee/providers/send_chat_message/send_e2ee_chat_message_service.c.dart
- lib/app/features/chat/e2ee/views/components/one_to_one_messages_list.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/action_button.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/audio_record_button.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/delete_audio_button.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/pause_audio_button.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/play_audio_button.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/recording_overlay.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/voice_message_preview_tile.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar.dart
- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar_recording.dart
- lib/app/services/compressors/audio_compressor.c.dart
- lib/app/services/media_service/ffmpeg_commands_config.dart
- pubspec.yaml
This PR adds the ability to pause and resume voice message recording.
- Adjust padding on the conversation page between the date label and the first message.
https://github.com/user-attachments/assets/2b3efadc-c7da-46af-8114-2c83854d3eb3
> feat: add pause/resume functionality to voice message recording

- ios/Podfile.lock
- lib/app/features/chat/e2ee/providers/send_chat_message/send_e2ee_chat_message_service.c.dart
- lib/app/features/feed/stories/providers/story_reply_provider.c.dart
Adds missing quoted event to kind 14 message
> fix: story reply 

- ios/Podfile.lock
- lib/app/features/chat/e2ee/model/entities/private_direct_message_data.c.dart
- lib/app/features/chat/recent_chats/providers/money_message_provider.c.dart
- lib/app/features/wallets/data/database/dao/funds_requests_dao.c.dart
- lib/app/features/wallets/data/repository/request_assets_repository.c.dart
- lib/app/features/wallets/domain/transactions/send_transaction_to_relay_service.c.dart
- lib/app/features/wallets/providers/transactions_subscription_provider.c.dart
This PR fixes some issues with the MoneyMessage in chat.
Most of them were caused by the `EventMasterPubkeyNotFoundException` in `transactionsSubscriptionProvider` during the `await ref.watch(entitiesSyncerNotifierProvider('transactions').notifier).syncEvents(...);`. Because of that exception, we couldn't do the sync and couldn't subscribe to the new events.
One more issue was that the MoneyMessage wasn't updated on a receiver's side after being paid. I changed `get` to `watch` request to the DB.
> fix: money message issues

- lib/app/features/user/pages/profile_page/components/profile_details/follow_counters/follow_counters.dart
- lib/app/features/user/pages/profile_page/pages/follow_list_modal/followers_list.dart
- lib/app/features/user/pages/profile_page/profile_page.dart
- lib/app/features/user/providers/followers_count_provider.c.dart
- Use cache for followers count
- Refresh followers count on pull to refresh
- Improve profile page pull to refresh
> feat: improve profile page refresh handling

- lib/app/utils/text_input_formatters.dart
- test/utils/text_input_formatters_test.dart
Added handling and covered with tests.
https://github.com/user-attachments/assets/433c2d20-4229-445e-9097-0f83be9c72f9
> fix: added handling for pasting text into the coin amount input field

- lib/app/router/main_tabs/main_tab_navigation.dart
> feat: always close app when system back button is tapped on feed tab on android

- ios/Podfile.lock
- lib/app/features/chat/e2ee/model/entities/private_direct_message_data.c.dart
- lib/app/features/chat/e2ee/providers/send_chat_message/send_e2ee_chat_message_service.c.dart
Fixed issue when messages are marked as "edited"
> fix: Set same createdAt time

- lib/app/components/scroll_view/pull_to_refresh_builder.dart
- lib/app/features/user/pages/profile_page/components/tabs/tab_entities_list.dart
- lib/app/features/wallets/views/pages/coins_flow/coin_details/coin_details_page.dart
> fix: pull to refresh on coin details page not working for android

- lib/app/features/chat/e2ee/providers/e2ee_messages_subscriber.c.dart
Sets wrap messages request to unlimited
> fix: set unlimited messages request

- lib/app/extensions/delta.dart
- lib/app/features/feed/views/components/post/components/post_body/post_body.dart
This PR hides the text of a post if it only contains a single link (preview of it is displayed instead)
> feat: hide post text body if post contains only single link

- lib/app/features/wallets/views/pages/coins_flow/coin_details/coin_details_page.dart
> fix: add bottom offset to the coin details transaction list

- lib/app/features/chat/model/database/dao/conversation_event_message_dao.c.dart
This PR fixes an issue where the last version of edited messages is kept in the local db.
N/A
> fix(chat): ensure edited messages reflect latest version

- lib/app/features/wallets/data/database/wallets_database.c.dart
> fix: use schema table inside the migrator. Fix not working migration from 9 to 10

- lib/app/features/feed/create_post/views/pages/post_form_modal/components/create_post_content.dart
- lib/app/features/feed/views/components/url_preview_content/url_preview_content.dart
> fix: make link preview in post body clickable

- lib/app/features/chat/recent_chats/views/pages/delete_message_modal/delete_message_modal.dart
- lib/l10n/app_en.arb
This PR updates the delete message modal text for clarity.
N/A
> fix(chat): update delete message modal text for clarity

- lib/app/features/chat/views/pages/chat_media_page/chat_media_page.dart
- lib/app/features/chat/views/pages/chat_media_page/components/chat_media_context_menu.dart
- lib/app/features/feed/stories/providers/camera_capture_provider.c.dart
- lib/app/services/media_service/media_service.c.dart
This PR addresses the context menu for the chat media preview screen.
N/A
> fix: handle context menu of chat media preview screen

- ios/Podfile.lock
- lib/app/features/chat/e2ee/providers/e2ee_delete_event_provider.c.dart
- lib/app/features/chat/e2ee/views/components/one_to_one_messages_list.dart
- lib/app/features/chat/model/database/chat_database.c.dart
- lib/app/features/chat/model/database/dao/conversation_message_dao.c.dart
- lib/app/features/chat/model/database/dao/event_message_dao.c.dart
- lib/app/features/chat/providers/conversation_messages_provider.c.dart
- lib/app/features/chat/recent_chats/views/components/recent_chat_tile/recent_chat_tile.dart
- lib/app/features/chat/views/components/message_items/message_item_wrapper/message_item_wrapper.dart
- lib/app/features/chat/views/components/message_items/message_types/audio_message/audio_message.dart
- lib/app/features/chat/views/components/message_items/message_types/document_message/document_message.dart
- lib/app/features/chat/views/components/message_items/message_types/emoji_message/emoji_message.dart
- lib/app/features/chat/views/components/message_items/message_types/money_message/money_message.dart
- lib/app/features/chat/views/components/message_items/message_types/post_message/post_message.dart
- lib/app/features/chat/views/components/message_items/message_types/post_message/shared_post_message.dart
- lib/app/features/chat/views/components/message_items/message_types/post_message/shared_story_message.dart
- lib/app/features/chat/views/components/message_items/message_types/profile_share_message/profile_share_message.dart
- lib/app/features/chat/views/components/message_items/message_types/text_message/text_message.dart
- lib/app/features/chat/views/components/message_items/message_types/visual_media_message/visual_media_message.dart
- lib/app/features/feed/views/components/article/article.dart
- lib/app/features/feed/views/components/post/post.dart
- pubspec.lock
- Improves performance of the chat by reducing amount of rebuids 
- Fixes reposted chat messages UI
> fix: chat performance and reposts messages

- lib/app/features/chat/recent_chats/views/components/recent_chat_tile/recent_chat_tile.dart
- lib/app/features/chat/views/components/message_items/message_metadata/message_metadata.dart
- Adds status to the recent chat tile
> feat: add status to recent chat tile

- lib/app/features/chat/views/components/message_items/message_types/audio_message/audio_message.dart
This PR addresses the issue of enhancing the handling of voice message loading states.
N/A
> fix: improve voice message loading state handling

- lib/app/features/chat/views/pages/chat_media_page/components/chat_media_page_view.dart
- lib/app/features/video/views/pages/video_page.dart
> fix: reduce the side cropping of video inside full screen video page

- lib/app/exceptions/exceptions.dart
- lib/app/features/wallets/domain/wallet_views/wallet_views_service.c.dart
- lib/app/features/wallets/providers/send_coins_notifier_provider.c.dart
- lib/app/features/wallets/views/pages/coins_flow/coin_details/providers/coin_transaction_history_notifier_provider.c.dart
This pr
1. Adds a bunch of the logs to catch floating bugs, related to transactions and coin balance;
2. Fixes retry function in case of the wrong transfer status.
> chore: add logs to the transactions/wallets to catch floating bugs

- lib/app/features/chat/views/components/message_items/message_types/profile_share_message/profile_share_message.dart
- lib/l10n/app_en.arb
This PR updates the profile share button text to "View Profile."
> fix: update profile share button text to view profile

- lib/app/features/chat/e2ee/views/components/one_to_one_messages_list.dart
This PR resolves an issue in the chat: it dismisses the keyboard when the user scrolls down on the messages screen.
N/A
https://github.com/user-attachments/assets/99ce8ac6-8e24-4949-a2dd-c4590ffe6cda
> fix(chat): dismiss keyboard when user scrolls down on messages screen

- lib/app/features/core/providers/exception_presenter_provider.c.dart
Fixed order of the handled cases for proper displaying.
> fix: order of the handled cases in the ExceptionPresenter

- lib/app/features/chat/views/pages/share_via_message_modal/components/share_send_button.dart
This PR fixes the issue of sharing a profile from the profile page's context menu.
> fix: share profile from profile page context menu

- lib/app/features/core/providers/env_provider.c.dart
> fix: add relay ping interval default value

- lib/app/features/feed/global_notifications/helpers/feed_global_notifications_helper.dart
This PR improves notification handling by implementing a permanent loading state until an error occurs or success is achieved.
N/A
> fix: update notification handling to show permanent loading state

- lib/app/features/chat/views/pages/chat_media_page/components/chat_media_page_view.dart
- lib/app/features/feed/create_post/providers/create_post_notifier.c.dart
- lib/app/features/feed/views/pages/fullscreen_media/components/single_media_view.dart
- lib/app/features/feed/views/pages/fullscreen_media/components/video_carousel.dart
- lib/app/features/video/views/components/video_thumbnail_preview.dart
- lib/app/features/video/views/pages/video_page.dart
- lib/app/features/video/views/pages/videos_vertical_scroll_page.dart
- lib/app/services/media_service/blurhash_service.c.dart
> feat: add video thumbnail preview for improved loading UX

- android/app/src/main/kotlin/io/ion/app/MainActivity.kt
- android/app/src/main/kotlin/io/ion/app/VideoEditorModule.kt
- ios/Runner/VideoEditorModule.swift
This PR fixes an issue where any vertical video going through banuba editor ended up being horizontal
> fix: stop banuba from converting horizontal videos to vertical

- lib/app/features/user/providers/request_coins_submit_notifier.c.dart
- lib/app/features/wallets/domain/transactions/send_transaction_to_relay_service.c.dart
- lib/app/features/wallets/model/entities/funds_request_entity.c.dart
- lib/app/features/wallets/model/entities/wallet_asset_entity.c.dart
- lib/app/features/wallets/providers/send_coins_notifier_provider.c.dart
Update keys for 1755 and 1756 to fix unwrapGift issue
> fix(chat): change keys for 1755 and 1756

- lib/app/features/chat/views/components/message_items/message_types/post_message/shared_story_message.dart
This PR resolves an issue by adding a margin to the chat post message.
N/A
> fix: add margin for chat post message

- lib/app/components/scroll_view/ion_pull_to_refresh_loading_indicator.dart
> feat: update pull to refresh indicator size

- lib/app/utils/text_input_formatters.dart
Fixed issues:
1. Reset input value to zero if dot was entered.
2. Cursor calculation.
> fix: dot inserting and cursor calculation

- lib/app/features/chat/views/components/message_items/message_types/money_message/money_message.dart
this PR fixes delivery status for fund transfer chat message
> fix: show delivery status for fund transfer chat message

- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/confirmation/confirmation_sheet.dart
- lib/app/router/wallet_routes.dart
Screenshot after transfer with the same flow before fix, and demo after fix.
https://github.com/user-attachments/assets/d3a43770-c36d-49f2-85fc-b926c334b933
> chore: add RedirectType to control the redirection way after success transfer

- packages/ion_identity_client/lib/src/users/update_user_social_profile/models/user_social_profile_data.c.g.dart
- packages/ion_identity_client/lib/src/wallets/models/requester.c.dart
- packages/ion_identity_client/lib/src/wallets/models/requester.c.freezed.dart
- packages/ion_identity_client/lib/src/wallets/models/requester.c.g.dart
The API is changed, just updated the model to get rid of NPE
> fix(ion_identity_client): update Requester model

- ios/Podfile.lock
- lib/app/components/url_preview/providers/url_metadata_provider.c.dart
- lib/app/features/auth/providers/auth_provider.c.dart
- lib/app/features/user/pages/profile_page/profile_page.dart
- lib/app/features/user_block/model/database/block_user_database.c.dart
- lib/app/features/user_block/model/database/dao/block_event_dao.c.dart
- lib/app/features/user_block/model/database/dao/unblock_event_dao.c.dart
- lib/app/features/user_block/optimistic_ui/block_sync_strategy_provider.c.dart
- lib/app/features/user_block/optimistic_ui/block_user_provider.c.dart
- lib/app/features/user_block/providers/block_list_notifier.c.dart
- lib/app/features/user_block/providers/blocked_users_database_provider.c.dart
- lib/app/features/user_block/providers/blocked_users_sync_provider.c.dart
- lib/app/services/provider_rebuild_counter/provider_rebuild_counter.dart
- lib/app/services/riverpod/container.dart
- lib/main.dart
- Block notifiers became keep alive till logout
- Circular dependency watcher
> fix: block user circular dependency

- lib/app/components/url_preview/url_preview.dart
- lib/app/features/feed/views/components/post/components/post_body/post_body.dart
This PR fixes a wrong condition which was causing an empty post to be displayed if the url preview couldn't load.
> fix: empty posts

- lib/app/features/chat/providers/user_chat_relays_sync_provider.c.dart
- lib/app/features/user/providers/user_file_storage_relays_sync_provider.c.dart
This PR fixes infinite requests loop caused by inappropriate sets comparison.
> fix: compare sets properly

- lib/app/features/feed/stories/views/components/story_viewer/components/viewers/video_story_viewer.dart
> fix: aspect ratio for horizontal videos in stories

- lib/app/features/wallets/data/repository/transactions_repository.c.dart
- packages/ion_identity_client/lib/ion_identity.dart
Assume that UTXO transfers are native transfers.
Fixes after ION-2792
> chore: add support of the native transfers for the utxo networks

- lib/app/features/core/providers/env_provider.c.dart
- lib/app/features/core/providers/init_provider.c.dart
- lib/app/features/feed/create_article/providers/create_article_provider.c.dart
- lib/app/features/feed/create_article/views/pages/article_preview_modal/article_preview_modal.dart
- lib/app/features/feed/create_post/providers/create_post_notifier.c.dart
- lib/app/features/feed/create_post/views/components/topics/topics_button.dart
- lib/app/features/feed/data/models/feed_config.c.dart
- lib/app/features/feed/data/models/feed_interests.c.dart
- lib/app/features/feed/providers/feed_for_you_content_provider.c.dart
- lib/app/features/feed/providers/feed_selected_article_categories_provider.c.dart
- lib/app/features/feed/providers/feed_selected_visible_article_categories_provider.c.dart
- lib/app/features/feed/providers/feed_user_interest_picker_provider.c.dart
- lib/app/features/feed/providers/feed_user_interests_provider.c.dart
- lib/app/features/feed/providers/selected_interests_notifier.c.dart
- lib/app/features/feed/views/pages/feed_article_categories/feed_visible_article_categories_modal.dart
- lib/app/features/feed/views/pages/feed_page/components/article_categories_menu/article_categories_menu.dart
- lib/app/features/feed/views/pages/feed_page/components/article_categories_menu/article_categories_row.dart
- lib/app/features/feed/views/pages/feed_page/feed_page.dart
- lib/app/features/feed/views/pages/topics_modal/select_topics_categories_modal.dart
- lib/app/features/ion_connect/model/related_hashtag.c.dart
- lib/app/features/wallets/views/components/network_icon_widget.dart
- lib/app/router/app_routes.c.dart
- lib/app/router/feed_routes.dart
- lib/l10n/app_en.arb
- test/feed/feed_user_interests_picker_test.dart
This PR adds support for new topics on article feed page.
https://github.com/user-attachments/assets/177d7d20-5bad-4726-be62-7288bd2b79ee
> feat: support new topics in article categories on feed

- lib/app/features/config/providers/config_repository.c.dart
- lib/app/features/feed/providers/feed_config_provider.c.dart
- lib/app/features/feed/providers/feed_user_interests_provider.c.dart
- lib/app/features/push_notifications/providers/app_translations_provider.c.dart
- lib/app/features/user/providers/service_pubkeys_provider.c.dart
A simple refactor to simplify the `ConfigRepository` usage.
> chore: extract cacheMaxAge to ConfigRepository constructor

- lib/app/features/search/providers/chat_users_search_provider.c.dart
- lib/app/features/search/views/pages/feed_advanced_search_page/components/feed_advanced_search_users/feed_advanced_search_users.dart
- lib/app/features/search/views/pages/feed_simple_search_page/feed_simple_search_page.dart
- lib/app/features/user/pages/user_picker_sheet/user_picker_sheet.dart
- lib/app/features/user/providers/search_users_provider.c.dart
This PR addresses the issue of flickering that occurs during chat user searches.
N/A
ION-2989
> fix: prevent flicker issue on chat user search

- lib/app/features/wallets/views/pages/coins_flow/send_coins/components/confirmation/confirmation_sheet.dart
ION-3071
1. Another page with the correct order.
2. Page before changes.
3. Page after changes.
> fix: update UI of the confirm transfer sheet

- lib/app/features/chat/providers/share_post_to_chat_provider.r.dart
- lib/app/features/chat/views/components/message_items/message_item_wrapper/message_item_wrapper.dart
- lib/app/features/chat/views/components/message_items/message_reaction_dialog/components/message_reaction_context_menu.dart
- lib/app/features/chat/views/components/message_items/message_reaction_dialog/message_reaction_dialog.dart
- lib/app/features/chat/views/components/message_items/message_types/post_message/post_message.dart
- lib/app/features/chat/views/components/message_items/message_types/post_message/shared_post_wrapper.dart
- lib/app/features/chat/views/pages/share_via_message_modal/components/share_send_button.dart
- lib/app/features/feed/stories/providers/story_reply_notification_provider.m.dart
- lib/app/features/feed/stories/providers/story_reply_provider.r.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/core/story_content.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/reactions/story_reaction_notification.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/reactions/story_reaction_overlay.dart
- lib/l10n/app_en.arb
- test/app/features/stories/providers/stories_basic_providers_test.dart
- Resend failed post message
- Make share post sync
ION-2799
> feat: resend failed post message

- ios/Podfile.lock
- lib/app/components/video_preview/video_preview.dart
- lib/app/features/chat/views/components/message_items/message_types/post_message/shared_story_message.dart
- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_item.dart
- lib/app/features/feed/views/components/post/components/post_body/components/post_media/post_media.dart
- lib/app/features/feed/views/components/post/components/post_body/post_body.dart
- lib/app/features/feed/views/components/post/post.dart
- lib/app/features/search/views/pages/chat/components/chat_search_results_list_item.dart
- Adds autoplay property to post
- Disables autoplay for quoted events
- Fixes shared story pop
ION-3113, ION-3081
> fix: autoplay for quoted event, shared story pop

- lib/app/features/chat/providers/share_feed_item_to_chat_provider.r.dart
- lib/app/features/chat/views/components/message_items/message_reaction_dialog/components/message_reaction_context_menu.dart
- lib/app/features/chat/views/pages/share_via_message_modal/components/share_send_button.dart
This PR enables displaying the Article in chat when a user shares it via the share modal on the feed page.
N/A
3141
> fix(chat): show shared article in conversation

- lib/app/features/feed/providers/user_posts_provider.r.dart
- lib/app/features/user/pages/profile_page/components/tabs/tab_entities_list.dart
- lib/app/features/user/providers/tab_data_source_provider.r.dart
When creating a post from the user profile, the new post was not automatically displayed in the profile feed
3138
- [х] Bug fix
>  fix: auto-update profile feed when creating posts

- ios/Podfile.lock
- lib/app/features/chat/views/pages/chat_media_page/chat_media_page.dart
- lib/app/features/chat/views/pages/chat_media_page/components/chat_media_page_view.dart
- lib/app/features/video/views/components/video_slider.dart
- lib/app/features/video/views/pages/video_page.dart
This PR fixes the issue where users were unable to interact with the video progress slider. The update enables scrubbing functionality, allowing users to seek video playback manually by dragging the slider thumb.
3007
https://github.com/user-attachments/assets/f89b1d14-e245-45b9-964a-a0c38f22bff6
> fix(chat): enable user interaction with video slider to scrub video on page

- lib/app/features/wallets/views/pages/wallet_page/components/nfts/nfts_header_layout_action.dart
> fix: hide active option in NFT layout switcher and show only selectable option

- ios/Podfile.lock
- lib/app/components/video_preview/video_preview.dart
- lib/app/features/core/providers/mute_provider.r.dart
- lib/app/features/core/providers/volume_stream_provider.r.dart
- lib/app/router/components/app_router_builder.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
- Added video mute/unmute behavior when the user presses the volume up/down button 
- Fix padding of the mute button
3176, 3152
> feat: add volume button mute/unmute functionality for videos

- ios/Runner/AppDelegate.swift
- lib/app/features/core/providers/mute_provider.r.dart
> fix: video mute behavior on login and add device silent mode support

- lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar_initial.dart
- lib/app/services/media_service/media_service.m.dart
This PR enables sharing system GIFs (e.g., from the Android keyboard) in chat.
N/A
3143
https://github.com/user-attachments/assets/eba7b91d-6abf-427c-9726-0f8e6b168106
> feat(chat): allow users to share system GIFs from Android keyboard

- ios/Podfile.lock
- lib/app/features/chat/providers/share_feed_item_to_chat_provider.r.dart
- Send posts to the participants in parallel
ION-3266
> fix: share posts to chat in parallel

- lib/app/features/chat/views/components/message_items/message_reactions/message_reactions.dart
- lib/app/features/wallets/data/database/dao/transactions_visibility_status_dao.m.dart
- lib/app/features/wallets/views/components/coins_list/coin_item.dart
- Removes duplicated logic in transactions indicators
> fix: remove duplicated logic in transactions indicators

- lib/app/features/wallets/data/database/dao/coins_dao.m.dart
- lib/app/theme/app_text_themes.dart
Hide coins with unsupported network.
ION-3334
https://github.com/user-attachments/assets/47ddf071-dd08-4dc8-b9b1-d5b77f9c3d88
> fix: networks list is not loading while requesting payment

- lib/app/features/chat/e2ee/providers/encrypted_direct_message_handler.r.dart
- Fixes bug when money messages were not handled
> fix: money request handler canHandle

- lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_carousel_vertical.dart
- lib/app/features/feed/views/components/post/components/post_body/post_body.dart
This PR fixes an issue where the feed carousel was rendering with extra horizontal margin.
N/A
3406
https://github.com/user-attachments/assets/ca36573c-603d-4bf4-9710-bc73b9dc19a8
> fix: adjust padding and layout in media carousel

- lib/app/features/feed/stories/providers/user_stories_provider.r.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/viewers/image_story_viewer.dart
- lib/app/features/feed/views/pages/entity_delete_confirmation_modal/entity_delete_confirmation_modal.dart
This PR fixes an issue where story could be seen after deletion.
> fix: story was displayed after being deleted

- lib/app/features/indexer/data/repositories/indexers_nfts_repository.r.dart
- lib/app/features/indexer/model/nft_collection_response.f.dart
- lib/app/features/indexer/model/nft_collections_query.f.dart
- lib/app/features/indexer/providers/nft_collection_sync_provider.r.dart
- lib/app/features/indexer/services/nft_collection_sync_service.r.dart
- lib/app/features/indexer/sync/nft_collection_sync_controller.r.dart
This pull request introduces a background process to find and persist a user's ION Content NFT collection. This is the foundational component for upcoming changes.
ION-3310
> feat(nft): Implement background sync for ION Content NFT collection

- lib/app/features/push_notifications/providers/relay_firebase_app_config_provider.m.dart
- get config from `relayPickerProvider` relays
ION-3477
> feat: improve firebase config retrieval

- ios/Podfile.lock
- lib/app/features/user/pages/user_picker_sheet/components/following_users.dart
- lib/app/features/user/pages/user_picker_sheet/components/searched_users.dart
- lib/app/features/wallets/views/pages/coins_flow/contact_picker/contact_picker_modal.dart
This PR addresses an issue with the message sending logic, which previously failed to handle chat privacy settings.
N/A
3450
> fix: update message sending logic to handle chat privacy settings

- packages/ion_identity_client/example/macos/Flutter/GeneratedPluginRegistrant.swift
- packages/ion_identity_client/example/pubspec.lock
- packages/ion_identity_client/lib/src/signer/passkey_signer.dart
- packages/ion_identity_client/pubspec.yaml
- pubspec.lock
- upgraded passkey lib;
- added isUserVerifyingPlatformAuthenticatorAvailable check to passkey availability check
> fix: passkey platform exception on android

- lib/app/features/components/user/follow_user_button/follow_user_button.dart
- lib/app/features/core/views/pages/unfollow_user_page.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/header/story_context_menu.dart
- lib/app/features/feed/views/components/overlay_menu/user_info_menu.dart
- lib/app/features/optimistic_ui/features/follow/follow_provider.r.dart
- lib/app/features/optimistic_ui/features/follow/follow_sync_strategy.dart
- lib/app/features/optimistic_ui/features/follow/follow_sync_strategy_provider.r.dart
- lib/app/features/optimistic_ui/features/follow/model/user_follow.f.dart
- lib/app/features/optimistic_ui/features/follow/toggle_follow_intent.dart
- lib/app/features/push_notifications/providers/relay_firebase_app_config_provider.m.dart
- lib/app/features/user/providers/follow_list_provider.r.dart
This PR adds an optimistic UI for follow feature.
https://github.com/user-attachments/assets/3fdef656-9d80-432d-8a3f-afdbea51b8a7
> feat: add optimistic user follow

- lib/app/features/core/providers/env_provider.r.dart
- lib/app/features/feed/reposts/providers/optimistic/post_repost_provider.r.dart
- lib/app/features/optimistic_ui/core/operation_manager.dart
- lib/app/features/optimistic_ui/features/follow/follow_provider.r.dart
- lib/app/features/optimistic_ui/features/language/language_sync_strategy_provider.r.dart
- lib/app/features/optimistic_ui/features/likes/post_like_provider.r.dart
- lib/app/features/user_block/optimistic_ui/block_user_provider.r.dart
- test/app/features/feed/reposts/providers/load_initial_reposts_merge_test.dart
- test/app/features/feed/reposts/providers/optimistic/quote_intent_test.dart
- test/app/features/feed/reposts/providers/optimistic/toggle_repost_race_condition_test.dart
- test/app/features/optimistic_ui/optimistic_test.dart
- test/mocks.dart
This PR adds a config that enables/disabled optimistic ui across the app.
> feat: add optimistic ui on/off config

- lib/app/features/chat/views/components/message_items/message_types/money_message/components/money_message_button.dart
- lib/l10n/app_en.arb
Just replaced "Cancel" with "Cancelled" for Money Request.
ION-3482
> fix: set "Cancelled" label for cancelled 1755

- lib/app/features/components/quick_page_swiper/quick_page_swiper.dart
- lib/app/features/feed/stories/views/components/story_viewer/components/core/cube_page_view.dart
- lib/app/features/video/views/pages/videos_vertical_scroll_page.dart
This PR adds a manual swiper mechanism used for page view to better manage the speed of the swipe animation.
https://github.com/user-attachments/assets/e817a988-956e-420e-b89c-ba6aff8a77f7
> feat: increase vertical videos page swipe speed

- lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart
Reverts ice-blockchain/ion-framework#1842
> Revert "Revert "fix(feed): temporary enable Feed creation without NFT content""

- lib/app/features/wallets/views/pages/wallet_page.dart
Precache tier 1 network icons during "intState" of the WalletPage.
ION-3168
> feat: precache tier 1 network icons

- lib/app/features/user/providers/friends_section_providers.r.dart
- lib/app/features/wallets/views/pages/wallet_page/components/friends/friends_list.dart
Added a debouncer to prevent blinking of the friends section.
ION-3666
> chore: add debouncer for the shouldShowFriendsSection 

- lib/app/features/chat/e2ee/providers/send_chat_message/compress_chat_media_provider.r.dart
- lib/app/features/chat/e2ee/providers/send_chat_message/send_chat_media_provider.r.dart
- lib/app/features/ion_connect/providers/ion_connect_upload_notifier.m.dart
- lib/app/services/compressors/audio_compressor.r.dart
- lib/app/services/compressors/compress_executor.r.dart
- lib/app/services/compressors/image_compressor.r.dart
- lib/app/services/compressors/video_compressor.r.dart
- Cancels compression
- Cancels file upload
ION-3609
> fix: cancel compression and upload for large media

- lib/app/features/wallets/domain/wallet_views/wallet_view_parser.dart
Skip coin in the wallet view, if it in the unknown network.
ION-3715
> fix: skip coin in the unknown network

- lib/app/features/user/pages/profile_page/pages/follow_list_modal/followers_list.dart
- lib/app/features/user/pages/profile_page/pages/follow_list_modal/following_list.dart
- lib/app/features/user/providers/followers_data_source_provider.r.dart
- lib/app/features/user/providers/followers_provider.r.dart
- lib/app/features/user/providers/search_users_provider.r.dart
- packages/ion_identity_client/lib/src/users/ion_identity_users.dart
- packages/ion_identity_client/lib/src/users/search_users_social_profile/data_sources/search_users_social_profile_data_source.dart
- packages/ion_identity_client/lib/src/users/search_users_social_profile/search_users_social_profile_service.dart
this PR changes logic for fetching searched users in following and followers modals
> feat: add followedBy and followerOf query params to search

- lib/app/features/chat/recent_chats/views/components/recent_chat_tile/recent_chat_tile.dart
- lib/app/features/chat/views/components/message_items/message_item_wrapper/message_item_wrapper.dart
- lib/app/features/chat/views/components/message_items/message_types/money_message/money_message.dart
- lib/l10n/app_ar.arb
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
Added new localization texts and provided amount of requested or transferred funds
ION-3616
> feat: Chat → Update titles for payment messages

- build.yaml
- lib/app/features/feed/providers/feed_bookmarks_notifier.r.dart
- lib/app/features/ion_connect/providers/ion_connect_db_cache_notifier.r.dart
- lib/app/features/user/pages/bookmarks_page/bookmarks_page.dart
- lib/app/features/user/providers/relays/user_relays_manager.r.dart
- packages/ion_connect_cache/lib/src/service/ion_connect_cache_service.dart
- packages/ion_connect_cache/lib/src/service/ion_connect_cache_service_drift_impl.d.dart
> fix: cache bugfixes

- lib/app/features/feed/polls/providers/poll_results_provider.r.dart
- lib/app/features/feed/providers/counters/models/replied_events_map.f.dart
- lib/app/features/feed/providers/counters/replied_events_provider.r.dart
Two more providers rebuild optimisation
It was the same issue - unconditional dependency on ionConnectCacheProvider
ION-3502
> fix: optimise poll_result_provider and replied_events_provider

- lib/app/services/media_service/media_encryption_service.m.dart
- lib/app/services/media_service/mime_resolver/mime_resolver.dart
- Using original mime type or try to get one from magic numbers
- Add custom magic numbers resolver for `opus/ogg`
ION-3756
> fix: custom mime types identifier

- lib/app/features/video/views/components/video_thumbnail_preview.dart
> fix: add a ion loading placeholder for trending videos

- lib/app/features/video/views/pages/videos_vertical_scroll_page.dart
- lib/app/features/wallets/views/pages/wallet_page/components/header/wallet_header.dart
> chore: reformat videos scroll page to not exceed line limit

- lib/app/features/user/pages/profile_page/pages/follow_list_modal/followers_list.dart
- lib/app/features/user/providers/followers_provider.r.dart
This PR fixes an issue where load more was not working on followers list modal.
2466
> fix: followers load more

- lib/app/features/auth/hooks/use_referrer_controller.dart
- lib/app/features/auth/views/components/user_data_inputs/general_user_data_input.dart
- lib/app/features/auth/views/components/user_data_inputs/referral_input.dart
- lib/app/features/auth/views/pages/fill_profile/fill_profile.dart
- lib/app/services/referrer/referrer_service.r.dart
- pubspec.lock
- pubspec.yaml
Introduction of Google Play Referral API
The feature takes a referral from Google Play link and uses it to fill referral field on onboarding
ION-3773
> feat: use google play referrer to fill who invited field on onboarding

- lib/app/services/media_service/media_upload_service.dart
Fix gif images processing issue
There was an issue with GIF images. During the scaling it threw the exception, also  FFmpeg wasn't able to handle animated webp images on IOS. As A solution gif images where handled same as videos for creating thumb image.
ION-3804
> fix: take thumbs from gif images in the way we do for videos

- lib/app/features/wallets/views/pages/transaction_details/transaction_details.dart
- `TransactionDetailsPage` now uses CustomScrollView with `shrinkWrap: true` so the sheet sizes to its content and doesn’t add extra bottom space.
- Preserved ScreenBottomOffset and refactored inline UI into small private widgets (e.g., _AssetHeader, _TimelineSection, etc.) for clarity; no functional API changes.
Fixes a bug where the bottom padding caused the bottom sheet to appear almost full-height even when content was short. The dialog now matches the expected compact layout when there aren’t enough fields, and expands/scrolls only when content is long.
ION-3876
Before/After:
/
>  fix(wallets): TransactionDetails bottom-sheet bottom padding; size to content when short

- lib/app/features/feed/notifications/data/database/dao/comments_dao.m.dart
- lib/app/features/feed/notifications/data/repository/comments_repository.r.dart
- lib/app/features/feed/notifications/providers/comments_notifications_provider.r.dart
- lib/app/features/ion_connect/providers/event_backfill_service.r.dart
- lib/app/features/ion_connect/providers/global_subscription.r.dart
- lib/app/features/ion_connect/providers/global_subscription_latest_event_timestamp_provider.r.dart
- lib/app/features/user/providers/account_notifications_sync_provider.r.dart
Several issues were fixed here
Several issues were fixed here
1. mention in article didn't appear in in-app notification
2. post and article quotes didn't appear in notifications
3. on comment notifications tab were other notification together with reply notifications
ION-3865,ION-3849
> fix: in-app notification fixes

- lib/app/features/chat/recent_chats/views/pages/recent_chats_timeline_page/recent_chats_timeline_page.dart
Do not throw if there is no elements
ION-3960
> fix: StateError - Bad state: No element

- lib/app/components/text_editor/utils/mentions_hashtags_handler.dart
- lib/app/features/feed/views/components/overlay_menu/user_info_menu.dart
- lib/app/features/feed/views/pages/feed_page/components/stories/components/story_list_item.dart
- lib/app/features/feed/views/pages/feed_page/components/trending_videos/components/trending_video_author.dart
- lib/app/features/feed/views/pages/who_can_reply_info_modal/who_can_reply_info_modal.dart
- lib/app/features/user/pages/profile_page/components/profile_details/relevant_followers/followed_by_text.dart
- lib/app/features/user/providers/badges_notifier.r.dart
- lib/app/features/user/providers/user_metadata_provider.r.dart
Read Copilot description
ION-3963
> feat: remove sync user metadata provider

- .github/workflows/CI.yaml
- .github/workflows/CICD.yaml
- melos.yaml
Some cache issues still remain
Pub-cache is created on every run of CI and CICD flows
Flutter SKD cache is created on every CI flow run
ION-3834
> fix: CI Flutter cache fix, CI and CICD pub-cache disabling

- packages/ion_screenshot_detector/android/src/main/kotlin/io/ion/app/ion_screenshot_detector/IonScreenshotDetectorPlugin.kt
IllegalStateException
https://sentry.ice.vip/organizations/sentry/issues/1350/?project=4&query=is%3Aescalating&referrer=issue-stream&stream_index=11
https://play.google.com/console/u/0/developers/6531985169641222293/app/4973841958539492300/vitals/crashes/ab0f082fe26a03c7d55bcbf70cf1209f/details?days=60&isUserPerceived=true
Problem
The app was experiencing crashes with IllegalStateException: Unknown URL: content://media/external in the background, specifically in the screenshot detection feature. The error occurred when the ContentObserver tried to query media content that was in an invalid or pending state.
Root Cause
The issue was caused by a race condition in Android's media content lifecycle:
Screenshot taken → Android creates a new media entry with URI like …
> fix: add retry logic and error handling to querying media

- lib/app/features/ion_connect/model/event_reference.f.dart
> fix: incorrect tag input exception

- lib/app/features/optimistic_ui/features/likes/post_like_provider.r.dart
Likes by current user appear with 1 likes counter
Wrong data came from optimistic state. Which was uses as a cache, always initialised and had higher priority then cache.
Optimistic state should be temporary short living till successful sync. Cache should be the primary source of likes data, not optimistic state.
ION-3974
> fix: remove optimisitic state initialisation with likes

- lib/app/features/ion_connect/providers/global_subscription.r.dart
- lib/app/features/ion_connect/providers/global_subscription_latest_event_timestamp_provider.r.dart
Check Copilot description and file comments
ION-4032
> fix: proper fetching logic for encrypted events

- lib/app/features/user_profile/providers/user_profile_sync_provider.r.dart
> fix: load chat metadata in parallel

- lib/app/features/chat/views/components/message_items/message_types/text_message/text_message.dart
Temporarily fix till we figure out how to process it without compute or shared isolates
> fix: disable url preview in text messages

- packages/ion_identity_client/lib/src/networks/services/get_estimate_fees/models/network_fee.f.freezed.dart
- packages/ion_identity_client/lib/src/networks/services/get_estimate_fees/models/network_fee.f.g.dart
- packages/ion_identity_client/lib/src/users/update_user_social_profile/models/user_social_profile_data.f.g.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_assets/models/wallet_asset.f.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_assets/models/wallet_asset.f.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_assets/models/wallet_asset.f.g.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/transfer_request_body.f.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/get_wallet_transfer_requests/models/transfer_request_body.f.g.dart
- packages/ion_identity_client/lib/src/wallets/services/make_transfer/models/transfer.f.dart
- packages/ion_identity_client/lib/src/wallets/services/make_transfer/models/transfer.f.freezed.dart
- packages/ion_identity_client/lib/src/wallets/services/make_transfer/models/transfer.f.g.dart
According to the screenshot, this field can be nullable.
ION-4079
> fix: wallet parsing issue

- packages/ion_screenshot_detector/android/src/main/kotlin/io/ion/app/ion_screenshot_detector/IonScreenshotDetectorPlugin.kt
Fix crash because of NullPointerException in IonScreenshotDetectorPlugin
> fix: crash in IonScreenshotDetector

- lib/app/features/chat/recent_chats/views/pages/recent_chats_timeline_page/recent_chats_timeline_page.dart
- lib/app/features/search/providers/chat_search/chat_local_user_search_provider.r.dart
- lib/app/features/search/providers/chat_search/chat_messages_search_provider.r.dart
- lib/app/features/search/views/pages/chat/chat_advanced_search_page/components/chat_advanced_search_all/chat_advanced_search_all.dart
- lib/app/features/search/views/pages/chat/chat_advanced_search_page/components/chat_advanced_search_people/chat_advanced_search_people.dart
- lib/app/features/search/views/pages/chat/components/chat_search_results.dart
Improvements for search in chat and for scroll in chat list 
ION-3966,ION-3984
> fix: chat scroll jumps

- lib/app/features/wallets/domain/coins/transfer_factory.dart
- lib/app/features/wallets/providers/transaction_provider.r.dart
- lib/app/features/wallets/views/pages/import_token_page/providers/import_token_notifier_provider.r.dart
1. Save the unknown token to the DB during importing.
2. Avoid math operations during coin amount conversion (Used string manipulation approach).
3. Add a wallet view name to the transaction data.
ION-4107
> fix: transactions with imported token

- lib/app/features/chat/e2ee/providers/chat_message_media_path_provider.r.dart
- lib/app/features/chat/e2ee/providers/send_chat_message/send_chat_media_provider.r.dart
- lib/app/features/chat/views/components/message_items/message_types/visual_media_message/visual_media_content.dart
> feat: chat memory optimisations
