lib/app/features/auth/providers/auth_provider.dart
lib/app/features/auth/views/pages/discover_creators/discover_creators.dart
lib/app/features/components/follow_user_button/follow_user_button.dart
lib/app/features/feed/feed_search/providers/feed_search_filters_provider.dart
lib/app/features/feed/feed_search/providers/feed_search_history_provider.dart
lib/app/features/feed/providers/feed_current_filter_provider.dart
lib/app/features/user/pages/pull_right_menu_page/components/profile_details/profile_details.dart
lib/app/features/user/pages/switch_account_modal/components/accounts_list/account_tile.dart
lib/app/features/user/providers/user_following_provider.dart
lib/app/features/user/providers/user_metadata_provider.dart
lib/app/features/wallet/providers/wallet_user_preferences/user_preferences_selectors.dart
lib/app/features/wallet/views/pages/nfts_sorting_modal/components/sorting_button/sorting_button.dart
lib/app/features/wallet/views/pages/wallet_page/components/balance/balance.dart
lib/app/features/wallet/views/pages/wallet_page/components/nfts/nfts_header_layout_action.dart
lib/app/features/wallet/views/pages/wallet_page/components/tabs/tabs_header_hide_action.dart

This PR aligns name of the provider with the rest of the code.
- Rename provider `currentUserIdSelector -> currentIdentityKeyNameSelector`
- Change it's return type to be nullable
- Update dependent code to use the new name and the return nullable value
Logout happens immediately
https://github.com/user-attachments/assets/44a38c6b-9f38-467c-84b3-b4fc25290fb4

chore(auth provider): rename currentUserIdSelector -> currentIdentityKeyNameSelector

---

lib/app/features/auth/views/components/identity_key_name_input/identity_key_name_input.dart
lib/app/features/auth/views/pages/get_started/login_form.dart
lib/app/features/auth/views/pages/sign_up_passkey/sign_up_passkey_form.dart
packages/ion_identity_client/lib/src/auth/data_sources/login_data_source.dart
packages/ion_identity_client/lib/src/auth/data_sources/register_data_source.dart
packages/ion_identity_client/lib/src/auth/result_types/login_user_result.dart
packages/ion_identity_client/lib/src/auth/result_types/register_user_result.dart

Improves error handling and displays error messages in the login and registration forms.
- **IdentityKeyNameInput**: Added `errorText` prop to show validation errors.
- **LoginForm & SignUpPasskeyForm**: Pass `errorText` to `IdentityKeyNameInput`.
- **LoginDataSource & RegisterDataSource**: Better network error handling (e.g., account deactivated, invalid code).
- **Failure types**: Added new failure cases with clearer error messages.

feat(ion identity client): improve errors for register and login

---

lib/app/extensions/riverpod.dart
lib/app/features/core/providers/env_provider.dart
lib/app/features/core/views/pages/error_modal.dart
lib/app/services/ion_identity/ion_identity_provider.dart
lib/l10n/app_en.arb

This PR implements the modal sheet to display general errors in the app.
[Design](https://www.figma.com/design/3TnZngoFeklOVC8TexlR1D/%F0%9F%A7%8A-ICE-Cloud?node-id=42325-154130&t=DxnabsBFUzBEk15G-4)
1. Added `ErrorModal` widget.
2. Replaced `AlertDialog` with `ErrorModal` in the `displayErrors` method.
3. Added `SHOW_DEBUG_INFO` flag.
4. Improved `get` method so it can read boolean env variables.

feat: General error modal dialog UI

---

lib/app/features/chat/messages/views/components/forwarded_message_info/forwarded_message_info.dart
lib/app/features/chat/messages/views/components/message_types/emoji_message/emoji_message.dart
lib/app/features/chat/messages/views/components/message_types/text_message/text_message.dart
lib/app/features/chat/messages/views/components/replied_message_info/replied_message_info.dart
lib/app/features/chat/messages/views/pages/messages_page.dart
lib/app/features/chat/recent_chats/views/components/recent_chat_tile/recent_chat_tile.dart
lib/l10n/app_en.arb

Added visual indicators for forwarded and replied messages in chat, including sender info and message previews.
N/A
https://www.figma.com/design/3TnZngoFeklOVC8TexlR1D/%F0%9F%A7%8A-ICE-Cloud?node-id=43823-115687&m=dev

feat: Add forwarded and replied message indicators in chat

---

lib/app/features/feed/providers/feed_stories_data_source_provider.dart
lib/app/features/feed/stories/providers/story_viewing_provider.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/core.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/cube_page_view.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/stories_swiper.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/story_content.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/story_viewer_action_buttons.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/user_story_page_view.dart
lib/app/features/feed/stories/views/components/story_viewer/components/header/story_viewer_header.dart
lib/app/features/feed/stories/views/components/story_viewer/components/progress/story_progress_bar_container.dart
lib/app/features/feed/stories/views/components/story_viewer/components/viewers/image_story_viewer.dart
lib/app/features/feed/stories/views/components/story_viewer/components/viewers/story_viewer_content.dart
lib/app/features/feed/stories/views/components/story_viewer/components/viewers/video_story_viewer.dart
lib/app/features/feed/stories/views/pages/story_viewer_page.dart
lib/app/features/feed/views/pages/feed_page/components/stories/components/current_user_story_list_item.dart
lib/app/features/feed/views/pages/feed_page/components/stories/components/story_list.dart
lib/app/router/feed_routes.dart
pubspec.lock
pubspec.yaml

- fix ION-490 - The user’s profile button on the story screen leads to the single hardcoded profile
- fix ION-375 - after clicking on the user’s stories, all the stories playback starts from the first stories in the list
- simplify the logic of the stories viewing
- remove the `cube_transition_plus` library and move a class from that one to the project to resolve a limitation of the library

fix: logic of the viewing stories

---

ios/Podfile.lock
lib/app/features/chat/messages/views/pages/messages_page.dart
lib/app/features/feed/create_post/views/pages/compress_test_page.dart
lib/app/services/audio_wave_playback_service/audio_wave_playback_service.dart
lib/app/services/media_service/media_compress_service.dart
pubspec.lock
pubspec.yaml

- Added Opus audio codec compression functionality
- Implemented WAV audio compression
- Streamlined video/image compression with FFmpeg Kit direct integration
- Removed deprecated compression methods and dependencies
- WAV conversion is required as audio waveforms cannot be generated from Opus format

feat: support opus codec

---

lib/app/extensions/riverpod.dart
lib/app/features/auth/views/pages/recover_user_page/components/recovery_creds_step.dart
lib/app/features/auth/views/pages/recover_user_page/components/twofa_options_step.dart
lib/app/features/auth/views/pages/recover_user_page/recover_user_page.dart
lib/app/features/protect_account/backup/providers/recover_user_action_notifier.dart
lib/app/features/protect_account/secure_account/providers/selected_two_fa_types_provider.dart
packages/ion_identity_client/lib/ion_identity.dart
packages/ion_identity_client/lib/src/auth/ion_identity_auth.dart
packages/ion_identity_client/lib/src/auth/services/recover_user/data_sources/recover_user_data_source.dart
packages/ion_identity_client/lib/src/auth/services/recover_user/recover_user_service.dart
packages/ion_identity_client/lib/src/core/types/ion_exception.dart
packages/ion_identity_client/lib/src/signer/passkey_signer.dart

This PR does 2 things:
- splits recoverUser into 2 methods (initRecover and completeRecover) to let the app show Passkey prompt properly (most of the changes are related to this)
- adds 2FA options count for recover flow (only few files changed)

feat(ion identity client): improve recover user flow

---

.github/PULL_REQUEST_TEMPLATE.md

Remove the optional Figma link section from the pull request template.
N/A

chore: remove figma link section from PR template

---

lib/l10n/app_en.arb

fix: auth key text warning

---

lib/app/components/inputs/search_input/search_input.dart
lib/app/features/dapps/views/categories/apps/apps.dart
lib/app/features/dapps/views/components/categories_collection/categories_collection.dart
lib/app/features/dapps/views/pages/dapps.dart
lib/app/features/dapps/views/pages/dapps_list/dapps_list.dart
lib/app/features/search/views/components/search_navigation/search_navigation.dart
lib/app/features/search/views/pages/dapps_simple_search_page/dapps_simple_search_page.dart
lib/app/router/app_routes.dart
lib/app/router/dapps_routes.dart
lib/l10n/app_en.arb

dApps UI bugs fixes
The list of bugs
1. “Search here for dApps” text displayed on dapps “Search” screen instead of “Search here for dApps, categories…”
2. “Back” button is missing on dapps “Search” screen.
3. “Cancel” button is present on dapps “Search” screen.
4. “Search” bar is present on dapps “Highest ranked” screen
Fixed pages

fix: UI bugs in the dApps

---

lib/app/features/wallet/views/pages/wallet_scan/wallet_scan_modal_page.dart

Removes top and bottom padding on qr scanner page.

fix: qr scanner padding

---

lib/app/features/protect_account/authenticator/views/pages/setup_authenticator/authenticator_setup_page.dart

fix: remove title and progress bar from authenticator setup page modal

---

lib/app/features/protect_account/phone/views/components/countries/select_country_page.dart

fix:  add missing close button to select country page modal

---

lib/app/features/protect_account/backup/views/pages/create_recover_key_page/create_recovery_key_page.dart
lib/l10n/app_en.arb

fix: add error handling for recovery keys modal when passkeys validation fails

---

lib/app/features/protect_account/backup/views/components/recovery_key_option.dart

fix: change overflow three dots text alignment to center on recovery key options

---

.gitignore
lib/app/features/feed/stories/providers/story_camera_provider.c.dart
lib/app/features/feed/stories/views/components/story_capture/camera/idle_camera_preview.dart
lib/app/features/feed/stories/views/components/story_capture/components.dart
lib/app/features/feed/stories/views/components/story_capture/controls/story_gallery_button.dart
lib/app/features/feed/stories/views/components/story_viewer/components/share/story_share_modal.dart
lib/app/features/feed/stories/views/pages/story_preview_page.dart
lib/app/features/feed/stories/views/pages/story_record_page.dart
lib/app/features/gallery/providers/gallery_provider.c.dart

- Disable `Banuba editor` due to token expiration
- Add a close button to the bottom sheet for story-sharing
- Update the title in the story-sharing bottom sheet
- Display the latest gallery preview image in the custom camera

fix: display a gallery preview image in the create story flow

---

lib/app/features/feed/stories/views/components/story_viewer/components/core/story_content.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/story_gesture_handler.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/story_input_field.dart

fix: prevent long text from overflowing by enabling line wrapping

---

pubspec.lock
pubspec_overrides.yaml

This PR adds a fix for iOS to be able to use another device to login.
Changes in the passkeys_ios: https://github.com/corbado/flutter-passkeys/pull/83

fix(passkey auth): override passkeys_ios with custom fix

---

lib/app/features/protect_account/components/delete_twofa_input_step.dart
lib/app/features/protect_account/phone/views/pages/delete_phone/components/delete_phone_select_options_step.dart

fix: correctly display error modal on phone number verification delete page

---

lib/app/extensions/theme_data.dart
lib/app/theme/app_colors.dart
lib/app/theme/app_text_themes.dart

Add default `colors` and `textThemes` to avoid force unwrap

feat: add default colors, textThemes

---

lib/app/components/list_item/list_item.dart
lib/app/components/list_item/variants/list_item_user.dart
lib/app/features/feed/views/components/post/post.dart
lib/app/features/feed/views/components/user_info/user_info.dart

If user presses on red area, it should open profile
if user presses on any other area (in blue one for example), it  should open post page. because right now the white area on right of the profile opens the profile,  and is confusing
Pressing on the quoted post (in any position, including the author of quoted post), should open the quoted post page
Please, note, that `GestureDetector`s were added for each user artifact (name, username, avatar) separately in the `UserInfo` to avoid corruption of other `ListItem.user` usages, since this widget/constructor is used in many places.
https://github.com/user-attachments/assets/f62c2ced-7019-4fc6-ab4e-1c3ae3d84344

fix: feed post gesture detecting issue

---

lib/app/features/feed/views/components/post/components/post_body/post_body.dart

Reorders post content to display text before media and adds 10dp top spacing between them.
N/A

feat: show post text above the media in post feed

---

lib/app/features/protect_account/components/delete_twofa_initial_scaffold.dart
lib/app/features/protect_account/components/delete_twofa_input_step.dart
lib/app/features/protect_account/components/delete_twofa_select_options_step.dart
lib/app/features/protect_account/components/delete_twofa_step_scaffold.dart

https://github.com/user-attachments/assets/8f6ebadf-10cd-4fc6-a730-ec08fd8f93dc

fix: make delete 2fa pages scrollable to fit the whole content in case of many 2fa options set up

---

lib/app/features/auth/views/pages/create_local_creds_prompt_dialog/create_local_creds_prompt_dialog.dart
lib/app/features/auth/views/pages/get_started/login_form.dart

fix: remove manual navigation from login form

---

lib/app/features/feed/data/models/entities/article_data.c.dart
lib/app/features/feed/data/models/entities/post_data.c.dart

fix: return null WhoCanReplyEventSetting during post/article creation if all tag values are null

---

lib/app/features/auth/views/pages/recover_user_twofa_page/components/twofa_option_selector.dart
lib/app/features/auth/views/pages/recover_user_twofa_page/components/twofa_options_selector_button.dart

fix: disable two fa options dropdown when there are no options available

---

lib/app/features/auth/providers/onboarding_complete_notifier.c.dart
lib/app/features/chat/components/following_user_list/following_user_list.dart
lib/app/features/chat/components/searched_user_list/searched_user_list.dart
lib/app/features/chat/providers/user_chat_relays_provider.c.dart
lib/app/features/chat/providers/users_data_source_provider.c.dart
lib/app/features/chat/views/pages/new_chat_modal/new_chat_modal.dart
lib/app/router/main_tabs/main_tab_navigation.dart

- Implemented two list views with backend integration: Following users list (default view), Searched users list with pagination
- Implemented dynamic chat relay management that mirrors user's main relays

feat: render user list for new chat modal

---

lib/app/features/protect_account/authenticator/views/pages/delete_authenticator/components/delete_authenticator_input_step.dart
lib/app/features/protect_account/components/delete_twofa_input_step.dart
lib/app/features/protect_account/components/delete_twofa_step_scaffold.dart

fix: improve 2fa delete input step padding

---

lib/app/features/feed/views/pages/article_details_page/components/article_details_header.dart

Fixed an issue where the "Follow" button in the article feed view was inactive and users were unable to interact with it. The button is now properly responding to click events and allows users to follow/unfollow article author as expected.
N/A
N/A

fix: Enable follow button interaction in article feed view

---

ios/Podfile.lock
lib/app/features/gallery/providers/camera_provider.c.dart
lib/app/services/media_service/banuba_service.c.dart
lib/app/services/media_service/media_service.c.dart
pubspec.lock
pubspec.yaml

This PR fixes an issue where media (photos/videos) were not displaying correctly in the Android story preview screen. The root cause was identified as improper file path handling on Android devices and missing MIME type validation for media files. 
Related issue: https://github.com/flutter/flutter/issues/148335
- Added `mime: ^2.0.0` for proper media type detection
- Added `uri_to_file: ^1.0.0` for Android Content URI conversion
- Updated `photo_manager` to `3.6.3` 
N/A

fix: missing media on android story preview screen

---

lib/app/features/chat/providers/conversation_management_provider.c.dart
lib/app/features/chat/providers/conversation_message_actions_provider.c.dart
lib/app/features/chat/providers/conversation_message_management_provider.c.dart
lib/app/features/chat/providers/fetch_conversation_provider.c.dart
lib/app/features/chat/recent_chats/providers/conversations_provider.c.dart
lib/app/services/database/conversation_db_service.c.dart
lib/app/services/database/ion_database.c.dart
test/services/database/database_test.dart

- Providers to manage conversation actions (mark as sent, read, deleted, bookmark, add reaction)
- Refactoring (seperated DB conversation service from DB file)
- Delete conversation method

feat: delete/react/bookmark message

---

lib/app/features/feed/views/components/text_editor/text_editor_preview.dart
lib/app/features/feed/views/components/text_editor/utils/quill.dart

When handling URLs in the preview editor, the current implementation allows for editing which can lead to incorrect URL processing and potential issues with link navigation.
N/A
N/A

fix: set ready only as true of the preview editor to handle URLs correctly

---

lib/app/features/chat/views/pages/chat_main_modal/chat_main_modal_page.dart
lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart
lib/app/router/base_route_data.dart
lib/app/router/components/sheet_content/main_modal_content.dart
lib/app/router/components/sheet_content/sheet_content.dart
pubspec.lock
pubspec.yaml

This PR:
- upgrades smooth_sheets library to the latest version which contains a fix for janks during modals swipe to dismiss
- improves swipe to dismiss experience by changing required swipe distance and velocity
- sets all main modals scrollviews as non scrollable to allow swipe to dismiss by swiping the content of the modal

fix: increase main modal performance, fix janks when swipe to dismiss

---

lib/app/features/feed/create_post/views/components/post_submit_button/post_submit_button.dart
lib/app/features/feed/create_post/views/components/reply_input_field/reply_input_field.dart

Fixes a problem where pop to feed happens after replying to a post inside post details page using text field at the bottom of the page.

fix: preventing post details page to be popped after reply is added using bottom textfield on that page

---

lib/app/features/components/entities_list/components/bookmark_button/bookmark_button.dart
lib/app/features/feed/data/models/entities/post_data.c.dart
lib/app/features/feed/providers/bookmarks_notifier.c.dart
lib/app/features/feed/views/components/article/article.dart
lib/app/features/feed/views/pages/post_details_page/post_details_page.dart

- Adding bookmark button to post details page (was missing there)
- Add logic that distinguishes between stories/videos/regular posts to add them to correct bookmark group. 
- Merge bookmark button's constructors into one
- Refactor toggleBookmark method inside bookmark notifier for better clarity

fix: add support for stories and videos bookmarks, refactor bookmarking method for better clarity

---

lib/app/features/core/providers/init_provider.c.dart
lib/app/features/wallet/components/coin_sync/coins_sync_wrapper.dart
lib/app/features/wallet/data/coins/database/coins_database.c.dart
lib/app/features/wallet/data/coins/database/coins_repository.c.dart
lib/app/features/wallet/data/coins/database/coins_table.c.dart
lib/app/features/wallet/data/coins/database/duration_type.dart
lib/app/features/wallet/data/coins/domain/coin_initializer.c.dart
lib/app/features/wallet/data/coins/domain/coin_sync_service.c.dart
lib/app/features/wallet/data/coins/domain/coins_mapper.dart
lib/app/services/ion_identity/ion_identity_provider.c.dart
lib/app/services/logger/config.dart
lib/app/services/storage/local_storage.c.dart
lib/main.dart
packages/ion_identity_client/lib/ion_identity.dart
packages/ion_identity_client/lib/src/coins/ion_identity_coins.dart
packages/ion_identity_client/lib/src/coins/models/coin.c.dart
packages/ion_identity_client/lib/src/coins/models/coin.c.freezed.dart
packages/ion_identity_client/lib/src/coins/models/coin.c.g.dart
packages/ion_identity_client/lib/src/coins/models/coins_response.c.dart
packages/ion_identity_client/lib/src/coins/models/coins_response.c.freezed.dart
packages/ion_identity_client/lib/src/coins/models/coins_response.c.g.dart
packages/ion_identity_client/lib/src/coins/services/data_sources/get_coins_data_source.dart
packages/ion_identity_client/lib/src/coins/services/get_coins_service.dart
packages/ion_identity_client/lib/src/core/service_locator/clients_service_locator.dart
packages/ion_identity_client/lib/src/core/service_locator/ion_identity_clients/coin_client_service_locator.dart
packages/ion_identity_client/lib/src/core/service_locator/network_service_locator.dart
packages/ion_identity_client/lib/src/ion_identity_client.dart
packages/ion_identity_client/lib/src/ion_identity_config.dart
packages/ion_identity_client/lib/src/signer/dtos/user_registration_challenge.c.g.dart

- This PR adds coins sync once per 24 hours
- Coins are saved to the DB
- The synchronization happens only if a user is logged in and the app is in resumed state
- The timer starts in `CoinsSyncWrapper`, which wraps the `MateriaApp`
- The `ion_identity_client` package is also updated to provide API interaction code
- Also, this PR adds code to load the initial state of the coins from assets

feat: Add sync coins once per 24 hours

---

lib/app/features/feed/views/pages/notifications_history_page/components/notification_item/notification_item.dart

Adds missing padding on comments tab in notifications page

fix: use correct padding for notifications comments tab

---

packages/ion_identity_client/lib/src/core/network/utils.dart

Add an empty string handing to the `parseJsonObject` method.

fix: getCoins exception with empty string response

---

lib/app/features/user/model/user_notifications_type.dart
lib/app/features/user/pages/profile_page/components/profile_details/profile_actions/profile_actions.dart
lib/app/features/user/pages/profile_page/pages/account_notifications_modal/account_notifications_modal.dart
lib/app/features/user/pages/profile_page/providers/user_notifications_provider.c.dart

Choosing `none` should unmark the rest of the options.
`None` can’t be chosen with any other option together.
`None` should be chosen by default for all other users.
https://github.com/user-attachments/assets/efbbb87b-e6a7-49ca-98c7-08ba34abec01

fix: add multiselection for the account notifications

---

lib/app/components/scroll_view/load_more_builder.dart
lib/app/features/auth/views/pages/discover_creators/discover_creators.dart
lib/app/features/user/pages/profile_page/components/tabs/tab_entities_list.dart
lib/app/features/user/pages/user_picker_sheet/components/follower_users.dart
lib/app/features/user/pages/user_picker_sheet/components/searched_users.dart

fix: remove listener for scroll metrics causing too many loadMores

---

lib/app/features/feed/create_post/views/components/post_submit_button/post_submit_button.dart
lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart

automatically closing the modal sheets after successful video post-creation

fix: close modal stack after successful video post creation

---

lib/app/features/components/entities_list/entities_list.dart
lib/app/features/user/providers/block_list_notifier.c.dart

This PR introduces a logic to: 
1. hide any entities (posts/articles/reposts) that are created by users we block 
2. hide any entities (posts/reposts) that quote/repost other entities created by users we block
Example:
User A creates a post, user B creates the post by quoting a post from user A. Now if we block user A, we should also not see post from user B, because it contains a post from blocked user A. Any Other posts user B creates that don't contain any content from blocked user A should be still visible.

feat: add blocked entities hiding on all levels

---

lib/app/features/wallet/views/pages/wallet_page/components/contacts/contacts_list_header.dart
lib/l10n/app_en.arb

A simple change of a string resource on Wallets page

fix: rename Contacts section title to Friends

---

lib/app/features/feed/data/models/entities/event_count_request_data.c.dart
lib/app/features/feed/data/models/entities/event_count_result_data.c.dart
lib/app/features/ion_connect/providers/ion_connect_notifier.c.dart
lib/app/features/user/pages/profile_page/profile_page.dart
lib/app/features/user/providers/followers_count_provider.c.dart

feat: followers counter flow

---

lib/app/features/auth/views/components/recovery_keys_input_container/recovery_keys_input_container.dart
lib/app/features/auth/views/pages/recover_user_page/components/recovery_creds_step.dart
lib/app/features/auth/views/pages/recover_user_page/recover_user_success_page.dart
lib/app/features/auth/views/pages/restore_menu/restore_menu.dart

This PR adds a missing AuthFooter widget to Restore identity key pages. It also slightly alters a restore button position.

fix: add missing auth footer to recovery pages

---

lib/app/features/components/entities_list/entities_list.dart
lib/app/features/settings/views/blocked_users_modal.dart
lib/app/features/user/providers/block_list_notifier.c.dart

This issue is related to blocking. When a feed cell is about to be rendered, we watch the provider to check if the author is blocked/blocking to determine if we want to show the cell. The default value inside cell is `true`, so that when the provider is still loading, we don’t show the cell. Later, after the provider is loaded and it returns `false`, we know that the author is not blocked/blocking and we show the cell. 
Then, when user scrolls through the feed, some of the cells are getting out of the viewport, they are getting disposed of and their block checking provider is getting disposed, because nothing else is listening to it.
Now, when user scrolls back, these cells try to render again. Provider was disposed, so it is recreated and starts loading. When it’s loading, we use the …

fix: feed scroll to top on scroll up

---

packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/short_wallet_view.c.dart
packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/short_wallet_view.c.freezed.dart
packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/short_wallet_view.c.g.dart
packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view.c.dart
packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view.c.freezed.dart
packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view.c.g.dart

It turns out that `symbolGroup` can be null, so we need to handle that case.

fix: nullable symbolGroup handling

---

lib/app/extensions/go_router_state.dart
lib/app/router/components/sheet_content/main_modal_content.dart
lib/app/router/main_tabs/main_tab_navigation.dart

- Replace go() calls (which replaced the entire stack) with push() and pop() to properly open and close the main modal.
- Update isMainModalOpen to check the full URI instead of matchedLocation, ensuring we detect the /main-modal suffix correctly.
- This preserves the existing navigation stack and prevents multiple copies of the same modal from being pushed.

fix: main modal navigation

---

ios/Podfile.lock
lib/app/features/auth/views/pages/two_fa/twofa_input_step.dart
lib/app/features/protect_account/authenticator/views/pages/setup_authenticator/authenticator_setup_instructions_page.dart
lib/app/features/protect_account/common/two_fa_utils.dart
lib/app/features/protect_account/components/delete_twofa_input_step.dart
lib/app/features/protect_account/email/views/pages/setup_email/email_setup_confirm_page.dart
lib/app/features/protect_account/email/views/pages/setup_email/email_setup_input_page.dart
lib/app/features/protect_account/phone/views/pages/setup_phone/phone_setup_confirm_page.dart
lib/app/features/protect_account/phone/views/pages/setup_phone/phone_setup_input_page.dart
lib/app/features/protect_account/secure_account/providers/delete_twofa_notifier.c.dart
lib/app/features/protect_account/secure_account/providers/request_twofa_code_notifier.c.dart
lib/app/features/protect_account/secure_account/providers/two_fa_signature_notifier.c.dart
lib/app/features/protect_account/secure_account/providers/two_fa_signature_wrapper_notifier.c.dart
lib/app/features/protect_account/secure_account/views/components/two_fa_signature_wrapper.dart
lib/app/features/protect_account/secure_account/views/pages/secure_account_options_page.dart
lib/app/router/components/app_router_builder.dart
packages/ion_identity_client/lib/src/auth/ion_identity_auth.dart
packages/ion_identity_client/lib/src/auth/services/twofa/data_sources/twofa_data_source.dart
packages/ion_identity_client/lib/src/auth/services/twofa/twofa_service.dart
packages/ion_identity_client/lib/src/core/types/ion_exception.dart

This PR introduces a reactive two fa requests signer, which only initiates a signing flow when a server error about invalid signature is returned.

feat: 2FA reactive signer

---

lib/app/features/user/providers/should_show_friends_selector_provider.c.dart
lib/app/features/wallets/views/pages/wallet_page.dart

This PR hides Friends section on Wallet page if a user has <3 (less than 3) friends.

fix(wallet): show friends only if more than 3

---

lib/app/features/wallets/views/components/wallet_tile.dart

Closes the modal when a user selects a wallet

fix(wallet): close modal on wallet selected

---

lib/app/features/feed/views/pages/feed_page/components/stories/stories.dart

Fix Stories bottom divider height on feed to match other feed cells.

fix: stories section bottom divider height

---

.gitignore
lib/app/features/core/providers/main_wallet_provider.c.dart
lib/app/features/core/providers/wallets_provider.c.dart
lib/app/features/wallets/data/coins/database/coins_dao.c.dart
lib/app/features/wallets/data/coins/repository/coins_repository.c.dart
lib/app/features/wallets/domain/coins/coins_service.c.dart
lib/app/features/wallets/domain/wallet_views/wallet_views_service.c.dart
lib/app/features/wallets/model/network.dart
lib/app/features/wallets/providers/coins_by_filters_provider.c.dart
lib/app/features/wallets/providers/nfts_provider.c.dart
lib/app/features/wallets/views/pages/coins_flow/network_list/network_list_view.dart
lib/app/features/wallets/views/pages/coins_flow/receive_coins/providers/wallet_address_notifier_provider.c.dart

1. Replace `getCoinsBySymbolGroup` with `getCoinsByFilters` to use the different number of filters in the future.
2. Commented receive NFTs call to avoid 404 response in the logs, since we use mocked data in any way.
3. Added ION testnet to networks.
4. Refactored wallets provider, so now it can handle added wallet without reloading.

fix: receive coins filtering

---

lib/app/features/chat/database/conversation_database.c.dart
lib/app/features/chat/database/conversation_db_service.c.dart
lib/app/features/chat/messages/providers/chat_messages_provider.c.dart
lib/app/features/chat/providers/conversation_message_actions_provider.c.dart
lib/app/features/chat/providers/e2ee_conversation_management_provider.c.dart
lib/app/features/chat/providers/fetch_conversation_provider.c.dart
lib/app/features/chat/recent_chats/providers/conversation_metadata_provider.c.dart
test/app/features/chat/database/conversation_database_test.dart

In order to support sent/received/read statuses of E2E messages we need separate table to write message delivery statuses to each participant

feature: Conversation messages status table

---

lib/app/features/feed/views/components/toolbar_buttons/toolbar_send_button.dart

fix: remove onTap in toolbar send button when disabled

---

lib/app/features/auth/views/pages/recover_user_page/recover_user_page.dart
lib/app/features/auth/views/pages/two_fa/twofa_input_step.dart

This PR disabled automatic 2fa code request on user recover page and on login page. It should be initiated by the button tap

fix: disable automatic code request on recover user page

---

.github/workflows/CICD.yaml

Updates GitHub Actions workflow to use flutter version from pubspec.yaml file for consistent versioning across CI/CD pipeline.
N/A

fix: use project's flutter version on CI/CD pipeline

---

lib/app/features/user/pages/profile_page/pages/request_coins_form_modal/request_coins_form_modal.dart
lib/app/features/user/pages/profile_page/pages/select_coin_modal/select_coin_modal.dart
lib/app/features/user/pages/profile_page/pages/select_network_modal/select_network_modal.dart
lib/app/features/user/pages/profile_page/pages/send_coins_form_modal/send_coin_form_modal.dart
lib/app/features/wallets/providers/coins_provider.c.dart
lib/app/features/wallets/views/components/coin_networks_list/coin_network_item.dart
lib/app/features/wallets/views/components/coin_networks_list/coin_networks_list_view.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/buttons/coin_amount_input.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/buttons/coin_id_button.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart
lib/app/router/profile_routes.dart

This PR fixes an issue for a dialog `SelectNetworkModal`.
What was the issue: `coinInWalletByIdProvider(ref, coinId)` actually looked for a coin by _abbreviation_, not _id_.
The main fix is in the `coins_provider.c.dart`. All other code is just a renaming to make it look more consistent.

fix: send funds network selection

---

lib/app/features/chat/e2ee/views/components/one_to_one_messages_list.dart
lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar_initial.dart

- Prevent enter/space at the beginning of the message 
- After entering text and then trying to select it, it deletes everything
- the text field should extend to a maximum 5 lines, and then scroll should be available inside (like whatsapp)
- Change position of the attachment file icon
- When user send a message, scroll automatically to show it
- Hide camera icon when user type a text
https://github.com/user-attachments/assets/fb5d49e0-7eaa-465a-a109-3594e628ce11

fix: chat text field issues

---

lib/app/features/auth/views/components/identity_key_name_input/identity_key_name_input.dart

Change keyboard type for identity key name field to make it possible to type symbols.
Before:
After:

fix: change keyboard type for identity key name

---

lib/app/components/text_editor/components/custom_blocks/text_editor_code_block/text_editor_code_block.dart
lib/app/components/text_editor/components/custom_blocks/text_editor_poll_block/text_editor_poll_block.dart
lib/app/components/text_editor/components/custom_blocks/text_editor_separator_block/text_editor_separator_block.dart
lib/app/components/text_editor/components/custom_blocks/text_editor_single_image_block/text_editor_single_image_block.dart
lib/app/components/text_editor/hooks/use_quill_controller.dart
lib/app/components/text_editor/text_editor.dart
lib/app/components/text_editor/text_editor_preview.dart
lib/app/features/feed/create_article/views/pages/create_article_modal/create_article_modal.dart
lib/app/features/feed/create_post/views/components/reply_input_field/reply_input_field.dart
lib/app/features/feed/create_post/views/pages/create_post_modal/hooks/use_post_quill_controller.dart
lib/main.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

This PR upgrades Quill dependency to 11.0.0 and fixes all the breaking changes, ensuring everything works.
It should be merged in addition to: https://github.com/ice-blockchain/markdown_quill/pull/1
https://github.com/user-attachments/assets/2e8e0a41-0569-4680-9760-70e04a2399e4

fix: upgrade quill to 11, fix link popup menu popping the entire post/article create flow

---

lib/app/features/chat/community/channel/views/pages/channel_page/channel_messaging_page.dart
lib/app/features/chat/e2ee/views/pages/group_mesages_page.dart
lib/app/features/chat/e2ee/views/pages/one_to_one_messages_page.dart
lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/recording_overlay.dart
lib/app/features/chat/views/pages/chat_learn_more_modal/chat_learn_more_modal.dart

iInstead of applying a custom bottom padding based on the device’s bottom inset, the chat bar should respect the safe area and be rendered above it.
N/A

fix: system phone navigation is present on the chat window

---

lib/app/features/core/providers/init_provider.c.dart
lib/app/features/wallets/domain/coins/coins_sync_service.c.dart
lib/app/features/wallets/providers/coins_sync_provider.c.dart
lib/app/utils/functions.dart

The issue was pretty complex:
- `CoinsSync` provider got disposed because it was read, not watched (changed to `ref.listen`)
- There was exception because `CoinsSync` provider was initialized at the same time as `authProvider` (moved to a later stage at `initProvider`)
- Backend changed a few things on their side too

fix: coins sync

---

lib/app/features/user/providers/block_list_notifier.c.dart

After latest changes related to making most of the providers sync, the issue previously related to blocking provider is no longer reproducable, hence the provider can be brought back to life.

fix: enable isPostChildBlockedOrBlocking provider

---

lib/app/components/inputs/text_input/components/paste_suffix_button.dart
lib/app/features/wallets/views/pages/import_token_page/components/import_token_form.dart
lib/app/features/wallets/views/pages/import_token_page/components/token_already_exists_dialog.dart
lib/app/features/wallets/views/pages/import_token_page/import_token_page.dart
lib/app/services/clipboard/clipboard.dart
lib/l10n/app_en.arb

Consider reviewing this PR by commits (each commits fixes an issue)
This PR contains the following changes:
- "token already exists" dialog: changed button text, title and description
- added "paste" button for address text field
- "import" button is now disabled if the form is invalid (selectedNetwork == null || address.isEmpty)

fix: import token page issues

---

lib/app/features/feed/stories/providers/story_viewing_provider.c.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/story_viewer_action_buttons.dart
lib/app/services/file_cache/ion_cache_manager.dart

- fix handling the likes for the stories
- replace `getLibraryDirectory` method with `getApplicationSupportDirectory`, since it isn't supported on Android

fix: stories likes

---

lib/app/features/user/pages/profile_page/components/profile_details/profile_actions/profile_actions.dart

This enables users to start a conversation by clicking the chat button in the profile actions section.
N/A
https://github.com/user-attachments/assets/9437daaf-ca03-4ac8-99be-3cbf58b7cc6a

feat: initiate conversation from profile page

---

lib/app/features/wallets/views/components/wallets_list.dart
lib/app/features/wallets/views/pages/manage_wallets_modal.dart

Hide "Create wallet" button if a user already has 2 wallest.

fix(wallet): hide create wallet button

---

lib/app/features/feed/providers/feed_filter_relays_provider.c.dart
lib/app/features/feed/providers/feed_posts_data_source_provider.c.dart
lib/app/features/feed/providers/feed_stories_data_source_provider.c.dart
lib/app/features/feed/providers/feed_trending_videos_data_source_provider.c.dart
lib/app/features/feed/providers/feed_videos_data_source_provider.c.dart
lib/app/features/feed/providers/topic_articles_data_source_provider.c.dart
lib/app/features/feed/views/pages/feed_page/feed_page.dart

Seamless feed filter update to prevent feed from re-render after follow/unfollow 
Now `feedFilterRelays` updates only after pull-to-refresh
Splitting the existing `feedFilterRelaysProvider` into three specialized providers:
- Main provider that determines which specialized provider to use
- feedForYouFilterRelaysProvider for the "For You" feed
- feedFollowingFilterRelaysProvider for the "Following" feed

feat: seamless feed filter update

---

lib/app/features/feed/providers/feed_posts_provider.c.dart

Add filter to avoid showing story in feed as a post, after publish

fix: filter story from post feed

---

lib/app/features/wallets/views/pages/coins_flow/network_list/network_list_view.dart

Clear the address field before the Send form is opened. Currently this the only place we open the form. Also, I tried to `ref.invalidate` it (to reset to its initial state), but by some reason we get a `npe`.
This provider should be `keepAlive`d. And in future we gonna set the address from QR scanner before opening the form.

fix(wallet): clear address field before send coin flow

---

lib/app/features/wallets/providers/network_fee_provider.c.dart
packages/ion_identity_client/lib/ion_identity.dart
packages/ion_identity_client/lib/src/networks/services/get_estimate_fees/data_sources/get_estimate_fees_data_source.dart
packages/ion_identity_client/lib/src/networks/services/get_estimate_fees/models/estimate_fee.c.dart
packages/ion_identity_client/lib/src/networks/services/get_estimate_fees/models/estimate_fee.c.freezed.dart
packages/ion_identity_client/lib/src/wallets/services/make_transfer/models/transfer.c.g.dart

Currently our BE supports fees for EVM chains only, and returns 400 error for other networks. I set a default empty NetworkFee value in case of error to let the app continue the flow without fee information.

fix(wallet): handle 400 network fees response

---

lib/app/features/wallets/views/pages/coins_flow/receive_coins/providers/wallet_address_notifier_provider.c.dart

Fix the value to pass to `createWallet`. e.g. it has to be `BscTestnet` but we sent `BSC`.

fix(wallet): create wallet with correct network value

---

lib/app/features/wallets/model/transaction_details.c.dart
lib/app/features/wallets/providers/send_coins_notifier_provider.c.dart
lib/app/features/wallets/views/pages/transaction_details/transaction_details.dart

There was a parsing error for `TransactionDetails.networkFeeOption`. I changed the field to be nullable.
- change type of `TransactionDetails.networkFeeOption`
- hide some views if `networkFeeOption` is `null`

fix(wallet): make `TransactionDetails.networkFeeOption` nullable

---

ios/Podfile.lock
lib/app/features/chat/model/database/tables/reaction_table.dart
packages/ion_identity_client/pubspec.yaml

Added `@ReferenceName` annotations to resolve Drift duplicate references warning in `ReactionTable`. This fixes the issue where Drift couldn't generate proper filtering and sorting methods due to multiple references to the same table ([doc](https://drift.simonbinder.eu/dart_api/manager/#name-clashes)):
```
[WARNING] drift_dev on lib/app/features/chat/model/database/chat_database.c.dart:
Duplicate orderings/filters detected for field "reactionTableRefs" on table "$EventMessageTableTable". Filter and orderings for this field wont be generated. Use the @ReferenceName() annotation to resolve this issue. See https://drift.simonbinder.eu/docs/manager/#name-clashes for more information
[WARNING] drift_dev on lib/app/features/chat/model/database/chat_database.c.dart:
Duplicate orderings/filters …
```

fix: add @ReferenceName annotations to resolve drift duplicate references warning

---

lib/app/features/components/entities_list/components/repost_list_item.dart

Align repost padding with plain post

fix: remove repost padding

---

lib/app/features/wallets/domain/wallet_views/wallet_views_service.c.dart
packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view.c.dart
packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view.c.freezed.dart
packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view.c.g.dart

`nfts` field in `WalletView` was required, I've changed it to nullable.
The issue was that backend includes this field in the response only if it's not empty.

fix(wallet): remove `required` from nfts in WalletViews dto

---

lib/app/features/feed/views/pages/fullscreen_media/fullscreen_media_page.dart

fix: status bar color staying black after leaving media full screen page

---

lib/app/features/feed/stories/views/pages/story_record_page.dart
lib/app/services/media_service/banuba_service.c.dart

fix: prevent double banuba editor opening on Android camera capture

---

lib/app/features/chat/e2ee/providers/chat_message_load_media_provider.c.dart
lib/app/features/chat/views/components/message_items/message_reaction_dialog/message_reaction_dialog.dart
lib/app/features/chat/views/components/message_items/message_types/document_message/document_message.dart
lib/app/features/chat/views/components/message_items/message_types/text_message/text_message.dart
lib/app/services/share/share.dart

Fixes an issue where shared files did not retain their original filename and extension in chat.
- Fix overflow issue on message reaction dialog
N/A

bugfix(chat): use original filename and extension when sharing files

---

ios/Podfile.lock
lib/app/features/chat/e2ee/model/entities/private_direct_message_data.c.dart
lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/action_button.dart
lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/more_content_view.dart
lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/text_message_limit_label.dart
lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar.dart
lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar_initial.dart

Implements a 4096 character limit for text messages with visual feedback. When users exceed the limit, a red counter shows the number of excess characters and the send button is disabled.
- Set max selection count to 10 from media picker modal

feat(chat): Add character limit for text messages

---

ios/Podfile.lock
lib/app/services/compressor/compress_service.c.dart
lib/app/services/media_service/ffmpeg_args/ffmpeg_pixel_format_arg.dart

Add YUV420P pixel format support to ensure better video compatibility across platforms and devices. This flag forces it to export in standard 8-bit format so it works on all devices.
N/A
https://github.com/user-attachments/assets/1f9113ce-569f-4bbe-9b22-35b98a43263b

bugfix: add yuv420p pixel format support for video compression

---

lib/app/features/chat/e2ee/model/entities/private_direct_message_data.c.dart
lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar_recording.dart

Add 5-minute duration limit for audio messages.
- Clean up event listener naming for better clarity
N/A

feat: add audio message duration limit

---

lib/app/features/chat/e2ee/providers/send_chat_message/send_e2ee_chat_message_service.c.dart
lib/app/features/chat/e2ee/providers/send_chat_message_service.c.dart
lib/app/features/chat/e2ee/views/pages/one_to_one_messages_page.dart

Generate conversation IDs by combining the sorted participant master pubkeys. This ensures:
•	Messages sent simultaneously by User A and User B are grouped in the same conversation.
•	User B can continue receiving messages in the existing conversation even if User A reinstalls the app.

fix: improve chat conversation id generation to prevent duplicate conversation issue

---

lib/app/features/chat/e2ee/providers/e2ee_messages_subscriber.c.dart

Add `keepAlive` to `E2eeMessagesSubscriber` to ensure continuous message updates.  Without `keepAlive`, the subscription would be disposed when no widgets are listening
In a previous release, I listened to the `ref.dispose`, which is triggered when the user enters the conversation page.

fix: e2ee message subscriber should not be disposed

---

lib/app/features/chat/e2ee/providers/send_chat_message/send_chat_media_provider.c.dart
lib/app/features/chat/e2ee/providers/send_chat_message/send_e2ee_chat_message_service.c.dart
lib/app/features/ion_connect/providers/ion_connect_upload_notifier.c.dart
lib/app/services/compressor/compress_service.c.dart
pubspec.lock
pubspec.yaml

- Added database transactions and synchronized FFmpeg operations for better reliability [issue](https://github.com/arthenica/ffmpeg-kit/issues/1037)
- Improved media operation cancellation handling
- Added [synchronized](https://pub.dev/packages/synchronized) package to prevent concurrent FFmpeg operations during multiple media uploads

fix(chat):  improve reliability of multiple media uploads

---

lib/app/features/chat/e2ee/model/entities/private_direct_message_data.c.dart
lib/app/features/chat/model/upload_limit_modal_type.dart
lib/app/features/chat/views/components/message_items/messaging_bottom_bar/components/more_content_view.dart
lib/app/features/chat/views/pages/upload_limit_reached_modal/upload_limit_reached_modal.dart
lib/app/features/gallery/views/components/gallery_grid_cell.dart
lib/l10n/app_ar.arb
lib/l10n/app_en.arb

This PR implements a file upload size limit of 25MB for chat messages, similar to the existing video duration limit. It introduces a new `UploadLimitModalType` enum to handle different types of upload limits and updates the UI to show appropriate error messages when limits are reached.
N/A
https://github.com/user-attachments/assets/60c54812-4e5a-4ed1-894c-f77b8cd6275e

feat(chat): implement file upload size limit and update UI

---

lib/app/features/chat/model/database/dao/conversation_message_dao.c.dart
lib/app/features/chat/providers/unread_message_count_provider.c.dart
lib/app/features/chat/recent_chats/views/components/recent_chat_tile/archive_chat_tile.dart

This PR removes the filtering of muted conversations from the archive unread message count and show badge in gray if it has any muted conversation.
N/A

feat: remove muted conversations from archive unread count

---

lib/app/features/chat/views/components/message_items/message_types/visual_media_message/visual_media_content.dart
lib/app/features/ion_connect/model/media_attachment.dart
lib/app/features/ion_connect/providers/ion_connect_upload_notifier.c.dart
lib/app/services/compressor/compress_service.c.dart
lib/app/services/media_service/media_encryption_service.c.dart
lib/app/services/media_service/media_service.c.dart

This PR adds video duration display functionality to the chat interface. 
N/A

fix: show video duration label from file metadata for a chat video message

---

lib/app/features/wallets/domain/transactions/sync_transactions_service.c.dart
lib/app/features/wallets/providers/wallets_initializer_provider.c.dart

1. Catch exception during history loading and log them. As for now, just skip wallet, if we cannot get history for it. This flow will be improved in the future.
2. Improve `WalletsInitializer` to avoid wallets page freezing.

fix: catch exception during history loading and log them

---

lib/app/components/text_editor/components/custom_blocks/unknown/text_editor_unknown_embed_builder.dart
lib/app/components/text_editor/text_editor.dart
lib/app/components/text_editor/text_editor_preview.dart

By adding an `unknownEmbedBuilder` we enable backwards compatibility for when new embed builders are introduces and not supported on older version of the app.

feat: add unknown embed builder

---

lib/app/features/chat/e2ee/providers/send_chat_message/send_e2ee_chat_message_service.c.dart

Always set previousId for encrypted messages to ensure consistent message threading
N/A

fix: update previousId assignment in SendE2eeChatMessageService

---

lib/app/features/chat/e2ee/providers/e2ee_messages_subscriber.c.dart
lib/app/features/chat/e2ee/providers/send_chat_message/send_e2ee_chat_message_service.c.dart

Ensure messages are only processed when chat relays are properly synced, preventing potential message delivery issues.
N/A

fix(chat): Add chat relay validation before message processing

---

lib/app/features/wallets/domain/wallet_views/sync_wallet_views_coins_service.c.dart

1. Added several checks to protect against multiple queue runs.
2.  Added a time threshold for better grouping of coins for sync.

fix: add protection from empty attempts to sync

---

lib/app/features/chat/recent_chats/views/pages/recent_chats_timeline_page/recent_chats_timeline_page.dart

Enhances the animation of the archive section in the recent chats timeline by switching from height-based to opacity-based animation.
N/A
https://github.com/user-attachments/assets/6a83ae54-45d6-4afa-95c0-09f1316e0b9c

bugfix(chat): improve archive section animation in recent chats to prevent overflow issue

---

lib/app/exceptions/exceptions.dart
lib/app/features/chat/community/providers/community_messages_subscriber_provider.c.dart
lib/app/features/chat/e2ee/model/entities/private_direct_message_data.c.dart
lib/app/features/chat/e2ee/model/entities/private_message_reaction_data.c.dart
lib/app/features/chat/e2ee/providers/e2ee_messages_subscriber.c.dart
lib/app/features/chat/e2ee/providers/send_chat_message/send_e2ee_chat_message_service.c.dart
lib/app/features/chat/e2ee/providers/send_chat_message_service.c.dart
lib/app/features/chat/e2ee/providers/send_e2ee_message_provider.c.dart
lib/app/features/chat/model/database/dao/conversation_dao.c.dart
lib/app/features/chat/model/database/dao/conversation_event_message_dao.c.dart
lib/app/features/chat/providers/exist_chat_conversation_id_provider.c.dart
lib/app/features/feed/stories/providers/story_reply_provider.c.dart
lib/app/features/wallets/domain/transactions/send_transaction_to_relay_service.c.dart
test/app/services/ion_connect/ion_connect_gift_wrap_service_test.dart

- Allows to subscribe to new Replaceable events 
- All new messages send only new Replaceable events kind
- Backward compatible with Immutable events
- Allows to send both types of events

feat:  edit chat message migration, phase 2

---

lib/app/features/feed/views/pages/feed_page/feed_page.dart

This PR fixes an issue where the same requests for feed related data was fired multiple times upon pull to refresh.
It appears that the order of invalidations mattered here, as moving the feedRelays provider invalidation to the top of the chain resolved the issue.

fix: multiple feed requests after pull to refresh

---

lib/app/features/chat/views/components/message_items/message_types/document_message/document_message.dart
lib/app/services/media_service/media_encryption_service.c.dart

Chat receiver should be able to preview the document message.
N/A
https://github.com/user-attachments/assets/ec425b28-2212-48bf-b2e4-6ddef5e1321f

bugfix(chat): handle document media preview

---

lib/app/services/text_parser/model/text_matcher.dart

This PR updates the regex for URLMatcher to cover old media urls

fix: modify url matcher regex to match old images urls

---

lib/app/features/core/permissions/views/components/permission_aware_widget.dart
lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart
lib/app/features/feed/views/pages/feed_page/components/stories/components/current_user_avatar_with_permission.dart
lib/app/features/feed/views/pages/feed_page/components/stories/components/plus_button_with_permission.dart

This PR fixes an issue where double record video page was pushed because of multiple widgets reacting to granted permission.
- Refactored how a `resourceId` is used inside the `PermissionAwareWidget`
- Removed checks for correct `resourceId` during tap callback as user initiated actions should always pass.

fix: double camera page push upon initial permission grant when creating a video post

---

lib/app/features/wallets/utils/prefix_trimmer.dart
lib/app/features/wallets/views/components/qr_scanner_bottom_sheet.dart
lib/app/features/wallets/views/pages/wallet_scan_modal_page.dart
test/app/features/wallets/utils/prefix_trimmer_test.dart

This PR fixes removes prefix for QR scanned codes. e.g. if scanner reads "prefix:thecode" it's gonna emmit "thecode" without the "prefix:" part. See tests for the function for better explanation

fix: remove network prefix for qr code scanner

---

lib/app/features/wallets/providers/delete_wallet_view_provider.c.dart
lib/app/features/wallets/views/pages/create_new_wallet_modal.dart
lib/app/features/wallets/views/pages/delete_wallet_modal.dart

This PR adds `await` for deleting and creating WalletViews. Previously the app was closing the dialog right after the button is pressed.

fix(wallet): wait for request to complete before going away from dialog

---

lib/app/components/video_preview/video_preview.dart
lib/app/features/video/views/pages/video_page.dart

This PR fixes an issue where the video in full screen mode would pause when muted/unmuted
This issue is actually caused by the video_preview present inside feed cell underneath that uses the same video controller. It has a `onEffect` which pauses the video, because cell is not visible on the screen. By introducing a `wasOffScreen` flag we avoid video pausing after controller changes if the video_preview was already off screen before that.

fix: stop video from pausing in full screen when mute is toggled

---

lib/app/features/wallets/utils/wallet_address_validator.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/address_input_field.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/buttons/coin_amount_input.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/contact_input_switcher.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart
lib/app/features/wallets/views/pages/send_nft_form.dart
lib/l10n/app_en.arb
pubspec.lock
pubspec.yaml
test/wallets/wallet_address_validator_test.dart

Add rough wallet address validation to filter obvious mistakes. 
1. Create wallet validators for each network. As for now, attach it to id. 
2. Add validation for the wallet address field to send coins/nft flows. 
3. Refactor input coin amount field validation.
https://github.com/user-attachments/assets/2e341113-e19d-4804-9bb0-4f2aca952b73

fix: add wallet address validation

---

lib/app/features/wallets/views/pages/wallet_page/components/search_bar/search_bar.dart
lib/app/features/wallets/views/pages/wallet_page/components/tabs/tabs_header.dart
lib/app/features/wallets/views/pages/wallet_page/helpers/cancel_search_helper.dart

Previously, a user had to start typing into the Search field to let the "Cancel" button appear. On the "Cancel" tap, the Search field is hidden.
This PR adds ability to hide the Search field by tapping the Search icon the second time. See the GIF attached.

feat(wallet): toggle Search filed on Search icon tap

---

lib/app/features/chat/providers/active_audio_message_provider.c.dart
lib/app/features/chat/views/components/message_items/message_types/audio_message/audio_message.dart
lib/app/features/chat/views/components/message_items/message_types/audio_message/components/play_pause_button.dart
lib/app/features/chat/views/components/message_items/message_types/document_message/document_message.dart
lib/app/services/media_service/media_encryption_service.c.dart

- Add active audio message provider to manage single audio playback
- Refactor audio message component to use load from message media table
- Improve document message tap behavior
- Update media encryption service to use correct file extensions
N/A
https://github.com/user-attachments/assets/24871f82-da43-4fe0-b68b-e75be41d831e

bugfix: audio message playback and media handling

---

lib/app/features/user/pages/profile_page/profile_page.dart
lib/app/features/user/providers/followers_count_provider.c.dart

Remove keep alive for `followersCount` provider, to get new state on profile page instead cached.

fix: refresh followers count

---

lib/app/features/wallets/data/mappers/transaction_mapper.dart
lib/app/features/wallets/data/repository/transactions_repository.c.dart
lib/app/features/wallets/domain/wallet_views/wallet_views_service.c.dart
lib/app/features/wallets/providers/send_coins_notifier_provider.c.dart
lib/app/features/wallets/providers/synced_coins_by_symbol_group_provider.c.dart

ion service apply similar balance hack itself for tier 2 networks, so we don't need to do it on the mobile side.
1. Fix balance hack.
2. Remove `balanceBeforeTransactions`, since it isn't used anymore.
3. Fix issue with `SyncedCoinsBySymbolGroupNotifier`. Earlier because of the state type it was recreated before each call.

fix: apply balance hack only for tier 1 networks

---

lib/app/features/ion_connect/providers/ion_connect_db_cache_notifier.c.dart
lib/app/features/user/providers/relays_reachability_provider.c.dart
lib/app/features/user/providers/user_relays_manager.c.dart

This PR migrates `UserRelaysManager` to use db cache instead of memory cache. 
It also adds logic to refetch the relays if most of them are marked as dead
Relays will be marked as dead when there are three consecutive failed attempts to reach them with 1 hour passing between each attempt. This will be implemented as part of the next PR.

feat: fetch user relays from db instead of memory cache, add refetch logic when most of the cached relays are dead

---

lib/app/features/chat/views/components/message_items/message_types/text_message/text_message.dart

This PR fixes an issue where text messages containing newline characters would cause layout overlap with the message metadata.
N/A

fix: prevent overlap issue when text message has a new line char

---

lib/app/features/wallets/domain/coins/coins_comparator.dart

Update coins/networks sorting. If coins have the same balance and symbols, display first native for the selected network, if provided.

fix: receive flow networks order

---

ios/Podfile.lock
lib/app/features/wallets/providers/send_nft_form_provider.c.dart
lib/app/features/wallets/views/components/qr_scanner_bottom_sheet.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/address_input_field.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/contact_input_switcher.dart
lib/app/features/wallets/views/pages/send_nft_form.dart
lib/app/router/wallet_routes.dart

This PR adds (fixes) QR code scanner for Send NFT form.
- The main changes are in the `wallet_routes.dart`. These fix the navigation to the QR code scanner and back to the form.
- Changes in the `QRScannerBottomSheet` fix an issue with the events sent from QR code scanner when they shouldn't, and that led to a crash.
- Changes in the `ContactInputSwitcher` and `AddressInputField` allows to set an address by padding in to the constructor, which allows to override value in the address field after a QR code is scanned.
- There's also a fix for NPE in the `SendNftFormController._loadNetworkFeeOptions`
https://github.com/user-attachments/assets/6a3b47d4-d0d9-407b-b676-6c587d8aab36

fix: Send NFT flow with QR code scanner

---

lib/app/features/wallets/views/pages/coins_flow/send_coins/components/buttons/coin_amount_input.dart
lib/l10n/app_en.arb

This PR fixes the amount field validation in the Request Funds form. Also, we use this component in the Send Funds form, that's why there're additional checks for `maxValue` (we don't use `maxValue` for funds request).

fix: request funds amount validation

---

lib/app/exceptions/exceptions.dart
lib/app/features/chat/providers/user_chat_relays_provider.c.dart
lib/app/features/ion_connect/providers/ion_connect_db_cache_notifier.c.dart
lib/app/features/ion_connect/providers/ion_connect_notifier.c.dart
lib/app/features/ion_connect/providers/mixins/relay_create_mixin.dart
lib/app/features/ion_connect/providers/relay_creation_provider.c.dart
lib/app/features/ion_connect/providers/relay_provider.c.dart
lib/app/features/user/model/user_chat_relays.c.dart
lib/app/features/user/providers/relays_reachability_provider.c.dart
lib/app/features/user/providers/user_relays_manager.c.dart
lib/app/utils/retry.dart

This PR adds a mechanism for caching relays and refetching them when more than 50% of them are marked as dead.
Relay will marked as dead when there are 3 consecutive failed connection attempts with 1 hour between each one.

feat: add refetch for unreachable relays

---

lib/app/features/wallets/views/pages/coins_flow/coin_receive_modal/components/coin_address_tile/coin_address_tile.dart

This PR fixes displaying a coin with a long name in the Receive dialog.
Before:
After:

fix: displaying long coin names in Receive dialog

---

lib/app/features/feed/stories/hooks/use_keyboard_height.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/story_content.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/story_input_field.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/story_viewer_action_buttons.dart
lib/app/features/feed/stories/views/components/story_viewer/components/reactions/story_reaction_overlay.dart
lib/app/features/feed/stories/views/pages/story_viewer_page.dart

This PR fixes a visual issue where both video and image stories lost their aspect ratio after the keyboard was opened. The root cause was related to layout constraints and incorrect rebuild areas reacting to MediaQuery's insets and paddings.
- Adjusted the layout on StoryViewerPage to ignore bottom insets and paddings when the keyboard is visible.
- Reworked the bottom overlay footer and progress bar area to correctly respond to keyboard visibility 
https://github.com/user-attachments/assets/3e2413a9-b201-4424-b047-06f50a9d42aa

fix: video/image stories shrinking when keyboard appears

---

lib/app/features/feed/providers/delete_entity_provider.c.dart

Story is still displayed after deleting - user needs to refresh feed not to see removed story
Story is not displayed after deleting

fix: optimize story deletion process

---

lib/app/features/feed/stories/views/components/story_viewer/components/header/story_context_menu.dart
lib/app/features/feed/stories/views/pages/story_preview_page.dart

- Improve the story deletion process by ensuring the current story is referenced
- Invalidate the stories' data source after successful story publication

fix: resolve story deletion reference and data refresh issue

---

lib/app/features/wallets/views/pages/coins_flow/send_coins/components/buttons/coin_amount_input.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart

This PR fixes this issue: when a user opens "send coins" form, the amount field has `0.00` value. Also, the zero value (like `0` or `0.0`) issued "insufficient funds" validation error.

fix(wallet): set initial amount value to ''

---

lib/app/components/text_editor/utils/text_editor_styles.dart
lib/app/templates/basic.json
lib/app/templates/template.c.dart
lib/app/theme/app_colors.dart

This PR changes text color only for post and articles content
Added new color to avoid breaking other places in the app using the same font as post/article content

feat: update post and article content text color

---

lib/app/features/core/providers/internet_connection_checker_provider.c.dart
lib/app/features/core/providers/internet_status_stream_provider.c.dart

Users see the "no internet connection" notification even when the internet connection is there. I changed the url to knock to (our origin) and increased timeout from default 3 to 5 seconds. Also check interval is decreased from default 10 to 8 seconds.

fix: change internet availability checking strategy

---

lib/app/features/chat/views/components/message_items/message_types/money_message/components/amount_display.dart
lib/app/features/wallets/providers/wallet_user_preferences/wallet_user_preferences_provider.c.dart
lib/app/features/wallets/views/pages/coins_flow/coin_details/components/balance/coin_usd_amount.dart
lib/app/features/wallets/views/pages/coins_flow/coin_details/components/transaction_list_item/transaction_list_item.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/confirmation/transaction_amount_summary.dart

fix: unify usd amount display for all coins to always display $ sign instead of USD postfix

---

ios/Podfile.lock
lib/app/services/sentry/sentry_service.dart
lib/main.dart

Small improve to init sentry only for release builds
Also remove `SentryWidget` cuz we don't needed

feat: sentry init only in release mode

---

lib/app/features/wallets/hooks/use_check_wallet_address_available.dart

This PR adds a logic where `AddresNotFoundModal` is not displayed for ION network and the wallet address is immediately created.

fix: skip display of address not found modal for ion network

---

lib/app/features/core/providers/internet_connection_checker_provider.c.dart
lib/app/features/core/providers/internet_status_stream_provider.c.dart
pubspec.lock

We still have the false "No internet connection" banner shown in the app. This PR tries to fix it by adding more URIs to check and increasing timeout.

fix: add IPs to check, add lifecycle check

---

lib/app/features/auth/views/pages/select_languages/select_languages.dart
lib/app/features/core/providers/app_locale_provider.c.dart
lib/app/features/core/views/pages/language_selector_page.dart
lib/app/features/optimistic_ui/features/language/language_sync_strategy_provider.c.dart
lib/app/features/settings/views/account_settings_modal.dart
lib/app/hooks/use_languages.dart

This PR adds a logic that displays the system locale at the top of the language selector, or at second place, if a different language is already selected.

fix: put system language at the top of the list if selected, second place if not

---

lib/app/features/chat/views/components/message_items/messaging_bottom_bar/messaging_bottom_bar_initial.dart

This PR fixes the chat text field from resetting when the user switches to the initial view.
N/A

fix: prevent resetting chat text field when user switch to initial view

---

lib/app/components/coins/coin_icon.dart
lib/app/features/wallets/providers/send_asset_form_provider.c.dart
lib/app/features/wallets/views/pages/coins_flow/coin_details/components/balance/coin_usd_amount.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/buttons/coin_amount_input.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart
lib/app/features/wallets/views/utils/amount_parser.dart
lib/app/utils/text_input_formatters.dart
test/utils/text_input_formatters_test.dart

So, the main purpose of new text formatter is to use comma as delimiter between int digits. So, if I input `9999`, then the text field should show `9,999`. So complex logic is necessary, cos iOS, for example, use comma as delimiter between ints and decimals, so we need to handle such cases.
Fixed bugs:
- Removed rounding for the coin icons.
- Used correct formatting for the coin balance on the `CoinDetails` page.
https://github.com/user-attachments/assets/94ff3d1a-fc28-4993-963a-ed73150bbdbe

fix: make coin amount input field the same as on the web

---

lib/app/features/chat/views/components/message_items/message_reaction_dialog/message_reaction_dialog.dart

Updated the calculation for the top y-coordinate in the message reaction dialog to ensure it respects the top padding of the media query
N/A
https://github.com/user-attachments/assets/902e3992-86f4-41e1-a02a-0c1fbce3c15b

fix: adjust message reaction dialog positioning logic

---

lib/app/features/core/providers/init_provider.c.dart
lib/app/features/core/views/components/widget_error_builder.dart

This PR sets a SizedBox as an ErrorWidget that will be rendered during build method exceptions in release mode.
This change prevents parts of the app from not being usable in case of any build error. For example, when exception was thrown during build method of a post cell on feed, whole feed became unusable. This change is going to prevent that from happening.
Sample screenshot showcasing how feed will look like when post body fails to render.

feat: set SizedBox as an error widget for release builds

---

ios/Podfile.lock
lib/app/features/feed/stories/views/components/story_capture/controls/story_gallery_button.dart
lib/app/features/gallery/views/components/gallery_grid_view.dart
lib/app/features/gallery/views/pages/media_picker_page.dart
lib/app/router/feed_routes.dart

- Set showCameraCell to false for gallery opened from StoryGalleryButton
- Prevents redundant camera access when users are already in camera mode

fix: prevent camera cell crash when opening gallery from story capture

---

lib/app/utils/text_input_formatters.dart
test/utils/text_input_formatters_test.dart

fix: set max decimals number for coin input amount to 18

---

lib/app/features/feed/create_article/providers/create_article_provider.c.dart
lib/app/features/feed/create_post/providers/create_post_notifier.c.dart
lib/app/features/feed/data/models/entities/article_data.c.dart
lib/app/features/feed/data/models/entities/modifiable_post_data.c.dart
lib/app/features/ion_connect/model/media_attachment.dart
lib/app/features/ion_connect/providers/ion_connect_upload_notifier.c.dart
lib/app/services/markdown/quill.dart

This PR:
1. Removes `x` and `i` fields from `imeta` tag
2. Sets empty `content` inside posts/article when `richText` is not empty during creation
3. Introduces a logic to flatten links inside content of posts/articles if they are the same as text (e.x. "*[someLink]*(someLink)")  to avoid duplication

feat: optimize event links

---

lib/app/features/wallets/data/database/wallets_database.c.dart
lib/app/features/wallets/domain/wallet_views/wallet_views_service.c.dart
lib/app/features/wallets/providers/send_coins_notifier_provider.c.dart
lib/app/features/wallets/providers/synced_coins_by_symbol_group_provider.c.dart
lib/app/features/wallets/views/pages/wallet_page.dart

1. Refresh synced coin groups after transfer/wallet page refresh.
2. Remove deprecated database table.
3. When request broadcasted transfers to apply balance fix, request only related to the current wallet view transfers.

fix: sync coin groups after transfer and wallets refresh

---

lib/app/features/auth/views/components/identity_key_name_input/identity_key_name_input.dart

This PR fixes an issue where continue button could be tapped and register logic was initiated with empty input field
https://github.com/user-attachments/assets/310baf65-c82f-4c1f-8b76-f560a7e03eca

fix: identity key name validation on continue tap

---

lib/app/services/compressors/brotli_compressor.c.dart

This PR optimizes Brotli compression and decompression operations by moving them to separate isolates using Flutter's compute function. This prevents UI blocking during heavy compression/decompression tasks.

perf(compression): move brotli operations to isolates

---

lib/app/features/wallets/domain/coins/coins_service.c.dart
lib/app/features/wallets/providers/send_coins_notifier_provider.c.dart
lib/app/features/wallets/views/components/arrival_time/network_fee_selector.dart

This PR fixes 2 issues related to fee in Send Coins flow:
- hides network fee slider if we have only 1 network fee option (screenshot 1). previously the app crashed on this step.
- adds network fee for the supported transfers

fix(wallet): send coins fee

---

lib/app/features/chat/recent_chats/views/pages/delete_message_modal/delete_message_modal.dart

This PR addresses the issue by adjusting the bottom padding in the delete message modal.
N/A

fix: adjust bottom padding in delete message modal

---

lib/app/features/chat/views/components/message_items/message_item_wrapper/message_item_wrapper.dart
lib/app/features/chat/views/components/message_items/message_reaction_dialog/components/message_reaction_context_menu.dart
lib/app/features/chat/views/components/message_items/message_types/money_message/money_message.dart
lib/app/features/chat/views/components/message_items/message_types/reply_message/reply_message.dart

This PR fix displays reply and reaction content for money messages.
N/A

fix: show reply and reactions content for money messages

---

lib/app/features/chat/views/components/message_items/message_reaction_dialog/components/message_reaction_context_menu.dart

This PR filters the message type only for text and emoji messages to enable copying.
N/A

fix: update message copy logic in reaction context menu

---

lib/app/components/text_editor/components/cashtags_suggestions.dart
lib/app/components/text_editor/components/hashtags_suggestions.dart
lib/app/components/text_editor/utils/mentions_hashtags_handler.dart
lib/app/services/text_parser/model/text_matcher.dart

This PR:
1. unifies regex for cashtags (different ones were used in different places)
2. updates the regex to allow numbers and dashes inside cashtags (don't allow numbers only)

fix: unify cashtag regex across the app, allow numbers and dashes in cashtags in addition to letters

---

packages/ion_identity_client/lib/src/core/helpers/converters/string_or_int_converter.dart
packages/ion_identity_client/lib/src/wallets/services/get_wallet_assets/models/wallet_asset.c.dart
packages/ion_identity_client/lib/src/wallets/services/get_wallet_assets/models/wallet_asset.c.freezed.dart
packages/ion_identity_client/lib/src/wallets/services/get_wallet_assets/models/wallet_asset.c.g.dart
packages/ion_identity_client/lib/src/wallets/services/wallet_views/models/wallet_view_aggregation_item.c.dart

Some backend responses return the balance field as a string, others as an int. This caused deserialization issues.
Added a StringOrIntConverter to handle both formats gracefully.

fix(ion_identity_client): add `StringOrIntConverter` to parse an asset's balance

---

lib/app/components/video_preview/video_preview.dart

This PR fixes an issue where the video thumbnail (during video loading) was only taking half of the available width.

fix: make video thumbnail cover the whole width in post media

---

lib/app/features/chat/views/components/message_items/message_types/money_message/components/amount_display.dart
lib/app/features/chat/views/components/message_items/message_types/money_message/money_message.dart

Fix for asset amount rounding in MoneyMessage. e.g. previously if I sent 0.005 it was shown as 0.01.

fix(chat): remove rounding for asset amount

---

lib/app/components/text_span_builder/text_span_builder.dart

This PR normalizes URLs before opening in the app browser when highlighted.
N/A

fix: normalize URLs before opening in app browser

---

lib/app/features/chat/recent_chats/views/components/recent_chat_tile/recent_chat_tile.dart

Previously the message was "Money sent" even for a user who received money. Now it's displayed "Money sent" for the sender and "Money received" for the receiver.

fix(chat): update MoneySent recent message title

---

lib/app/features/video/views/pages/video_page.dart

- video should not pause when you take a screenshot till it saves before the video continues to play

fix: video pause conditions

---

lib/app/features/feed/providers/feed_bookmarks_notifier.c.dart
lib/app/features/ion_connect/model/disliked_relay_urls_collection.c.dart
lib/app/features/ion_connect/providers/ion_connect_notifier.c.dart
lib/app/features/ion_connect/providers/long_living_subscription_relay_provider.c.dart
lib/app/features/ion_connect/providers/relay_creation_provider.c.dart

This PR adds a provider managing relays for long living subscription so that we can avoid multiple relays being used for the same pubkey subscriptions.

feat: add a provider for long living subscription relays

---

lib/app/features/chat/recent_chats/views/pages/recent_chats_timeline_page/recent_chats_timeline_page.dart

This PR fixes the smooth scrolling issue when the user reaches the bottom of the page.

fix: prevent scroll jump at end of message list

---

ios/Runner.xcodeproj/project.pbxproj
lib/app/features/chat/components/messaging_header/messaging_header.dart

This PR addresses the use of ellipsis for shortened display names in the messaging header.

fix: use ellipsis for overflowing display name in messaging header

---

lib/app/router/base_route_data.dart
lib/app/router/chat_routes.dart

This PR introduces a `canPop` parameter to `BaseRouteData`, enabling customizable pop behavior. Users can now swipe left from message pages to access conversation pages on android

feat: add canPop parameter to BaseRouteData for customizable pop behavior

---

lib/app/router/chat_routes.dart

This PR addresses the chat feature by enabling a dismiss gesture for full-screen preview images.
N/A

fix(chat): enable dismiss gesture for fullscreen preview image

---

lib/app/features/chat/views/pages/chat_media_page/chat_media_page.dart

This PR addresses the logic for the mute/unmute icons on the chat media page.
N/A

fix: correct mute/unmute icon logic in chat media page

---

lib/app/features/wallets/providers/network_fee_provider.c.dart
lib/app/features/wallets/providers/send_coins_notifier_provider.c.dart
lib/app/features/wallets/views/pages/transaction_details/transaction_details.dart
lib/app/features/wallets/views/pages/transaction_details/transaction_details_actions.dart

This PR disables "View on explorer" button in Transaction Details dialog for non-confirmed TON transactions.
Also it fixes a situation when we stuck in the "in progress" state during sending coins.

fix(wallet): disable TON explorer for not Confirmed transactions

---

lib/app/extensions/riverpod.dart
lib/app/features/ion_connect/providers/file_storage_url_provider.c.dart
lib/app/features/ion_connect/providers/ion_connect_delete_file_notifier.c.dart
lib/app/features/ion_connect/providers/ion_connect_upload_notifier.c.dart
lib/app/features/ion_connect/utils/file_storage_utils.dart

This PR fixes a performance issue where multiple requests were made to the NIP96 endpoint when uploading multiple media files. Previously, each file upload triggered a separate request to fetch the storage URL, causing unnecessary network overhead.
The fix introduces a cached provider (`fileStorageUrlProvider`) that fetches the URL once and reuses it for all subsequent uploads within a 5-minute window.
- The provider includes proper cleanup with `CancelToken` to cancel in-flight requests when disposed

fix: cache file storage URL to prevent multiple NIP96 requests

---

lib/app/features/core/model/paged.c.dart
lib/app/features/feed/notifications/providers/notification_followers_subscription_provider.c.dart
lib/app/features/feed/notifications/providers/notification_likes_subscription_provider.c.dart
lib/app/features/feed/notifications/providers/notification_quotes_subscription_provider.c.dart
lib/app/features/feed/notifications/providers/notification_replies_subscription_provider.c.dart
lib/app/features/feed/notifications/providers/notification_reposts_subscription_provider.c.dart
lib/app/features/ion_connect/providers/entities_syncer_notifier.c.dart
pubspec.yaml

This PR changes the time overlap we use for some requests from 2 seconds to 2 microsends, because time precision inside nostr-dart library was changed from seconds to microseconds.
Related PR: [Link](https://github.com/ice-blockchain/nostr-dart/pull/12)

feat: change time precision for event messages from seconds to microseconds

---

lib/app/services/media_service/media_service.c.dart

This PR resolves the issue of saving media in bytes read, ensuring it appears in the recent gallery.
N/A

fix: save media to appear in recent gallery

---

lib/app/router/main_tabs/main_tab_navigation.dart

This PR fixes an issue where clicking on android system back button after coming back from the reply modal in post details page was closing the app.

fix: app closing after android system back button tap after reply

---

lib/app/features/search/views/pages/chat/components/chat_search_results_list_item.dart

This PR replaces userMetadataProvider with the cached version in the chat search list.
N/A

fix: replace userMetadataProvider with cached version in chat user search list

---

lib/app/features/chat/views/components/message_items/message_types/money_message/components/money_message_button.dart
lib/app/features/wallets/model/send_asset_form_data.c.dart
lib/app/features/wallets/providers/send_asset_form_provider.c.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/buttons/coin_amount_input.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart

The bug: When someone requests 1000 ION, but you have only 10, the Send form doesn’t validate your balance against the requested amount.
This PR fixes the issue by adding validation to ensure you cannot send more than your available balance.

feat(chat,wallet): add max amount validation for MoneyMessage request

---

lib/app/features/chat/views/components/message_items/message_types/money_message/components/money_message_button.dart

The bug: When you press “View Transaction” on a money message, the app shows a “success” modal, and only from there you can press “details” to see the transaction details.
Fix: Changed the destination of “View Transaction” to go directly to the transaction details.

fix: change route for MoneyMessage-ViewTransaction button

---

lib/app/features/feed/stories/views/pages/story_viewer_page.dart
lib/app/router/base_route_data.dart
lib/app/router/chat_routes.dart
lib/app/router/components/modal_wrapper/dismissible_content.dart
lib/app/router/components/modal_wrapper/dismissible_page.dart
lib/app/router/feed_routes.dart

- Fixed an issue where the black background in the story viewer was moving along with the content when swiping down to dismiss. The background now remains static while only the content moves.
- Added a new `staticBackground` parameter to `DismissiblePage` widget to control whether the background should animate its opacity during swipe
- Renamed `isFullscreenImage` to `isFullscreenMedia` throughout the codebase for better semantic accuracy
- The fix only affects fullscreen media views (stories, chat media) while preserving the existing behavior for other dismissible screens like video feeds

fix: static background for story viewer swipe dismiss

---

lib/app/features/wallets/domain/coins/coins_comparator.dart

Replaced deprecated abbreviation to sort coins correctly.

fix: replace ICE with ION in the CoinsComparator

---

lib/app/features/feed/stories/views/components/story_viewer/components/viewers/image_story_viewer.dart
lib/app/features/feed/stories/views/components/story_viewer/components/viewers/tap_to_see_hint.dart
lib/app/features/feed/stories/views/components/story_viewer/components/viewers/viewers.dart
lib/l10n/app_ar.arb
lib/l10n/app_en.arb

Implement a tap-to-see tooltip for stories with quoted posts. When users tap on a story that contains a quoted post, a tooltip appears, allowing them to navigate to the full post details.

feat: add tap-to-see tooltip for stories with quoted posts

---

lib/app/features/wallets/providers/send_asset_form_provider.c.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart
lib/app/features/wallets/views/utils/network_validator.dart

When a user makes a wallet public, another user is unable to send money because the wallets are still private in cache.

fix: skip cache when checking user wallets

---

lib/app/features/chat/views/components/message_items/message_types/money_message/components/money_message_button.dart

Issue: `User relays not found for ***`
Before and after the fix

fix: use the correct pubkey on send funds by request

---

lib/app/components/coins/coin_icon.dart
lib/app/components/select/select_coin_button.dart
lib/app/features/wallets/views/components/coin_icon_with_network.dart
lib/app/features/wallets/views/components/coin_networks_list/coin_network_item.dart
lib/app/features/wallets/views/components/coins_list/coin_item.dart
lib/app/features/wallets/views/pages/coins_flow/coin_details/coin_details_page.dart
lib/app/features/wallets/views/pages/coins_flow/coin_receive_modal/components/coin_address_tile/coin_address_tile.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/confirmation/confirmation_sheet.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/confirmation/transaction_result_sheet.dart
lib/app/features/wallets/views/pages/manage_coins/components/manage_coin_item_widget.dart
lib/app/features/wallets/views/pages/transaction_details/transaction_details.dart

1. Refactored `CoinIconWidget` to strict radius/size.
2. Set the correct values for different types.

fix: correct the borderRadius for the coin icons.

---

lib/app/features/video/views/components/video_post_info.dart
lib/app/features/video/views/components/video_post_text.dart
lib/app/features/video/views/pages/videos_vertical_scroll_page.dart

This PR fixes an issue where videos from legacy PostEntities could not be launched in media full screen page.

fix: support legacy PostEntity in video full screen page

---

lib/app/features/chat/e2ee/views/pages/one_to_one_messages_page.dart
lib/app/features/chat/recent_chats/views/pages/recent_chats_timeline_page/recent_chats_timeline_page.dart
lib/app/features/user/providers/user_metadata_provider.c.dart
lib/l10n/app_en.arb

This PR fixes the issue where if a user is deleted, it should be shown as a deleted account.

fix(chat): handle deleted accounts in chat timeline page

---

lib/app/features/core/providers/video_player_provider.c.dart

This PR fixes an issue where video player controller sometimes didn't get disposed, causing a memory leak.
This happened mostly during fast scrolling in vertical videos page. The root cause of this issue was that dispose logic was set up after the video player controller got created and initialized. If the provider got destroyed before video player controller finished initializing, it was never disposed.

fix: video player controller not disposing

---

lib/app/features/chat/recent_chats/views/pages/recent_chats_timeline_page/recent_chats_timeline_page.dart
lib/app/features/user/providers/request_coins_submit_notifier.c.dart
lib/app/router/chat_routes.dart

1. Fix navigation issue, when sending coins from chat.
2. Send pubkey of the current user in the request, so the person, who sent request, will receive coins.
https://github.com/user-attachments/assets/e5ebff71-faf9-4244-81c0-069e254e5d6a

fix: send funds via chat to the correct person

---

android/app/src/main/kotlin/io/ion/app/AudioFocusHandler.kt
ios/Runner/AppDelegate.swift
lib/app/features/core/providers/video_player_provider.c.dart

This PR fixes an issue where video sometimes got paused after volume was unmuted
https://github.com/user-attachments/assets/ecc2f777-17a7-48a2-9fa5-4ad128ca5bd2
https://github.com/user-attachments/assets/675c2228-89aa-42fb-bf1c-f7b93db36c4e

fix: video pause when unmuted

---

lib/app/features/components/entities_list/entities_list.dart
lib/app/features/user/pages/profile_page/components/tabs/tab_entities_list.dart

This PR fixes an issue where after clicking `not interested` on a user, it wasn't possible to see any of their posts on their profile. Such behavior should only apply to blocking. For non interested/muting, only content on feed should be hidden.

fix: show posts inside profile for muted users

---

lib/app/features/user/pages/profile_page/profile_page.dart

This PR fixes an issue where `CantFindProfilePage` was not properly shown when metadata didn't load

fix: show cant find profile page when user is deleted

---

lib/app/features/ion_connect/providers/active_relays_provider.c.dart
pubspec.lock
pubspec.yaml

Currently, when we restore the device keypair, the app loads old messages only after restart. This PR makes the app restore conversations in the same session.
The issue was that relay were already connected with the old data, and need to be invalidated.
2891

fix(chat): invalidate ActiveRelays on EventSigner change

---

lib/app/features/chat/e2ee/providers/send_chat_message/send_e2ee_chat_message_service.c.dart
lib/app/features/chat/recent_chats/views/components/recent_chat_tile/recent_chat_tile.dart
lib/app/features/chat/views/components/message_items/message_reaction_dialog/components/message_reaction_emoji_bar.dart
lib/app/features/chat/views/components/message_items/message_reactions/components/message_reaction_chip.dart
lib/app/features/chat/views/components/message_items/message_reactions/message_reactions.dart
lib/app/features/chat/views/components/message_items/message_types/emoji_message/emoji_message.dart
lib/app/features/core/views/pages/search_emoji_modal/components/emojis_grid_view.dart
lib/app/features/core/views/pages/search_emoji_modal/search_emoji_modal.dart
lib/app/features/feed/stories/views/components/story_viewer/components/reactions/story_reaction_notification.dart
lib/app/features/feed/stories/views/components/story_viewer/components/reactions/story_reaction_overlay.dart
pubspec.lock
pubspec.yaml

- Workaround for the old Android versions and emojis in the chat
- In a good way should be fixed with dynamic font load and font fallback but currently Flutter doesn't support it https://github.com/material-foundation/flutter-packages/issues/155

feat: platform aware emojis

---

lib/app/features/auth/views/pages/link_new_device/link_new_device_dialog.dart
lib/app/features/ion_connect/providers/device_keypair_utils.dart
lib/app/features/ion_connect/providers/ion_connect_event_signer_provider.c.dart
lib/app/features/user/pages/switch_account_modal/components/accounts_list/account_tile.dart

This PR updates the keypair handling flow during login on new devices.
What’s changed:
- When a user logs in on a new device, we now check if an uploaded keypair exists:
• If yes -> we restore/download the existing keypair
• If not -> we generate a new keypair and follow the existing attestation flow
ION-2933

feat: Use restored keypair on new devices instead of generating a new one

---

lib/app/features/chat/views/components/message_items/message_types/post_message/shared_story_message.dart
lib/app/features/feed/stories/providers/story_viewing_provider.c.dart
lib/app/features/feed/stories/views/pages/story_viewer_page.dart

With this PR, user can view a story from a non-followed user in the chat if it's shared in conversation.
N/A
ION-2943

fix(stories): allow viewing stories from non-followed users

---

lib/app/features/auth/views/pages/get_started/components/login_form.dart

This PR fixes the amount of space login modal scrolls up when keyboard is shown, to ensure that only identity key name and continue button are visible.

fix: decrease login input field bottom scroll padding

---

lib/app/features/feed/create_post/views/components/topics/topics_button.dart
lib/app/features/feed/create_post/views/pages/post_form_modal/components/create_post_content.dart

This PR improves a logic to detect wether or not post is a video post or not and update topics list based on that.

fix: correctly change available topics based on post/video type

---

lib/app/features/feed/create_article/providers/create_article_provider.c.dart
lib/app/features/feed/create_post/providers/create_post_notifier.c.dart

This PR adds a support for `unclassified` topics, which is automatically added to posts/article when no other topics are selected.

feat: add support for unclassified topic in posts and articles

---

lib/app/features/wallets/views/pages/import_token_page/import_token_page.dart

https://github.com/user-attachments/assets/1c613389-0c62-476f-a858-70a6580a186f

fix: close the Manage coins page after token import

---

lib/app/components/scroll_view/ion_pull_to_refresh_loading_indicator.dart

This PR reverts [this PR](https://github.com/ice-blockchain/ion-app/pull/1350) related to pull to refresh indicator size.

revert: pull to refresh indicator size

---

lib/app/features/config/providers/config_repository.c.dart
lib/app/features/feed/providers/feed_config_provider.c.dart
lib/app/features/feed/providers/feed_user_interests_provider.c.dart
lib/app/features/force_update/providers/force_update_provider.c.dart
lib/app/features/push_notifications/providers/app_translations_provider.c.dart
lib/app/features/user/providers/service_pubkeys_provider.c.dart

Replaced recursive call in getConfig with a fallback cache check to prevent potential infinite recursion when network returns no data and cache is empty. Now throws AppConfigNotFoundException instead of re-calling itself with refreshInterval = -1.
The original implementation called getConfig() recursively with refreshInterval = -1 when both the cache and network returned no data. If the network kept returning null (e.g., 204 No Content), this led to repeated self-calls with no exit condition, eventually causing a StackOverflowError due to infinite recursion.

fix: fix ConfigRepository getConfig.refreshInterval=-1 recursion issue

---

lib/app/features/components/ion_connect_avatar/ion_connect_avatar.dart
lib/app/features/config/providers/config_repository.c.dart

Problem:
When server returns 204 No Content (indicating cached data is up-to-date), the cache timestamp wasn't being updated. This caused infinite repeated network requests every time getConfig was called, as the cache was always considered stale.
Root cause:
- `_getFromNetwork` returns null on 204 No Content
- Cache timestamp was only updated when `networkData != null`
- Without timestamp update, subsequent calls treated cache as expired
- Always update cache timestamp when server returns 204 No Content

fix: update cache timestamp in case 204 response in ConfigRepository

---

lib/app/features/chat/components/messaging_header/one_to_one_messaging_header.dart
lib/app/features/chat/e2ee/providers/encrypted_deletion_request_handler.c.dart
lib/app/features/chat/e2ee/providers/encrypted_direct_message_handler.c.dart
lib/app/features/chat/e2ee/providers/encrypted_direct_message_reaction_handler.c.dart
lib/app/features/chat/e2ee/views/pages/one_to_one_messages_page.dart
lib/app/features/chat/recent_chats/views/components/recent_chat_tile/recent_chat_tile.dart
lib/app/features/chat/recent_chats/views/pages/recent_chats_timeline_page/recent_chats_timeline_page.dart
lib/app/features/chat/views/pages/conversation_page/conversation_page.dart
lib/app/features/chat/views/pages/new_chat_modal/new_chat_modal.dart
lib/app/features/core/providers/env_provider.c.dart
lib/app/features/feed/providers/feed_user_interest_picker_provider.c.dart
lib/app/features/ion_connect/providers/ion_connect_entity_provider.c.dart
lib/app/features/push_notifications/providers/notification_response_handler.c.dart
lib/app/features/search/views/pages/chat/components/chat_search_results_list_item.dart
lib/app/features/user/pages/profile_page/components/profile_details/profile_actions/profile_actions.dart
lib/app/features/user/pages/profile_page/pages/request_coins_form_modal/request_coins_form_modal.dart
lib/app/features/user_metadata/database/dao/user_metadata_dao.c.dart
lib/app/features/user_metadata/database/tables/user_metadata_table.c.dart
lib/app/features/user_metadata/database/user_metadata_database.c.dart
lib/app/features/user_metadata/providers/user_metadata_from_db_provider.c.dart
lib/app/features/user_metadata/providers/user_metadata_sync_provider.c.dart
lib/app/router/chat_routes.dart

- Syncs E2EE conversations user metadata to the local database
- Pull to refresh (always forces sync of existing conversation profiles)
- New event (30014, 5, 7) triggers check of the users metadata (sync window controller by env variable)
- User opened one-to-one conversation triggers check of users metadata
- Any new master pubkey passed to the flows which doesn't exist in the db causes force update

feat: user metadata from database

---

lib/app/features/chat/views/components/message_items/message_types/visual_media_message/visual_media_content.dart

This PR fix stops blurhash from displaying when a local file is available in the visual media message component. As a result, in the stack, if we use blurhash under the image and it has a transparent area, it appears as if it hasn't loaded.
N/A
ION-3006

fix(chat): prevent displaying blurhash when actual media is ready to display

---

lib/app/features/wallets/views/pages/manage_coins/components/import_token_action_button.dart
lib/app/features/wallets/views/pages/manage_coins/manage_coins_page.dart
lib/app/features/wallets/views/pages/manage_coins/providers/manage_coins_provider.c.dart

Add enable/disable mechanism for provider to prevent saving the prev state of the coin list.
ION-3017

fix: disable manage coins provider when opening token import page

---

android/app/src/main/kotlin/io/ion/app/MainActivity.kt
android/app/src/main/kotlin/io/ion/app/VideoEditorModule.kt
ios/Runner/AppDelegate.swift
ios/Runner/VideoEditorModule.swift
lib/app/services/media_service/banuba_service.r.dart

This PR changes banuba editor maximum video length setting from default 120 seconds to 60 seconds for stories.

feat: limit story video length to 60 seconds

---

lib/app/features/feed/stories/data/models/story_viewer_state.f.dart
lib/app/features/feed/stories/providers/story_viewing_provider.r.dart
lib/app/features/feed/stories/views/pages/story_viewer_page.dart

This PR fixes:
1. An issue where after viewing multiple stories multiple times, `storyViewingControllerProvider` returned controllers with wrong, old indexes and caused random stories to be displayed instead of the correct ones.
2. If there are multiple stories for a given user but some of them were already viewed, it starts displaying from the unseed ones.

fix: remove keepAlive from storyViewingControllerProvider so it resets the indexed when stories viewer is reentered

---

lib/app/features/wallets/providers/send_asset_form_provider.r.dart
lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart
pubspec.lock

Previously, if someone requested more money than the user had available, the user couldn’t send any amount in response to that request. This PR allows the Amount field to be editable in such cases, so the user can choose to send a smaller amount instead.
ION-2852

fix: make Amount field editable on SendCoinsForm

---

lib/app/router/components/navigation_app_bar/collapsing_app_bar.dart

Show the background behind the `child`, so the first one will not absorb the pointer.
ION-3092
https://github.com/user-attachments/assets/4f5e99d9-ea9d-4848-a897-f5f7bacf67cc

fix: put the background in the stack to the correct place to avoid absorbing pointer

---

pubspec.lock

- Returns to previous pubspec.lock without updating the depth, new version causes Android builds to fail

fix: recover old pubspec.lock

---

lib/app/components/image/ion_network_image.dart
lib/app/features/feed/stories/views/components/story_viewer/components/viewers/image_story_viewer.dart

This PR fixes an issue where a broken image icon was shown for loading story images instead of loading indicator.

fix: use correct loading indicator for stories images

---

lib/app/features/feed/stories/views/components/story_viewer/components/viewers/video_story_viewer.dart

This PR fixes an issue where vertical videos had their corners cut in stories viewer.

fix: border radius for vertical story videos

---

lib/app/features/feed/create_post/views/pages/post_form_modal/components/video_preview_edit_cover.dart
lib/app/features/feed/stories/providers/media_editing_service.r.dart
lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart
lib/app/services/media_service/banuba_service.r.dart

This PR fixes an issue where canceling the video editing flow for stories would still end up with navigation to story preview page

fix: story preview shown after video edit flow is cancelled

---

ios/Runner/PhotoEditorModule.swift

This PR fixes an issue where any image that went through banuba editor ended up being saved to device's photo gallery

fix: stop posted story images from saving to phone photo gallery

---

lib/app/services/media_service/aspect_ratio.dart

This PR increases max aspect ratio for feed images from 2 to 3 to better handle very wide images.
Before:
After:

fix: increase max aspect ratio for feed images to 3

---

lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart

Fixed an issue where the main modal remained open after publishing a post from the profile tab.

fix: automatically close main modal after post creation from the profile tab

---

lib/app/features/chat/model/database/dao/conversation_message_dao.dart

This PR removes the unnecessary inner join with eventMessageTable in `getUnreadMessagesCount`
N/A
ION-3127

chore: remove unnecessary inner join with eventMessageTable in getUnreadMessagesCount

---

lib/app/components/scroll_view/load_more_builder.dart
lib/app/features/feed/views/components/reply_list/reply_list.dart

Fixed double-loading indicators appearing during pull-to-refresh on the reply page.
**Problem:**
- Two loading indicators were shown simultaneously when refreshing replies
- Pull-to-refresh indicator at top + LoadMoreBuilder indicator at bottom
**Solution:**
- Added `showIndicator` parameter to `LoadMoreBuilder`
- Track refresh state in `ReplyList` using `useState` hook
- Hide LoadMoreBuilder indicator during pull-to-refresh
3099

fix: prevent duplicate loading indicators during pull-to-refresh in reply list

---

lib/app/features/user_profile/providers/user_metadata_from_db_provider.r.dart

This PR fixes the flicker issue when user scrolls the conversation page. `UserMetadataFromDbNotifier` keeps the previous value even chat tile widget is disposed so when it ll be rendered again, it uses the existing user metadata to prevent flicker issue.
N/A
ION-3132

fix: prevent flicker issue on conversations page

---

lib/app/components/url_preview/url_preview.dart

This PR adds an initial notify for all url preview meta listeners to handle a case where an already previously created provider is used.

fix: add initial listeners notify in url preview when url is already loaded during first build

---

lib/app/features/chat/e2ee/providers/encrypted_repost_handler.r.dart

This PR fixes the issue where loading gets stuck on the skeleton when a user sends a reaction to a story. When a user send a story reaction message, it triggers syncing the user profile to the local database, including the referenced story's owner master pubkey.
3142

fix(chat): sync user info for replied story to load metadata

---

lib/app/features/chat/e2ee/views/components/one_to_one_messages_list.dart
lib/app/features/chat/views/components/scroll_to_bottom_button.dart
pubspec.lock
pubspec.yaml

This PR replaces [scrollable_positioned_list](https://pub.dev/packages/scrollable_positioned_list) with [super_sliver_list](https://pub.dev/packages/super_sliver_list) to avoid unnecessary rebuilds in the message list.
Previously, when a message was added or removed, `scrollable_positioned_list` caused all visible items to rebuild. This led to UI flickering and issues like stopping an ongoing voice message playback.
By switching to `super_sliver_list` and using `findChildIndexCallback`, we can target specific items without triggering a full rebuild. This improves performance and prevent flicker issue of voice, photo, video messages.
- Tested the scroll to item and it works well.
3206
https://github.com/user-attachments/assets/3ee3d533-accf-4cf3-9d2c-3c0301d0b486

fix: message list rebuild issue causing flicker and audio playback interruption

---

lib/app/features/feed/views/components/post/components/post_body/post_body.dart
lib/app/templates/basic.json
lib/app/templates/template.f.dart
lib/app/theme/app_colors.dart

This PR introduces a new color named `anakiwa` to the app’s color scheme. It is used specifically to style mention text within shared post messages.
N/A
3242

fix: ui issue shared post with mention

---

lib/app/features/feed/providers/user_posts_provider.r.dart

This PR fixes an issue where a created story was visible on profile's post's tab because of wrong subscription filter.

fix: stories visible on profile after posting

---

lib/app/features/chat/views/components/message_items/message_types/text_message/text_message.dart

This PR fixes a layout issue where chat messages containing manually added new lines (\n) could cause overflow in the message bubble.
N/A
3248

fix(chat): prevent overflow when message contains new lines

---

lib/app/features/feed/views/components/post/components/post_body/post_body.dart
lib/app/features/feed/views/components/url_preview_content/url_preview_content.dart

Fixes a flickering issue in the feed caused by posts with URLs triggering metadata rendering during scroll.
N/A
3267
https://github.com/user-attachments/assets/eb3bea10-b31f-4ace-afd9-83a98d6ca5b5

fix: prevent flicker when rendering URL metadata in feed scroll

---

lib/app/features/chat/recent_chats/providers/replied_message_list_item_provider.r.dart
lib/app/features/chat/views/pages/conversation_page/conversation_page.dart

This PR fixes a visual flicker that occurred when scrolling to a replied message in chat. The layout now updates smoothly when the replied message becomes visible.
N/A
3139

fix: remove flicker when scrolling to replied message in chat

---

lib/app/features/chat/views/components/message_items/message_types/post_message/shared_post_message.dart

Shared post videos in chat now continue playing from where they stopped when scrolled back into view. The paused position is saved using keep-alive.
N/A
3270
https://github.com/user-attachments/assets/d8fce7bd-5630-4f26-a1cb-c1d6e2e2827c

feat: resume shared post video in chat from paused position on scroll return

---

lib/app/features/chat/model/database/dao/event_message_dao.dart

Fixes an issue where a small empty container remained visible in the UI after cancelling a video message.
N/A
3255
https://github.com/user-attachments/assets/e114599d-129d-4aac-a7a3-f9804c9cc7ef

fix: remove leftover container after cancelling video message

---

lib/app/features/core/providers/exception_presenter_provider.r.dart
lib/l10n/app_en.arb

Previously on the onboarding we were showing a not user friendly error message, like `SendEventException: events[{"kind":0, "id": ....`.
I replaced it with a custom error messages.
ION-3271

fix: add custom title and description for SendEventException

---

lib/app/features/chat/views/components/message_items/message_types/post_message/shared_story_message.dart
lib/app/features/feed/stories/data/models/story_viewer_state.f.dart
lib/app/features/feed/stories/hooks/use_story_progress_controller.dart
lib/app/features/feed/stories/hooks/use_story_video_playback.dart
lib/app/features/feed/stories/providers/story_viewing_provider.r.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/stories_swiper.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/story_content.dart
lib/app/features/feed/stories/views/components/story_viewer/components/core/user_story_page_view.dart
lib/app/features/feed/stories/views/components/story_viewer/components/progress/story_progress_bar_container.dart
lib/app/features/feed/stories/views/components/story_viewer/components/viewers/story_viewer_content.dart
lib/app/features/feed/stories/views/components/story_viewer/components/viewers/video_story_viewer.dart
lib/app/features/feed/stories/views/pages/story_viewer_page.dart
lib/app/features/feed/views/pages/feed_page/components/stories/hooks/use_preload_story_media.dart
lib/app/features/feed/views/pages/topics_modal/selected_topics.dart
test/app/features/stories/data/story_models_test.dart
test/app/features/stories/providers/story_controllers_test.dart
test/robots/mixins/story_state_mixin.dart
test/robots/stories/story_progress_bar_robot.dart
test/robots/stories/story_viewer_robot.dart
test/robots/stories/video_playback_robot.dart

This PR fixes an issue where swiping between users in story viewer page showed the same user on both side of the cube navigation.
3287
https://github.com/user-attachments/assets/dc7a8283-7e4a-42dc-af71-22f97f934460

fix: same story visible on both pages when swiping between users in story viewer page

---

ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
ios/Runner/VideoEditorModule.swift

This PR fixes an issue where even if the `maxVideoDuration` was set to less than 60 seconds, it was capped to 60 seconds on ios.

fix: allow maximum video length in banuba on ios to get under 60 seconds

---

android/app/src/main/kotlin/io/ion/app/MainActivity.kt
android/app/src/main/kotlin/io/ion/app/VideoEditorModule.kt
ios/Runner/AppDelegate.swift
ios/Runner/VideoEditorModule.swift
lib/app/features/feed/stories/providers/media_editing_service.r.dart
lib/app/features/feed/stories/views/pages/story_record_page.dart
lib/app/services/media_service/banuba_service.r.dart

This PR disabled banuba editor step with video cover flow selection for stories.
https://github.com/user-attachments/assets/afb18121-6cb8-4cf1-893d-7763fdb96a57

feat: disable cover selection for stories creation flow

---

lib/app/features/chat/e2ee/providers/e2ee_delete_event_provider.r.dart
lib/app/features/chat/e2ee/providers/encrypted_deletion_request_handler.r.dart
lib/app/features/chat/model/database/dao/conversation_message_dao.dart
lib/app/features/chat/model/database/dao/conversation_message_reaction_dao.r.dart

- Marks message as delete in local DB to represent result of user action
- Revert change if request to send kind 5 failed
ION-3256

fix: mark message as deleted immediately

---

lib/app/features/wallets/views/pages/wallet_page/components/empty_state/empty_state.dart
lib/app/features/wallets/views/pages/wallet_page/components/nfts/nfts_tab_footer.dart
lib/app/features/wallets/views/pages/wallet_page/tab_type.dart

Previosly we didn't show "Receive NFT" button if user already has at least 1 NFT. This PR makes it to show that button always.
ION-3328

feat(wallet): add Receive NFT button to NFT tab

---

lib/app/features/feed/views/components/post/components/post_body/post_body.dart
lib/app/features/wallets/views/components/coins_list/coin_item.dart
lib/app/features/wallets/views/pages/coins_flow/network_list/network_item.dart
lib/app/features/wallets/views/utils/crypto_formatter.dart
test/app/features/wallets/utils/crypto_formatter_test.dart

Apply advanced rules to crypto formatting.
Rules:
**0 < value < 0.000001 (10 * (10^-7))** => display the value in the next way `0.0(n)d`, where
n - number of zeros after the dot
d - first non-zero value
**0.000001 < value < 10** => display max 6 decimal digits + integer part 
**value > 10** => display only 2 decimal digits + full integer part
ION-2515

feat: crypto formatting

---

lib/app/features/wallets/views/pages/coins_flow/send_coins/components/send_coins_form.dart

Previously the Send Coins form didn't have a USD amount next to the amount field. This PR makes it visible.
ION-3335

fix: add "usd amount" to Send Coins form

---

lib/app/features/feed/views/components/post/components/post_body/components/post_media/components/post_media_carousel_vertical.dart

This PR remove extra padding from `PostMediaCarouselVertical` widget.
N/A

fix: remove unnecessary padding from post carousel

---

lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart
lib/app/features/force_update/providers/force_update_provider.r.dart

This PR fixes an issue where navigation callbacks (like pop results) would break after the app was resumed, due to unnecessary GoRouter stack refreshes.
- The GoRouter configuration uses refreshListenable: AppRouterNotifier(ref) to watch several providers for changes.
- In AppRouterNotifier, we listen to providers like forceUpdateProvider, authProvider, and others, triggering notifyListeners() on updates.
- forceUpdateProvider always set a new state when the app switched to resumed, even if nothing changed.
- This caused GoRouter to refresh the whole navigation stack every time the app was resumed, breaking pop callbacks.
- The fix avoids unnecessary state changes in forceUpdateProvider on app resume, so navigation callbacks now work as expected.
- Hide the main feed modal when the user …

fix: prevent go_router stack refresh on every app resume to keep pop callback working

---

lib/app/features/chat/community/models/entities/community_definition_data.f.dart
lib/app/features/chat/e2ee/providers/send_chat_message/send_e2ee_chat_message_service.r.dart
lib/app/features/chat/e2ee/providers/send_chat_message_service.r.dart
lib/app/features/chat/e2ee/views/pages/one_to_one_messages_page.dart
lib/app/features/chat/model/database/dao/conversation_dao.dart
lib/app/features/chat/providers/exist_chat_conversation_id_provider.r.dart
lib/app/features/chat/providers/muted_conversations_provider.r.dart
lib/app/features/chat/providers/share_feed_item_to_chat_provider.r.dart
lib/app/features/feed/stories/providers/story_reply_provider.r.dart
lib/app/services/uuid/generate_conversation_id.dart

- Replaces current approach for one-to-one conversations to use UUID v5 which produces same id for same participants
- Makes generation method isolated from `ref`
- Fixes bug when only author send messages and existing conversation Id can't be found
?

feat: Use v5 and v7 as conversation identifiers

---

lib/app/features/feed/stories/views/components/story_viewer/components/viewers/video_story_viewer.dart

This PR fixes an issue where story videos were stretched to fill the screen.
N/A
3376
https://github.com/user-attachments/assets/39c46b99-306d-49b1-b3ec-d695a6d1b2e0

fix: prevent story video from stretching to fit screen

---

lib/app/features/ion_connect/providers/global_subscription.r.dart

This PR enhances global subscription handling by:
•	Cancelling the active event stream subscription when the app moves to the background.
•	Reinitializing the subscription when the app returns to the foreground (AppLifecycleState.resumed).
•	Preventing potential event loss caused by OS-level network restrictions during background state.
N/A
part of 3243

fix: cancel global subscription on background and reinitialize on resume to prevent event loss

---

lib/app/features/feed/create_post/providers/create_post_notifier.m.dart
lib/app/features/feed/data/models/entities/modifiable_post_data.f.dart
lib/app/features/feed/providers/counters/reposted_events_provider.r.dart
lib/app/features/feed/providers/counters/reposts_count_provider.r.dart
lib/app/features/feed/providers/feed_data_source_builders.dart
lib/app/features/feed/reposts/models/post_repost.f.dart
lib/app/features/feed/reposts/providers/optimistic/intents/toggle_repost_intent.dart
lib/app/features/feed/reposts/providers/optimistic/post_repost_provider.r.dart
lib/app/features/feed/reposts/providers/optimistic/repost_sync_strategy.dart
lib/app/features/feed/reposts/providers/optimistic/repost_sync_strategy_provider.r.dart
lib/app/features/feed/stories/views/components/story_viewer/components/viewers/image_story_viewer.dart
lib/app/features/feed/stories/views/components/story_viewer/components/viewers/story_viewer_content.dart
lib/app/features/feed/stories/views/pages/story_preview_page.dart
lib/app/features/ion_connect/model/entity_data_with_parent.dart
lib/app/features/ion_connect/model/related_event_marker.dart
lib/app/features/ion_connect/model/source_post_reference.f.dart
lib/app/features/optimistic_ui/features/likes/post_like_provider.r.dart
test/app/features/feed/providers/counters/reposted_events_provider_test.dart
test/app/features/feed/reposts/models/post_repost_test.dart
test/app/features/feed/reposts/providers/optimistic/repost_intent_strategy_test.dart
test/app/features/feed/reposts/providers/optimistic/repost_sync_strategy_test.dart

When users share a post as a story by tapping "Add to story", the repost counter increments. This happens because the story creation flow passes the quotedEvent parameter, which creates a quote relationship and increases the quotesCount. Since the repost counter displays repostsCount + quotesCount, this causes the unintended increment.
Changes:
- Modified StoryPreviewPage to pass sourcePostReference instead of quotedEvent for post screenshots
- Added sourcePostReference field to ModifiablePostData to store reference to original post
- Implemented "a" tag with "mention" marker to track source post without affecting counters
- Updated EntityDataWithRelatedEvents.fromTags() to properly handle "a" tags with "mention" marker
- Removed ReferencesSearchExtension filter from …

fix: post sharing as a story increments repost counter

---

lib/app/features/feed/create_article/views/pages/article_form_modal/article_form_modal.dart
lib/app/features/feed/create_article/views/pages/article_preview_modal/article_preview_modal.dart
lib/app/features/feed/stories/views/pages/story_preview_page.dart
lib/app/features/feed/stories/views/pages/story_record_page.dart
lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart
lib/app/router/app_routes.gr.dart
lib/app/router/feed_routes.dart
lib/app/router/main_tabs/components/tab_item.dart

This PR fixes an issue where:
•	When the user shares content from the Profile tab, the app incorrectly switches to the Feed tab.
•	The Feed main modal remains open after sharing, even though the user did not explicitly open it.
3322

fix: feed and profile main modal navigation routing fixes

---

pubspec.lock
pubspec.yaml

This PR updates the following dependencies to their latest versions to fix the reversed (mirrored) front camera preview:
- `camera`
- `camera_android_camerax`
> Related Flutter issue: https://github.com/flutter/flutter/issues/156974
> Fix implemented in:  https://github.com/flutter/flutter/pull/170600
3422

fix: update camera dependencies to fix front camera mirroring issue

---

lib/app/features/feed/views/pages/feed_main_modal/feed_main_modal_page.dart
lib/app/features/gallery/views/pages/media_picker_page.dart

Fixes a routing issue that occurred when the user entered content in the share modal but then canceled. The app now correctly closes the modal and stays on the current tab without unintended navigation.
- keep media picker open after canceling banuba edit
3322-3439
https://github.com/user-attachments/assets/41a5728c-e6c8-4a50-8bff-4884bd03403e

fix: routing issue when user cancels sharing a post

---

analysis_options.yaml
lib/app/features/auth/views/pages/sign_up_passkey/sign_up_passkey_form.dart
lib/app/services/text_parser/model/text_matcher.dart
scripts/generate_code.sh
scripts/generate_tld_regex.dart
test/services/text_parser/text_parser_test.dart

- generate lib/generated/tlds_group.dart with list of all TLDs downloaded from latest https://data.iana.org/TLD/tlds-alpha-by-domain.txt;
- unfocus sign up passkey form before verify identity pop up to get rid of flickering;
https://github.com/user-attachments/assets/f857bf3f-adb9-4ff6-88f7-11e275758595
(if applicable)

chore: generate and inject whole tld list

---

lib/app/features/feed/stories/views/components/story_viewer/components/header/story_context_menu.dart

This PR fixes an issue where follow button on story viewer could only be used for unfollowing. It was updated to support both following and unfollowing.

fix: enable followed and unfollowed state for follow button in story viewer

---

lib/app/features/core/providers/ion_connect_media_url_fallback_provider.r.dart
lib/app/features/ion_connect/providers/relays/relay_picker_provider.r.dart
lib/app/features/ion_connect/utils/file_storage_utils.dart
lib/app/features/user/providers/relays/ranked_user_relays_provider.r.dart
lib/app/features/user/providers/relays/relevant_user_relays_provider.r.dart
lib/app/services/ion_connect/ion_connect_relays_ranker.r.dart

This PR excludes unreachable relays from the list of ranked and relevant relays.
3463

fix: exclude unreachable relays after ranking

---

lib/app/features/wallets/views/components/coins_list/coin_item.dart

`CoinsGroupItem` is used on different pages, like `Receive coins`, `Send coins` modals, etc. These pages have a search. For example, a user would paste the word "ice" in the search and see 100 different coins with the word "ice" in the name, symbol, or something else.
Because of the line
`ref.read(networkSelectorNotifierProvider(symbolGroup: coinsGroup.symbolGroup));`
for each of these 100 coins
`ref.watch(syncedCoinsBySymbolGroupProvider(symbolGroup));`
would be triggered, which would result in the mobile client making hundreds (or thousands) of requests in one session.
ION-3460

fix: remove image precache from the CoinsGroupItem

---

lib/app/features/protect_account/authenticator/views/pages/setup_authenticator/authenticator_setup_options_page.dart

This PR adds a missing padding to authenticator options in security menu.

fix: add authenticator options padding

---

lib/app/features/chat/e2ee/views/pages/one_to_one_messages_page.dart
lib/app/features/chat/views/components/message_items/message_types/text_message/text_message.dart

This PR addresses two main issues on the chat screen for both iOS and Android:
- Reduces UI lag when opening chat by offloading blocking logic ( text parsing) to background isolates.
- Fixes the incorrect appearance of an empty state when messages exist
N/A
3490

fix: reduce chat open lag and prevent false empty message state

---

lib/app/features/feed/providers/feed_following_content_provider.m.dart
lib/app/features/feed/providers/feed_for_you_content_provider.m.dart
lib/app/features/ion_connect/model/event_reference.f.dart
lib/app/features/ion_connect/model/events_metadata.f.dart
lib/app/features/ion_connect/model/events_metadata_builder.dart
lib/app/features/ion_connect/providers/entities_paged_data_provider.m.dart
lib/app/features/ion_connect/providers/ion_connect_event_parser.r.dart
lib/app/features/user/providers/relays/user_relays_manager.r.dart
lib/app/features/user/providers/user_events_metadata_provider.r.dart
lib/app/features/user/providers/verified_user_events_metadata_provider.r.dart
packages/ion_identity_client/lib/src/core/service_locator/ion_identity_clients/users_client_service_locator.dart
packages/ion_identity_client/lib/src/users/ion_connect_relays/data_sources/ion_connect_relays_data_source.dart
packages/ion_identity_client/lib/src/users/ion_connect_relays/ion_connect_relays_service.dart
packages/ion_identity_client/lib/src/users/ion_identity_users.dart

This PR adds a logic to refetch missing events on correct relays when previously chosen relay informs the app the requested event is missing, by a 21750 placeholder event.

feat: fetch missing entities on 21750 event

---

lib/app/features/core/providers/dio_provider.r.dart
lib/app/features/feed/nft/data/repositories/nft_identity_repository.r.dart
lib/app/features/feed/nft/providers/nft_identity_dio_provider.r.dart
lib/app/features/feed/nft/sync/nft_collection_sync_controller.r.dart

This PR reduces amount of logs for ION content NFT collection with 404 response. Previously it logged [http-error] with response (body+headers), which produced a lot of logs every 15s. Now it's 2 lines only.
Now logs look like this (Talker's extra lines are omited):
```
[Talker] ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ [http-request] [GET] https://staging.nft.identity.io/account/3ce59df2cddec7863e91ca6461cc7d3afc33cca1fd8d282c1f4996769803fdc1
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────
[Talker] ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ [debug] | 20:50:43 957ms | NFT collection …
```

fix: reduce logging for ION content NFT collection 404

---

lib/app/features/auth/views/pages/intro_page/intro_page.dart
lib/app/features/chat/views/pages/chat_media_page/components/chat_media_page_view.dart
lib/app/features/core/views/pages/splash_page.dart
lib/app/features/feed/stories/views/components/story_preview/media/story_video_preview.dart
lib/app/features/video/views/pages/video_page.dart
lib/app/hooks/use_auto_play.dart
lib/app/router/providers/go_router_provider.r.dart

- Fixed issue when for unauthorised users into video starts from the beginning after the splash one. it has the same segment at the beginning which supposed to be skipped for smooth transition;
- Fixed issue when splash video is played twice in some cases;
- Added useAutoPlay to reduce code duplication;

fix: intro and splash video fixes

---

lib/app/features/wallets/views/pages/wallet_page/view_models/nft_networks_view_model.dart

Previously, when a user switched from the NFTs tab to Coins and back to NFTs, the “Networks” filter state would reset to its initial state. I made the ViewModel non-autoDispose so that it preserves the filter state.
ION-3554
https://github.com/user-attachments/assets/3f7168c5-1040-4141-a4c6-06157610673f

fix(wallet): make `nftNetworksViewModelProvider` non-autoDispose

---

lib/app/features/feed/views/pages/article_details_page/components/articles_carousel_item.dart

user was proposed to block/follow/report himself on article details screen when he has more than 1 article.
context menu is hidden if current user is the owner of the post.
WTR: 
1. Log in the app.
2. Go to the Feed.
3. Publish 1st article.
4. Publish 2nd article.
5. Open 2nd article.
ION-3528
Own post          .          .          .              Another user post

fix: stop user blocking himself in article section

---

lib/app/features/feed/providers/feed_following_content_provider.m.dart
lib/app/features/feed/providers/feed_for_you_content_provider.m.dart

This PR fixes an issue where forYou fed was using a max retry count config from following and vice versa.

fix: use correct config retry multipliers for for you and following feed pages

---

lib/app/features/wallets/views/pages/manage_nfts/manage_nfts_page.dart

The reason of the bug is that ViewModel stays in memory when a user leaves the dialog. Reset the search query onInit fixes the issue.
ION-3674

fix(wallet): clear search query when NFTs networks dialog is opened

---

lib/app/router/main_tabs/components/profile_tab_button.dart

Previous fix for profile button wasn't sufficient. Design was changed and applied here
Small changes to the button profile size
ION-3694
slightly decreased size of the profile button
="image_url_here"> -->

fix:design changes for profile button

---

lib/app/features/feed/views/pages/fullscreen_media/components/image_carousel.dart

The bottom panel on image carousel shouldn't scroll with pageView swaps
Moved the panel out pf the pageView 
ION-3479
https://github.com/user-attachments/assets/87a38eb6-db73-4514-a915-f35111d0c6b0

fix:move CounterItemsFooter out of PageView in ImageCarousel to avoid scrolling effect on it

---

lib/app/features/chat/views/components/message_items/message_types/text_message/text_message.dart

This PR optimize text message rendering by using text scaler from context to prevent overlap issue for different screen zooms.
N/A
3705
[untitled.webm](https://github.com/user-attachments/assets/d384b404-968e-4aa1-ac04-f94e16663ef5)

fix: optimize text message rendering by using text scaler from context

---

lib/app/components/overlay_menu/overlay_menu.dart

Remove blinking effect on filters menu during the scroll
Effect was causes by auto close logic implemented earlier. To compliment it I added restriction on opening menu during the active scroll
ION-3717

fix:prevent opening overlay menu when scroll is active

---

lib/app/features/feed/reposts/models/post_repost.f.dart
lib/app/features/feed/reposts/providers/optimistic/post_repost_provider.r.dart

The issue with post repost provider was that it was watching ionConnectCacheProvider and rebuilding on any change in it
Rebuild rate dropped from 1000+ to 2. Solution is not really beautiful though.
ION-3502

fix: avoid unnecessary rebuilds in reposts provider

---

lib/app/features/protect_account/phone/provider/country_provider.r.dart
lib/app/features/protect_account/phone/provider/skip_countries_provider.r.dart

We want to be able to exclude some countries from the 2FA phone setup list. To do this, we want to get a remote config values.
- Added `skipCountriesIsoSet` provider
- Updated `countries` provider
ION-3458

feat(account): skip phone number countries from remote config for 2fa

---

lib/app/components/counter_items_footer/counter_items_footer.dart
lib/app/components/counter_items_footer/replies_counter_button.dart
lib/app/features/feed/views/pages/fullscreen_media/components/media_carousel.dart
lib/app/features/feed/views/pages/fullscreen_media/components/single_media_view.dart
lib/app/features/video/views/components/video_actions.dart
lib/app/features/video/views/pages/videos_vertical_scroll_page.dart
lib/app/router/media_picker_routes.dart
lib/app/router/profile_routes.dart

This PR changes the behaviour of reply button in full screen media pages so that it navigates to post/article detail pages.
https://github.com/user-attachments/assets/d5d854ec-b5ec-4b37-886a-c46fd04e7a24

feat: navigate to post details on reply tap on media full screen page

---

lib/app/features/push_notifications/data/models/ion_connect_push_data_payload.f.dart
lib/app/services/media_service/media_encryption_service.m.dart

currently, encrypted media could try alternative urls when being retrieved. this change ensures that all encrypted media is always fetched directly from the original url.
3757

fix: ensure encrypted media is fetched directly from the original url

---

lib/app/services/converters/dart_webp_to_jpeg_converter.dart
lib/app/services/local_notifications/local_notifications.r.dart
pubspec.lock
pubspec.yaml

This PR fixes an issue where android push notifications didn't contain any images an icons when push was received when app was in background
The main issue here is that we use ffmpegKit for converting push notification images from webp to jpeg. However this library [doesn't work on other isolates than main one](https://github.com/arthenica/ffmpeg-kit/issues/367). However firebase background notification handler runs on a background isolate. 
The solution uses a pure dart solution for image conversion that works on all isolates.
3570

fix: replace ffmpeg with pure dart implementation for webp to jpeg conversion on background push notification handler isolate

---

lib/app/router/main_tabs/components/tab_icon.dart
lib/app/router/main_tabs/main_tab_navigation.dart

Fix bottom navigation height
Removed SafeArea and calculate bottom padding manually
Allow bottom navigation bar to go under bottom safe area for some devices. depending on platform and system navigation mode.
ION-3789 Fix bottom menu height
iPhones : 
1. 16 Plus (bottom safe area is 34 px, 8px of our bottom navigation bar is underneath the safe area),
2. SE 3gen(showing as is - 9px padding between navbar buttons and system navigation panel) 
Android:
Sanmung S23: 
1. 3 buttons(showing as is - 9px padding between navbar buttons and system navigation panel),
2. gestures (bottom safe area is 16 px, padding between navbar buttons and system navigation panel reduced to 7px)
emulator: 
1. 2 buttons, (showing as is - 9px padding between navbar buttons and system navigation panel)
2. 3 buttons, …

fix: bottom menu height

---

lib/app/features/wallets/views/utils/crypto_formatter.dart
test/app/features/wallets/utils/crypto_formatter_test.dart

Starting from millions, add the abbreviation for the big crypto values:
1,200,000	              -  1.2M
18,308,397	              -  18.3M
508,920,000	              -  508.9M
7,320,000,000	      -  7.32B
18,308,397,101,537.31  -  18.308T
ION-3692

feat: add abbreviations for big crypto balances

---

lib/app/features/wallets/views/pages/coins_flow/send_coins/components/confirmation/transaction_result_sheet.dart
lib/app/features/wallets/views/pages/transaction_details/transaction_details.dart

Disable share button same as explorer button
ION-3872

fix: disable share button when explorer button is not active

---

lib/app/features/chat/views/components/message_items/message_types/post_message/shared_story_message.dart

- Introduced a new widget to display the owner's information for shared stories, including their avatar and display name.
- Updated the shared story message layout to include this new information.

feat: add story owner user info to shared story message component

---

lib/app/features/feed/views/components/post/post.dart

This PR enable autoPlay as true for quoted events.
N/A
3878
https://github.com/user-attachments/assets/11fefc83-3e14-4e95-8b12-e72af52b8675

fix: set autoplay true for quoted event videos

---

lib/app/features/wallets/views/pages/coins_flow/contact_picker/contact_picker_modal.dart

fix: get the user metadata from relay, if cached doesn't contain a wallet in the selected network

---

lib/app/features/wallets/views/utils/crypto_formatter.dart
test/app/features/wallets/utils/crypto_formatter_test.dart

If the crypto balance is less than 0.000001, then round it to 0.000001.
ION-3887

chore: remove the 0.0(n)d format for crypto balance

---

lib/app/features/ion_connect/providers/ion_connect_database_cache_notifier.r.dart

this PR prevents throwing `ShareableIdentifierDecodeException` exception when user bookmark a post.
N/A
3911

fix: optimize event reference handling in IonConnectDatabaseCache

---

lib/app/features/user/providers/account_notifications_sync_provider.r.dart

Exclude replies from post account notifications
ION-3899

fix: exclude reply marker from post filter in account notifications

---

lib/app/features/components/entities_list/components/repost_list_item.dart
lib/app/features/components/entities_list/entities_list.dart
lib/app/features/components/entities_list/list_cached_entities.dart
lib/app/features/components/entities_list/list_entity_helper.dart
lib/app/features/feed/views/components/article/article.dart
lib/app/features/feed/views/components/post/post.dart
lib/app/features/feed/views/pages/feed_page/feed_page.dart

- ListCachedObjects Inherited widget stores and provides entities and object sync to prevent jumping during scrolling
- Get rid of sync providers in posts, articles and reposts
- Check if user is blocked in async way 
ION-3847

feat: ListCachedObjects cache replacement of sync providers

---

lib/app/features/chat/e2ee/providers/chat_message_load_media_provider.r.dart

- Updated the logic to safely handle cases where the media attachment to load may be null, using `firstWhereOrNull` to avoid exceptions.
3917

fix(chat): handle null media attachment in chat message loading - StateError

---

lib/app/features/video/views/pages/videos_vertical_scroll_page.dart

This PR fixes an issue where clicking on the comment button on any of the videos in vertical videos page would always open the post details of the first video.

fix: navigate to proper post details page on comment button tap in vertical videos page

---

lib/app/features/auth/providers/auth_provider.m.dart
lib/app/features/core/providers/main_wallet_provider.r.dart
lib/app/features/protect_account/backup/providers/create_recovery_key_action_notifier.r.dart
lib/app/features/protect_account/secure_account/providers/recovery_credentials_enabled_notifier.r.dart
lib/app/features/push_notifications/background/firebase_messaging_background_service.dart
test/robots/stories/story_viewer_robot.dart

- **Before**: On logout, both `authenticatedIdentityKeyNames` and `currentIdentityKeyName` were cleared in `AuthState`. Dependents re-initialized in the same tick with a null pubkey, causing `UserMasterPubkeyNotFound`.
- **Change**: Moved `currentIdentityKeyName` out of `AuthState` into `currentIdentityKeyNameSelectorProvider` as the single source of truth.
- **Behavior**: On logout, first emit empty `authenticatedIdentityKeyNames` so dependents dispose; after a short delay (1s), set the selector to null. This prevents re-initialization with a null pubkey during teardown.
- **Result**: Eliminates `UserMasterPubkeyNotFound` on logout and stabilizes provider lifecycle across isolates and tests.
3910

refactor: update identity key name handling across app

---

lib/app/features/optimistic_ui/core/optimistic_service.dart

This PR fixes an issue where UI elements could subscribe to optmistic ui provider after it has emitted some events, causing them to not have most accurate state.

fix: add 1 event replay to optimistic service watch stream

---

ios/Runner.xcodeproj/project.pbxproj
lib/app/features/ion_connect/providers/ion_connect_entity_provider.r.dart
lib/app/features/user_profile/providers/user_profile_sync_provider.r.dart

When we load chat users metadata in bulk from most optimal relays some metadata can be missing, so additionally we will try to load it from write relay of each user individually

feat: fetch chat user metadata from write relay 

---

lib/app/services/text_parser/model/text_matcher.dart
test/services/text_parser/text_parser_test.dart

`#online+.` was parsed including the trailing `.` (but should be `#online+`)
updated regex in `HashtagMatcher`; added tests
ION-4008

fix(textparser): exclude trailing period from hashtag matches

---

lib/app/features/chat/model/database/dao/message_media_dao.r.dart

Enhance the `watchByEventId` method in `MessageMediaDao` to filter out duplicate entries based on `remoteUrl`, ensuring a cleaner stream of message media data. I could not find the root cause so did this workaround solution.
3962

fix: remove duplicates in message media stream

---

lib/app/features/feed/reposts/providers/optimistic/post_repost_provider.r.dart
test/app/features/feed/reposts/providers/load_initial_reposts_merge_test.dart

Reposts by current user appear with 1 reposts counter
Wrong data came from optimistic state. Which was uses as a cache, always initialised and had higher priority then cache.
Optimistic state should be temporary short living till successful sync.  Cache should be the primary source of repost data, not optimistic state. 
Also the tests are updated accordingly 
ION-4004

fix: reposts counter

---

lib/app/features/wallets/views/pages/manage_nfts/components/manage_nft_item.dart
lib/app/features/wallets/views/pages/wallet_page/view_models/nft_networks_view_model.dart
test/app/features/feed/reposts/providers/load_initial_reposts_merge_test.dart

1. Sort networks in the view model.
2. Change a bit the networks managing in the view model to avoid reloading network icons from the database.
ION-3993

fix: networks order on the manage nfts page

---

lib/app/features/chat/views/components/message_items/message_types/money_message/components/money_message_button.dart

Removing the border for the money request cancel button
ION-4026

fix: remove cancel button border on money request in chat

---

lib/app/features/ion_connect/providers/entities_paged_data_provider.m.dart
lib/app/features/user/pages/profile_page/pages/follow_list_modal/followers_list.dart
lib/app/features/user/providers/followers_provider.r.dart
lib/app/features/user/providers/search_users_provider.r.dart

This PR improves the loading and data appearance on followers list by awaiting all missing events fetch.
3964
Before:
https://github.com/user-attachments/assets/99c7f451-2c9e-49dc-a673-2b1da6a143e0
After:
https://github.com/user-attachments/assets/ea4f1f1e-458e-4b14-810b-47a717604bb8

fix: improve loading in followers list by awaiting all missing events

---

lib/app/components/overlay_menu/hooks/use_hide_on_tab_change.dart
lib/app/router/main_tabs/components/main_tab_navigation_container.dart

The context menu on the full-screen chat media preview page was not showing.  
This PR restores the context menu so users can access actions (e.g., save, share, delete) as expected.  
4039

fix(chat): restore context menu on full-screen media preview

---

ios/Podfile.lock
lib/app/features/components/biometrics/hooks/use_on_suggest_biometrics.dart
lib/app/features/user/providers/biometrics_provider.r.dart
macos/Flutter/GeneratedPluginRegistrant.swift
packages/ion_identity_client/example/macos/Flutter/GeneratedPluginRegistrant.swift
packages/ion_identity_client/example/pubspec.lock
packages/ion_identity_client/lib/ion_identity.dart
packages/ion_identity_client/lib/src/auth/services/biometrics_service.dart
packages/ion_identity_client/lib/src/auth/services/credentials/create_new_credentials_service.dart
packages/ion_identity_client/lib/src/auth/services/key_service.dart
packages/ion_identity_client/lib/src/core/service_locator/ion_identity_clients/auth_client_service_locator.dart
packages/ion_identity_client/lib/src/signer/password_signer.dart
packages/ion_identity_client/pubspec.yaml
pubspec.lock

Add Additional check on Android, because local_auth.authorize() allows to authenticate 
even if biometrics are not set up on the device and it leads to native crush in 
local_auth_crypto.authenticate then. So we should not even suggest user to add biometrics
in this rare case.

fix: android biometrics crash

---

lib/app/features/chat/recent_chats/views/pages/recent_chats_timeline_page/recent_chats_timeline_page.dart

There was doubling of the separator

fix:remove redundant separator on chas page
